/**
 * Blueprint theme preset — engineering drafting paper aesthetic.
 * Dark navy backgrounds with CSS grid overlay, dashed section borders, outlined-only
 * method badges with no fill. All monospace, ALL-CAPS labels, technical annotation style.
 * Palette: #0a1628 navy · #1e90ff dodger blue · #7db8e8 text · #1e3a5f borders.
 */
import type { AppTheme } from '../contract';

// Outlined only — no background fill.
const methodBadgeBase = 'method-badge shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] rounded-none uppercase w-[36px] text-center border bg-transparent';

export const blueprintTheme: AppTheme = {
  name: 'blueprint',
  swatches: ['#0a1628', '#1e90ff', '#7db8e8'],
  fontFamily: "ui-monospace, 'JetBrains Mono', SFMono-Regular, Menlo, Consolas, monospace",

  appRoot: {
    root:              'flex flex-col h-full overflow-hidden bg-[#0a1628] bp-grid theme-blueprint',
    navPane:           'shrink-0 bg-[#061020] bp-grid-sm overflow-y-auto flex flex-col',
    detailPane:        'flex-1 min-w-0 bg-[#0a1628] bp-grid overflow-hidden',
    tryPane:           'shrink-0 bg-[#0a1628] bp-grid overflow-hidden',
    shortcutsBackdrop: 'fixed inset-0 bg-black/75 flex items-center justify-center z-50',
    shortcutsPanel:    'bg-[#061020] rounded-none border border-[#1e3a5f] shadow-xl shadow-black/60 w-72 mx-4 overflow-hidden',
    shortcutsHeader:   'flex items-center justify-between px-5 py-3.5 border-b border-[#1e3a5f]',
    shortcutsTitle:    'text-sm font-mono font-bold text-[#4a9eff] uppercase tracking-wider',
    shortcutsClose:    'text-[#3a6080] hover:text-[#7db8e8] text-xl leading-none transition-colors font-mono',
    shortcutsRow:      'flex items-center justify-between py-1.5 border-b border-[#152a48] last:border-0',
    shortcutsDesc:     'text-xs font-mono text-[#7db8e8]',
    shortcutsKbd:      'text-[10px] font-mono bg-[#040d18] text-[#4a9eff] px-2 py-0.5 rounded-none border border-[#1e3a5f] shrink-0',
  },

  nav: {
    container:         'shrink-0 bg-[#061020] bp-grid-sm overflow-y-auto flex flex-col h-full',
    divider:           'mt-1 border-t border-[#1e3a5f]',
    searchWrapper:     'px-4 py-3 border-b border-[#1e3a5f] shrink-0',
    searchInput:       'w-full pl-7 pr-6 py-2 text-[11px] font-mono border border-dashed border-[#1e3a5f] rounded-none bg-transparent text-[#7db8e8] placeholder-[#1e3a5f] focus:outline-none focus:border-[#1e90ff] transition-colors uppercase tracking-wider',
    searchIcon:        'absolute left-2.5 top-1/2 -translate-y-1/2 w-3 h-3 text-[#1e3a5f] pointer-events-none',
    searchClearButton: 'absolute right-2 top-1/2 -translate-y-1/2 text-[#1e3a5f] hover:text-[#7db8e8] leading-none text-sm font-mono',
    searchHint:        'absolute right-2 top-1/2 -translate-y-1/2 text-[9px] font-mono text-[#1e3a5f] border border-[#1e3a5f] rounded-none px-1 pointer-events-none leading-none',
    loadingSpinner:    'w-5 h-5 animate-spin text-[#1e90ff]',
    tabBar:            'flex gap-1 px-4 py-2 border-b border-[#1e3a5f]',
    tab:               { base: 'px-2.5 py-1 text-[11px] font-mono rounded-none transition-colors text-[#1e3a5f] hover:text-[#7db8e8] uppercase tracking-wider', active: 'bg-[#0a1e36] text-[#4a9eff] border border-[#1e3a5f]' },
    tagHeader:         'w-full flex items-center justify-between px-4 py-2.5 text-[10px] font-mono font-bold uppercase tracking-widest text-[#1e3a5f] hover:text-[#4a9eff] transition-colors',
    tagChevron:        'w-3 h-3 transition-transform',
    tagCount:          'text-[10px] font-mono text-[#1e3a5f]',
    endpointItem:      { base: 'nav-endpoint w-full flex items-center gap-2.5 px-4 py-2 text-left transition-colors font-mono text-[#3a6080] hover:text-[#7db8e8] hover:bg-[#0a1e36]/60', active: 'bg-[#0a1e36] text-[#c8e0ff]' },
    endpointPath:      'truncate text-[11px] font-mono',
    methodBadge:       { base: methodBadgeBase, get: 'border-[#4a9eff]/80 text-[#4a9eff]', post: 'border-[#4ade80]/70 text-[#4ade80]', put: 'border-[#fbbf24]/70 text-[#fbbf24]', delete: 'border-[#f87171]/70 text-[#f87171]', patch: 'border-[#c084fc]/70 text-[#c084fc]', options: 'border-[#1e3a5f] text-[#3a6080]', head: 'border-[#1e3a5f] text-[#3a6080]' },
    schemaItem:        { base: 'w-full text-left gap-2.5 px-4 py-2 transition-colors hover:bg-[#0a1e36]/60', active: 'bg-[#0a1e36]' },
    schemaName:        { base: 'truncate text-[11px] font-mono text-[#3a6080]', active: 'text-[#c8e0ff]' },
    schemaTypeBadge:   'shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] rounded-none border border-[#c084fc]/50 text-[#c084fc] bg-transparent uppercase',
    schemaDescription: 'mt-0.5 text-[10px] font-mono text-[#1e3a5f] truncate pl-[38px]',
    emptyState:        'text-[11px] font-mono text-[#1e3a5f]',
  },

  endpoint: {
    container:           'h-full flex flex-col',
    header:              'flex items-center gap-3 px-6 py-5 border-b border-dashed border-[#1e3a5f] shrink-0 h-[50px]',
    methodBadge:         { base: methodBadgeBase, get: 'border-[#4a9eff]/80 text-[#4a9eff]', post: 'border-[#4ade80]/70 text-[#4ade80]', put: 'border-[#fbbf24]/70 text-[#fbbf24]', delete: 'border-[#f87171]/70 text-[#f87171]', patch: 'border-[#c084fc]/70 text-[#c084fc]', options: 'border-[#1e3a5f] text-[#3a6080]', head: 'border-[#1e3a5f] text-[#3a6080]' },
    path:                'font-mono text-sm text-[#c8e0ff] font-bold tracking-wide',
    summary:             'text-sm font-mono text-[#7db8e8] mb-2 font-medium',
    description:         'text-xs font-mono text-[#3a6080]',
    deprecated:          'ml-auto text-[10px] font-mono bg-[#1e1a08] text-[#fbbf24] border border-[#fbbf24]/40 rounded-none px-2 py-0.5 uppercase',
    paramSection:        'border border-[#1e3a5f] rounded-none overflow-hidden',
    paramSectionTitle:   'text-xs font-mono font-bold uppercase tracking-wider text-[#1e3a5f] mb-4',
    paramLocTitle:       'text-[10px] font-mono font-bold uppercase tracking-wider text-[#1e3a5f] mb-3',
    paramRow:            'border-b border-[#152a48] last:border-0 hover:bg-[#0a1e36]/50 transition-colors',
    paramName:           'font-mono text-[11px] text-[#c8e0ff] font-bold',
    paramType:           'text-[10px] font-mono bg-[#0a1e36] text-[#4a9eff] rounded-none px-1.5 py-0.5 border border-[#1e3a5f]',
    paramRequired:       'text-[#f87171] text-[9px] font-mono font-bold ml-1',
    paramDescription:    'px-4 py-3 w-full text-xs font-mono text-[#3a6080]',
    mutedText:           'font-mono text-[#1e3a5f]',
    responseAccordion:   'border border-[#1e3a5f] rounded-none overflow-hidden divide-y divide-[#1e3a5f]',
    responseHeader:      'w-full flex items-center gap-3 px-4 py-3.5 hover:bg-[#0a1e36]/50 transition-colors text-left',
    responseStatusCode:  { base: 'text-xs font-mono font-bold', success: 'text-[#4ade80]', redirect: 'text-[#4a9eff]', clientError: 'text-[#fbbf24]', serverError: 'text-[#f87171]' },
    responseDescription: 'text-xs font-mono text-[#3a6080] flex-1',
    bodySection:         'px-3 py-1.5 bg-[#040d18] border-b border-[#1e3a5f] flex items-center gap-2',
    bodyContentType:     'text-[10px] font-mono text-[#1e3a5f]',
  },

  topBar: {
    container:              'relative flex items-center gap-4 px-6 h-16 border-b border-[#1e3a5f] bg-[#040d18] shrink-0 z-10',
    specTitle:              'text-sm font-mono font-bold text-[#c8e0ff] truncate uppercase tracking-wide',
    specVersion:            'text-[10px] font-mono text-[#3a6080] border border-[#1e3a5f] rounded-none px-1.5 py-px shrink-0 leading-tight',
    specDescription:        'text-[10px] font-mono text-[#3a6080] truncate leading-tight mt-px',
    noSpecIcon:             'w-7 h-7 rounded-none border border-[#1e3a5f] flex items-center justify-center shrink-0',
    noSpecIconSvg:          'w-4 h-4 text-[#1e3a5f]',
    noSpecTitle:            'text-sm font-mono font-bold text-[#1e3a5f] uppercase tracking-wide',
    divider:                'w-px h-5 bg-[#1e3a5f] mx-1 shrink-0',
    authButtonConfigured:   'flex items-center gap-1.5 text-xs font-mono rounded-none px-2.5 py-1.5 font-bold border transition-all shrink-0 text-[#4ade80] bg-[#0a1e10] border-[#4ade80]/50 hover:bg-[#0f2a18] uppercase tracking-wide',
    authButtonUnconfigured: 'flex items-center gap-1.5 text-xs font-mono rounded-none px-2.5 py-1.5 font-medium border transition-all shrink-0 text-[#3a6080] bg-transparent border-[#1e3a5f] hover:border-[#4a9eff] hover:text-[#7db8e8] uppercase tracking-wide',
    neutralButton:          'flex items-center gap-1.5 text-xs font-mono rounded-none px-2.5 py-1.5 font-medium border transition-all shrink-0 text-[#3a6080] bg-transparent border-[#1e3a5f] hover:border-[#4a9eff] hover:text-[#7db8e8] uppercase tracking-wide',
    loadButton:             'flex items-center gap-1.5 text-xs font-mono text-[#040d18] bg-[#1e90ff] hover:bg-[#4a9eff] active:bg-[#1670d0] rounded-none px-3 py-1.5 font-bold transition-colors shrink-0 uppercase tracking-wide',
  },

  themePicker: {
    dropdown: 'bg-[#061020] border border-[#1e3a5f] rounded-none shadow-xl shadow-black/60 py-1 overflow-hidden',
    item:     { base: 'w-full flex items-center gap-3 px-3 py-2 text-left hover:bg-[#0a1e36] transition-colors font-mono', active: 'bg-[#0a1e36] border-l-2 border-[#1e90ff]' },
    name:     'text-sm font-mono text-[#7db8e8] flex-1',
    check:    'w-3.5 h-3.5 text-[#1e90ff] shrink-0',
  },

  modal: {
    backdrop:    'fixed inset-0 bg-black/75 flex items-center justify-center z-50',
    container:   'bg-[#061020] rounded-none border border-[#1e3a5f] shadow-xl shadow-black/60 w-full mx-4 overflow-hidden',
    header:      'flex items-center justify-between px-5 py-4 border-b border-[#1e3a5f]',
    closeButton: 'text-[#3a6080] hover:text-[#7db8e8] text-xl leading-none font-mono',
    footer:      'px-5 py-3 bg-[#040d18] border-t border-[#1e3a5f]',
  },

  loadModal: {
    title:        'text-sm font-mono font-bold text-[#c8e0ff] uppercase tracking-wide',
    footerText:   'text-[10px] font-mono text-[#1e3a5f]',
    petstoreLink: 'text-xs font-mono text-[#4a9eff] hover:underline',
    urlLabel:     'block text-xs font-mono font-bold text-[#3a6080] mb-1.5 uppercase tracking-wide',
    urlInput:     'flex-1 text-xs font-mono border border-[#1e3a5f] rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] placeholder-[#1e3a5f] focus:outline-none focus:border-[#1e90ff] transition-colors',
    dividerLine:  'flex-1 border-t border-dashed border-[#1e3a5f]',
    dividerText:  'text-[10px] font-mono text-[#1e3a5f] uppercase tracking-wider',
    fileLabel:    'block text-xs font-mono font-bold text-[#3a6080] mb-1.5 uppercase tracking-wide',
    fileDropZone: 'flex items-center justify-center gap-2 border border-dashed border-[#1e3a5f] rounded-none px-4 py-5 cursor-pointer hover:border-[#1e90ff] hover:bg-[#0a1e36]/30 transition-colors',
    fileDropIcon: 'w-4 h-4 text-[#1e3a5f]',
    fileDropText: 'text-xs font-mono text-[#3a6080]',
    errorBanner:  'text-xs font-mono text-[#f87171] bg-[#200a10] border border-[#f87171]/40 rounded-none px-3 py-2',
  },

  authModal: {
    tabBar:            'flex gap-1 px-4 py-2 bg-[#040d18] border-b border-[#1e3a5f] overflow-x-auto',
    tabActive:         'px-3 py-1.5 text-[11px] font-mono font-bold rounded-none bg-[#0a1e36] text-[#4a9eff] border border-[#1e3a5f] flex items-center gap-1.5 shrink-0 uppercase tracking-wide',
    tabInactive:       'px-3 py-1.5 text-[11px] font-mono rounded-none text-[#1e3a5f] hover:text-[#7db8e8] transition-colors flex items-center gap-1.5 shrink-0 uppercase tracking-wide',
    titleIcon:         'w-4 h-4 text-[#3a6080]',
    titleText:         'text-sm font-mono font-bold text-[#c8e0ff] uppercase tracking-wide',
    closeButton:       'text-xs font-mono bg-[#1e90ff] hover:bg-[#4a9eff] text-[#040d18] px-4 py-2 rounded-none font-bold transition-colors uppercase tracking-wide',
    schemeType:        'text-[10px] font-mono text-[#1e3a5f] uppercase',
    authorizedBadge:   'text-[9px] font-mono text-[#4ade80] bg-[#0a1e10] border border-[#4ade80]/40 rounded-none px-1.5 py-0.5 font-bold uppercase tracking-wide',
    schemeDescription: 'text-[10px] font-mono text-[#1e3a5f]',
    fieldLabel:        'block text-[10px] font-mono text-[#3a6080] mb-1 uppercase tracking-wide',
    fieldLabelHint:    'text-[#1e3a5f] font-mono',
    input:             'w-full text-xs font-mono border border-[#1e3a5f] rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] placeholder-[#1e3a5f] focus:outline-none focus:border-[#1e90ff]',
    tokenWrapper:      'flex items-stretch border border-[#1e3a5f] rounded-none overflow-hidden bg-[#040d18] focus-within:border-[#1e90ff] transition-all',
    tokenPrefix:       'px-2.5 flex items-center text-[10px] font-mono text-[#1e3a5f] bg-[#061020] border-r border-[#1e3a5f] shrink-0 select-none',
    tokenField:        'flex-1 text-xs px-2.5 py-2 bg-[#040d18] text-[#7db8e8] placeholder-[#1e3a5f] focus:outline-none font-mono min-w-0',
    saveButton:        'text-xs font-mono bg-[#1e90ff] hover:bg-[#4a9eff] text-[#040d18] px-3 py-1.5 rounded-none font-bold transition-colors uppercase tracking-wide',
    clearButton:       'text-xs font-mono border border-[#1e3a5f] text-[#3a6080] hover:border-[#4a9eff] hover:text-[#7db8e8] px-3 py-1.5 rounded-none font-medium transition-colors uppercase tracking-wide',
  },

  serverConfig: {
    chip: {
      base: 'flex items-center gap-1.5 text-[11px] font-mono px-2.5 py-1.5 rounded-none border transition-colors shrink-0 text-[#3a6080] border-[#1e3a5f] bg-transparent hover:border-[#4a9eff] hover:text-[#7db8e8] uppercase tracking-wide',
      open: 'bg-[#0a1e36] text-[#4a9eff] border-[#4a9eff]/60 hover:bg-[#0a1e36] hover:border-[#4a9eff]/60',
    },
    chipIcon:            'w-3 h-3 shrink-0 text-[#1e3a5f]',
    backdrop:            'fixed inset-0 bg-black/75 flex items-center justify-center z-[60]',
    popover:             'bg-[#061020] rounded-none border border-[#1e3a5f] shadow-xl shadow-black/60 w-full max-w-sm mx-4 overflow-hidden',
    popoverHeader:       'flex items-center justify-between px-5 py-4 border-b border-[#1e3a5f]',
    headerIcon:          'w-4 h-4 text-[#3a6080]',
    headerTitle:         'text-sm font-mono font-bold text-[#c8e0ff] uppercase tracking-wide',
    closeButton:         'text-[#3a6080] hover:text-[#7db8e8] text-xl leading-none font-mono',
    sectionDivider:      'px-5 py-4 border-b border-[#1e3a5f]',
    sectionLabel:        'block text-[10px] font-mono font-bold uppercase tracking-wider text-[#1e3a5f]',
    serverSelect:        'w-full text-[11px] font-mono border border-[#1e3a5f] rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] focus:outline-none focus:border-[#1e90ff] cursor-pointer',
    variableName:        'text-[11px] font-mono font-bold text-[#7db8e8]',
    variableDescription: 'text-[10px] font-mono text-[#1e3a5f] leading-tight mt-0.5',
    variableInput:       'text-[11px] font-mono border border-[#1e3a5f] rounded-none px-2.5 py-1.5 bg-[#040d18] text-[#7db8e8] focus:outline-none focus:border-[#1e90ff] w-full',
    resolvedSection:     'px-5 py-4 bg-[#040d18]',
    resolvedLabel:       'text-[10px] font-mono font-bold uppercase tracking-wider text-[#1e3a5f] mb-1.5',
    resolvedValue:       'text-[11px] font-mono text-[#1e90ff] break-all',
  },

  commandBar: {
    backdrop:       'fixed inset-0 bg-black/80 z-[60] flex items-start justify-center pt-[12vh]',
    container:      'bg-[#040d18] rounded-none border border-[#1e3a5f] shadow-2xl shadow-black/80 w-full max-w-lg mx-4 flex flex-col overflow-hidden max-h-[70vh]',
    searchRow:      'flex items-center gap-3 px-4 py-3 border-b border-[#152a48] shrink-0',
    searchIcon:     'w-4 h-4 text-[#1e3a5f] shrink-0',
    input:          'flex-1 bg-transparent text-sm font-mono text-[#7db8e8] placeholder-[#1e3a5f] outline-none',
    clearButton:    'text-[#1e3a5f] hover:text-[#7db8e8] text-lg leading-none shrink-0 transition-colors font-mono',
    groupTitle:     'px-4 py-1.5 text-[10px] font-mono font-bold uppercase tracking-widest text-[#1e3a5f] select-none',
    resultItem:     { base: 'w-full flex items-center gap-3 px-4 py-2.5 text-left transition-colors font-mono hover:bg-[#0a1e36]', active: 'bg-[#0a1e36] hover:bg-[#0a1e36] border-l-2 border-[#1e90ff]' },
    actionIcon:     { base: 'w-7 h-7 rounded-none flex items-center justify-center shrink-0 bg-[#061020] text-[#1e3a5f] border border-[#152a48]', active: 'bg-[#0a1e36] text-[#1e90ff] border-[#1e3a5f]' },
    resultLabel:    'text-sm font-mono text-[#7db8e8] truncate',
    resultSubtitle: 'text-xs font-mono text-[#1e3a5f] truncate mt-0.5',
    activeChevron:  'w-3.5 h-3.5 text-[#1e90ff] shrink-0',
    emptyIcon:      'w-8 h-8 text-[#1e3a5f] mb-3',
    emptyText:      'text-sm font-mono text-[#1e3a5f]',
    footer:         'shrink-0 flex items-center gap-4 px-4 py-2 border-t border-[#152a48] bg-[#040d18]',
    shortcutText:   'flex items-center gap-1 text-[11px] font-mono text-[#1e3a5f]',
    shortcutBadge:  'font-mono text-[10px] bg-[#061020] border border-[#1e3a5f] rounded-none px-1 py-px',
    specTitle:      'ml-auto text-[11px] font-mono text-[#1e3a5f] truncate',
    highlightMark:  'bg-[#1e90ff]/20 text-inherit not-italic',
  },

  schema: {
    tabBar:       'flex gap-1 px-3 py-2 bg-[#040d18] border-b border-[#1e3a5f]',
    tabActive:    'px-3 py-1 text-[11px] font-mono font-bold rounded-none bg-[#0a1e36] text-[#4a9eff] border border-[#1e3a5f] uppercase tracking-wide',
    tabInactive:  'px-3 py-1 text-[11px] font-mono rounded-none text-[#1e3a5f] hover:text-[#7db8e8] transition-colors uppercase tracking-wide',
    description:  'px-4 pt-3 pb-0 text-[11px] font-mono text-[#3a6080] leading-relaxed',
    exampleBlock: 'text-[11px] font-mono bg-[#040d18] border border-[#1e3a5f] rounded-none p-3 overflow-x-auto text-[#7db8e8] leading-relaxed',
  },

  schemaNode: {
    name:          'font-mono text-[11px] text-[#c8e0ff] font-bold',
    typeBadge:     'text-[10px] rounded-none px-1.5 py-0.5 font-mono border bg-transparent',
    nullableBadge: 'text-[9px] font-mono bg-[#061020] text-[#3a6080] rounded-none px-1 border border-[#1e3a5f]',
    constraint:    'text-[9px] font-mono text-[#1e3a5f]',
    enumValue:     'text-[9px] font-mono text-[#1e3a5f]',
    description:   'text-[11px] font-mono text-[#3a6080] mt-0.5 leading-relaxed',
    enumKey:       'font-mono text-[#7db8e8]',
    enumDesc:      'font-mono text-[#1e3a5f]',
    nestedBorder:  'border-l border-[#1e3a5f] ml-3 pl-3 mt-0.5',
    typeBadgeColors: {
      string:  'border-[#4ade80]/50 text-[#4ade80]',
      integer: 'border-[#4a9eff]/50 text-[#4a9eff]',
      number:  'border-[#4a9eff]/50 text-[#4a9eff]',
      boolean: 'border-[#c084fc]/50 text-[#c084fc]',
      object:  'border-[#fbbf24]/50 text-[#fbbf24]',
      array:   'border-[#4a9eff]/50 text-[#4a9eff]',
      default: 'border-[#1e3a5f] text-[#3a6080]',
    },
  },

  schemaDetail: {
    header:      'flex items-center gap-3 px-6 py-5 border-b border-dashed border-[#1e3a5f] shrink-0',
    typeBadge:   'text-[9px] font-bold font-mono px-[5px] py-[2px] rounded-none uppercase border bg-transparent',
    schemaName:  'font-mono text-sm text-[#c8e0ff] font-bold',
    description: 'text-sm font-mono text-[#3a6080] mb-6 leading-relaxed',
    sectionLabel:'text-xs font-mono font-bold uppercase tracking-wider text-[#1e3a5f] mb-4',
    schemaBox:   'border border-[#1e3a5f] rounded-none overflow-hidden',
    typeBadgeColors: {
      string:  'border-[#4ade80]/50 text-[#4ade80]',
      integer: 'border-[#4a9eff]/50 text-[#4a9eff]',
      number:  'border-[#4a9eff]/50 text-[#4a9eff]',
      boolean: 'border-[#c084fc]/50 text-[#c084fc]',
      object:  'border-[#fbbf24]/50 text-[#fbbf24]',
      array:   'border-[#4a9eff]/50 text-[#4a9eff]',
      default: 'border-[#1e3a5f] text-[#3a6080]',
    },
  },

  playground: {
    container:           'h-full flex flex-col bg-[#0a1628] bp-grid',
    header:              'flex items-center gap-2 px-5 border-b border-[#1e3a5f] shrink-0 h-[50px]',
    headerTitle:         'text-xs font-mono font-bold text-[#3a6080] uppercase tracking-wider',
    emptyState:          'h-full flex flex-col items-center justify-center text-center px-6 gap-3',
    emptyIconWrapper:    'w-10 h-10 rounded-none border border-[#1e3a5f] flex items-center justify-center',
    emptyIcon:           'w-5 h-5 text-[#1e3a5f]',
    emptyText:           'text-sm font-mono text-[#1e3a5f]',
    inputLabel:          'text-[10px] font-mono font-bold uppercase tracking-wider text-[#1e3a5f] mb-3',
    textInput:           'w-full text-xs font-mono border border-[#1e3a5f] rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] placeholder-[#1e3a5f] focus:outline-none focus:border-[#1e90ff] transition-colors',
    selectInput:         'w-full text-xs font-mono border border-[#1e3a5f] rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] focus:outline-none focus:border-[#1e90ff] cursor-pointer transition-colors',
    fileInput:           'block w-full text-xs font-mono text-[#3a6080] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-none file:border file:border-[#1e3a5f] file:text-xs file:font-mono file:font-medium file:bg-[#0a1e36] file:text-[#4a9eff] hover:file:bg-[#061020]',
    fileInputButton:     { base: 'file:py-1.5 file:px-3 file:rounded-none file:border file:border-[#1e3a5f] file:text-xs file:font-mono file:font-medium file:bg-[#0a1e36] file:text-[#4a9eff] hover:file:bg-[#061020]', hasFile: 'file:bg-[#0a1e36]' },
    bodyEditor:          'w-full text-[11px] font-mono border border-[#1e3a5f] rounded-none px-3 py-2.5 bg-[#040d18] text-[#7db8e8] placeholder-[#1e3a5f] focus:outline-none focus:border-[#1e90ff] resize-y transition-colors leading-relaxed',
    contentTypeSelector: 'text-[10px] font-mono text-[#1e3a5f] border border-[#1e3a5f] rounded-none px-2 py-0.5 bg-[#040d18]',
    sendButton:          { base: 'shrink-0 px-4 rounded-none text-xs font-mono font-bold transition-all bg-[#1e90ff] hover:bg-[#4a9eff] active:scale-[0.98] text-[#040d18] uppercase tracking-wide', loading: 'bg-[#0a1e36] text-[#1e3a5f] border border-[#1e3a5f] cursor-not-allowed', disabled: 'bg-[#0a1e36] text-[#1e3a5f] border border-[#1e3a5f] cursor-not-allowed' },
    responsePanel:       'h-full border-t border-[#1e3a5f] flex flex-col',
    responseStatus:      { base: 'text-[10px] font-mono font-bold rounded-none px-1.5 py-0.5 border bg-[#061020] text-[#3a6080] border-[#1e3a5f]', success: 'bg-[#0a1e10] text-[#4ade80] border-[#4ade80]/40', redirect: 'bg-[#0a1e36] text-[#4a9eff] border-[#4a9eff]/40', clientError: 'bg-[#1e1a08] text-[#fbbf24] border-[#fbbf24]/40', serverError: 'bg-[#200a10] text-[#f87171] border-[#f87171]/40' },
    responseTime:        'text-[10px] font-mono text-[#1e3a5f] border border-[#1e3a5f] rounded-none px-1.5 py-0.5',
    responseSize:        'text-[10px] font-mono text-[#1e3a5f]',
    responseTabs:        'flex items-center gap-2 px-4 py-2 border-b border-[#1e3a5f] bg-[#040d18] shrink-0',
    responseTab:         { base: 'px-2.5 py-1 text-[10px] font-mono rounded-none font-medium transition-colors text-[#1e3a5f] hover:text-[#7db8e8] uppercase tracking-wide', active: 'bg-[#0a1e36] text-[#4a9eff] border border-[#1e3a5f]' },
    responseBody:        'flex-1 overflow-auto bg-[#040d18]',
    responseEmpty:       'shrink-0 border-t border-[#1e3a5f] h-10 flex items-center justify-center text-[10px] font-mono text-[#1e3a5f]',
    errorBanner:         'mx-5 mb-4 px-3 py-2 bg-[#200a10] border border-[#f87171]/40 rounded-none text-xs font-mono text-[#f87171]',
  },

  authStatus: {
    sectionLabel:      'text-[10px] font-mono font-bold uppercase tracking-wider text-[#1e3a5f] mb-3',
    emptyText:         'text-[10px] font-mono text-[#1e3a5f]',
    schemeRow:         'flex items-center justify-between py-2.5 px-3 border border-[#1e3a5f] bg-transparent',
    schemeName:        'text-[11px] font-mono text-[#7db8e8]',
    schemeType:        'ml-1.5 text-[10px] font-mono text-[#1e3a5f]',
    authorizedBadge:   'text-[9px] font-mono text-[#4ade80] bg-[#0a1e10] border border-[#4ade80]/40 rounded-none px-1.5 py-0.5 font-bold uppercase tracking-wide',
    unauthorizedBadge: 'text-[9px] font-mono text-[#1e3a5f] bg-[#061020] border border-[#1e3a5f] rounded-none px-1.5 py-0.5 uppercase tracking-wide',
  },

  bodyEditor: {
    fileInput:    'block w-full text-xs font-mono text-[#3a6080] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-none file:border file:border-[#1e3a5f] file:text-xs file:font-mono file:font-medium file:bg-[#0a1e36] file:text-[#4a9eff] hover:file:bg-[#061020]',
    formatButton: 'absolute top-1.5 right-1.5 z-10 text-[10px] font-mono text-[#1e3a5f] hover:text-[#4a9eff] transition-colors px-1.5 py-0.5 rounded-none border border-transparent hover:border-[#1e3a5f] hover:bg-[#0a1e36]',
    textarea:     'w-full text-[11px] font-mono border border-[#1e3a5f] rounded-none px-3 py-2.5 bg-[#040d18] text-[#7db8e8] placeholder-[#1e3a5f] focus:outline-none focus:border-[#1e90ff] resize-y transition-colors leading-relaxed',
  },

  paramLabel: {
    nameText:        'font-mono text-[11px] text-[#c8e0ff] font-bold',
    nameDeprecated:  'font-mono text-[11px] line-through text-[#1e3a5f]',
    locPath:         'text-[9px] font-mono rounded-none px-1.5 py-0.5 leading-none text-[#fbbf24] bg-[#1e1a08] border border-[#fbbf24]/40',
    locQuery:        'text-[9px] font-mono rounded-none px-1.5 py-0.5 leading-none text-[#4a9eff] bg-[#0a1e36] border border-[#4a9eff]/40',
    locHeader:       'text-[9px] font-mono rounded-none px-1.5 py-0.5 leading-none text-[#c084fc] bg-[#1a0830] border border-[#c084fc]/40',
    locCookie:       'text-[9px] font-mono rounded-none px-1.5 py-0.5 leading-none text-[#4ade80] bg-[#0a1e10] border border-[#4ade80]/40',
    locForm:         'text-[9px] font-mono rounded-none px-1.5 py-0.5 leading-none text-[#4a9eff] bg-[#0a1e36] border border-[#4a9eff]/40',
    locDefault:      'text-[9px] font-mono rounded-none px-1.5 py-0.5 leading-none text-[#3a6080] bg-[#061020] border border-[#1e3a5f]',
    typeBadge:       'text-[9px] font-mono text-[#c084fc] bg-[#1a0830] border border-[#c084fc]/40 rounded-none px-1.5 py-0.5 leading-none',
    requiredBadge:   'text-[9px] font-mono font-bold text-[#f87171] bg-[#200a10] border border-[#f87171]/40 rounded-none px-1.5 py-0.5 leading-none',
    deprecatedBadge: 'text-[9px] font-mono font-bold text-[#fbbf24] bg-[#1e1a08] border border-[#fbbf24]/40 rounded-none px-1.5 py-0.5 leading-none',
    constraintBadge: 'text-[9px] font-mono text-[#1e3a5f] bg-[#061020] border border-[#1e3a5f] rounded-none px-1.5 py-0.5 leading-none',
    tooltipIcon:     'w-3.5 h-3.5 text-[#1e3a5f] cursor-help hover:text-[#4a9eff] transition-colors',
    tooltipPopup:    'pointer-events-none absolute bottom-full right-0 mb-2 w-56 rounded-none bg-[#040d18] border border-[#1e3a5f] px-2.5 py-2 text-[10px] font-mono text-[#7db8e8] leading-snug shadow-lg shadow-black/50 opacity-0 group-hover/tip:opacity-100 transition-opacity z-50',
  },

  responsePanel: {
    loadingState:  'shrink-0 border-t border-[#1e3a5f] h-16 flex items-center justify-center gap-2 text-xs font-mono text-[#1e3a5f] bg-[#040d18]',
    emptyState:    'shrink-0 border-t border-[#1e3a5f] h-10 flex items-center justify-center',
    emptyText:     'text-[10px] font-mono text-[#1e3a5f]',
    container:     'h-full border-t border-[#1e3a5f] flex flex-col',
    tabBar:        'flex items-center gap-2 px-4 py-2 border-b border-[#1e3a5f] bg-[#040d18] shrink-0',
    tab:           { base: 'px-2.5 py-1 text-[10px] font-mono rounded-none font-medium transition-colors text-[#1e3a5f] hover:text-[#7db8e8] uppercase tracking-wide', active: 'bg-[#0a1e36] text-[#4a9eff] border border-[#1e3a5f]' },
    tabDivider:    'w-px h-3 bg-[#1e3a5f] mx-1',
    headerCount:   'ml-0.5 font-mono text-[#1e3a5f]',
    copyButton:    { base: 'flex items-center gap-1 text-[10px] font-mono px-2 py-1 rounded-none hover:bg-[#0a1e36] transition-colors text-[#1e3a5f] hover:text-[#7db8e8] border border-transparent hover:border-[#1e3a5f]', copied: 'text-[#4ade80]' },
    statusNeutral: 'text-[10px] font-mono border rounded-none px-1.5 py-0.5 font-bold text-[#3a6080] bg-[#061020] border-[#1e3a5f]',
    statusSuccess: 'text-[10px] font-mono border rounded-none px-1.5 py-0.5 font-bold text-[#4ade80] bg-[#0a1e10] border-[#4ade80]/40',
    statusError:   'text-[10px] font-mono border rounded-none px-1.5 py-0.5 font-bold text-[#f87171] bg-[#200a10] border-[#f87171]/40',
    bodyContainer: 'flex-1 overflow-auto bg-[#040d18]',
    bodyPre:       'text-[11px] p-3 font-mono text-[#7db8e8] leading-relaxed',
    headersPre:    'text-[11px] p-3 font-mono text-[#3a6080] leading-relaxed',
  },

  sendBar: {
    container:          'px-5 py-3 border-b border-[#1e3a5f] shrink-0 bg-[#040d18]',
    urlBox:             'flex items-center gap-2 flex-1 min-w-0 bg-[#030a14] rounded-none px-2.5 py-2 border border-[#1e3a5f]',
    urlCode:            'text-[10px] font-mono text-[#3a6080] leading-tight flex-1 min-w-0 break-all',
    sendButtonActive:   'shrink-0 px-4 rounded-none text-xs font-mono font-bold transition-all bg-[#1e90ff] hover:bg-[#4a9eff] active:scale-[0.98] text-[#040d18] uppercase tracking-wide',
    sendButtonDisabled: 'shrink-0 px-4 rounded-none text-xs font-mono font-bold transition-all bg-[#0a1e36] text-[#1e3a5f] border border-[#1e3a5f] cursor-not-allowed uppercase tracking-wide',
  },

  inputScalar: {
    input:        'w-full text-xs font-mono border border-[#1e3a5f] rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] placeholder-[#1e3a5f] focus:outline-none focus:border-[#1e90ff] transition-colors',
    inputInvalid: 'w-full text-xs font-mono border border-[#f87171]/60 rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] placeholder-[#1e3a5f] focus:outline-none focus:border-[#f87171] transition-colors',
  },

  inputBoolean: {
    select:        'w-full text-xs font-mono border border-[#1e3a5f] rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] focus:outline-none focus:border-[#1e90ff] transition-colors',
    selectInvalid: 'w-full text-xs font-mono border border-[#f87171]/60 rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] focus:outline-none focus:border-[#f87171] transition-colors',
  },

  inputEnum: {
    select:        'w-full text-xs font-mono border border-[#1e3a5f] rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] focus:outline-none focus:border-[#1e90ff] transition-colors',
    selectInvalid: 'w-full text-xs font-mono border border-[#f87171]/60 rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] focus:outline-none focus:border-[#f87171] transition-colors',
  },

  inputFile: {
    input: 'block w-full text-xs font-mono text-[#3a6080] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-none file:border file:border-[#1e3a5f] file:text-xs file:font-mono file:font-medium file:bg-[#0a1e36] file:text-[#4a9eff] hover:file:bg-[#061020]',
  },

  inputArray: {
    rowInput:        'flex-1 text-xs font-mono border border-[#1e3a5f] rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] placeholder-[#1e3a5f] focus:outline-none focus:border-[#1e90ff] transition-colors',
    rowInputInvalid: 'flex-1 text-xs font-mono border border-[#f87171]/60 rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] placeholder-[#1e3a5f] focus:outline-none focus:border-[#f87171] transition-colors',
    rowIndex:        'text-[9px] font-mono text-[#1e3a5f] w-4 text-right shrink-0',
    removeButton:    'shrink-0 w-5 h-5 flex items-center justify-center rounded-none text-[#1e3a5f] hover:text-[#f87171] hover:bg-[#200a10] disabled:opacity-0 transition-colors',
    addButton:       'flex items-center gap-1 text-[10px] font-mono text-[#4a9eff] hover:text-[#7db8e8] transition-colors',
    hint:            'text-[9px] font-mono text-[#1e3a5f]',
  },

  inputMultiSelect: {
    trigger:        'w-full text-xs font-mono border border-[#1e3a5f] rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] focus:outline-none focus:border-[#1e90ff] transition-colors flex items-center justify-between text-left',
    triggerInvalid: 'w-full text-xs font-mono border border-[#f87171]/60 rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] focus:outline-none focus:border-[#f87171] transition-colors flex items-center justify-between text-left',
    placeholder:    'font-mono text-[#1e3a5f]',
    dropdown:       'absolute z-20 mt-1 w-full rounded-none border border-[#1e3a5f] bg-[#040d18] shadow-lg shadow-black/50 py-1',
    dropdownItem:   'flex items-center gap-2 px-3 py-1.5 hover:bg-[#0a1e36] cursor-pointer',
    optionText:     'text-xs font-mono text-[#7db8e8]',
  },

  inputObject: {
    textarea:        'w-full text-xs font-mono border border-[#1e3a5f] rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] placeholder-[#1e3a5f] focus:outline-none focus:border-[#1e90ff] transition-colors resize-y',
    textareaInvalid: 'w-full text-xs font-mono border border-[#f87171]/60 rounded-none px-3 py-2 bg-[#040d18] text-[#7db8e8] placeholder-[#1e3a5f] focus:outline-none focus:border-[#f87171] transition-colors resize-y',
  },

  detailPane: {
    spinner:      'w-5 h-5 animate-spin text-[#1e90ff]',
    errorIcon:    'w-10 h-10 rounded-none border border-[#f87171]/40 bg-[#200a10] flex items-center justify-center shrink-0 text-[#f87171]',
    errorMessage: 'text-sm font-mono text-[#f87171]',
    retryLink:    'text-xs font-mono text-[#1e3a5f] hover:text-[#7db8e8] underline underline-offset-2',
    emptyIcon:    'w-10 h-10 rounded-none border border-[#1e3a5f] flex items-center justify-center text-[#1e3a5f]',
    emptyMessage: 'text-sm font-mono text-[#1e3a5f]',
  },

  verticalResizable: {
    handle: 'w-8 h-0.5 rounded-none bg-[#1e3a5f] group-hover:bg-[#1e90ff] transition-colors',
  },

  syntax: {
    key:     '#4a9eff',
    string:  '#4ade80',
    boolean: '#c084fc',
    null:    '#1e3a5f',
    number:  '#fbbf24',
  },

  paneHandle:  'border-l border-[#1e3a5f] group-hover:border-[#4a9eff] group-[.dragging]:border-[#7eb8f7] transition-colors duration-150',
  focusRing:   'focus:ring-1 focus:ring-[#1e90ff] focus:ring-offset-0',
  scrollbar:   { thumb: 'bg-[#1e3a5f]', thumbHover: 'bg-[#2a4a6f]' },
};