/**
 * Broadsheet theme preset — pure black & white editorial, single red accent.
 * Zero border-radius. Serif descriptions, bold grid dividers. Zine / printed API reference.
 * Palette: white (#FFFFFF), ink (#111111), muted (#777777), accent red (#E63946).
 */
import type { AppTheme } from '../contract';

const badge = 'method-badge shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] uppercase w-[36px] text-center';

export const broadsheetTheme: AppTheme = {
  name: 'broadsheet',
  fontFamily: "'Georgia', 'Times New Roman', ui-serif, serif",

  appRoot: {
    root:              'flex flex-col h-full overflow-hidden bg-white',
    navPane:           'shrink-0 bg-[#F7F7F7] overflow-y-auto flex flex-col',
    detailPane:        'flex-1 min-w-0 bg-white overflow-hidden',
    tryPane:           'shrink-0 bg-white overflow-hidden',
    shortcutsBackdrop: 'fixed inset-0 bg-black/50 flex items-center justify-center z-50',
    shortcutsPanel:    'bg-white w-72 mx-4 overflow-hidden border-2 border-[#111] shadow-[4px_4px_0_#111]',
    shortcutsHeader:   'flex items-center justify-between px-5 py-3.5 border-b-2 border-[#111]',
    shortcutsTitle:    'text-sm font-bold text-[#111] tracking-tight',
    shortcutsClose:    'text-[#777] hover:text-[#111] text-xl leading-none transition-colors',
    shortcutsRow:      'flex items-center justify-between py-1.5 border-b border-[#E5E5E5] last:border-0',
    shortcutsDesc:     'text-xs text-[#333]',
    shortcutsKbd:      'text-[10px] font-mono bg-[#F0F0F0] text-[#111] px-2 py-0.5 border border-[#CCC] shrink-0',
  },

  nav: {
    container:         'shrink-0 bg-[#F7F7F7] overflow-y-auto flex flex-col h-full',
    divider:           'mt-1 border-t-2 border-[#111]',
    searchWrapper:     'px-4 py-3 border-b-2 border-[#111] shrink-0',
    searchInput:       'w-full pl-7 pr-6 py-2 text-[11px] border-2 border-[#111] bg-white text-[#111] placeholder-[#999] focus:outline-none focus:ring-0 focus:border-[#E63946] transition-colors font-sans',
    searchIcon:        'absolute left-2.5 top-1/2 -translate-y-1/2 w-3 h-3 text-[#999] pointer-events-none',
    searchClearButton: 'absolute right-2 top-1/2 -translate-y-1/2 text-[#999] hover:text-[#111] leading-none text-sm',
    searchHint:        'absolute right-2 top-1/2 -translate-y-1/2 text-[9px] text-[#AAA] border border-[#CCC] px-1 font-mono pointer-events-none leading-none',
    loadingSpinner:    'w-5 h-5 animate-spin text-[#E63946]',
    tabBar:            'flex gap-0 px-4 py-2 border-b-2 border-[#111]',
    tab:               { base: 'px-2.5 py-1 text-[11px] font-bold transition-colors text-[#777] hover:text-[#111] tracking-tight uppercase', active: 'bg-[#111] text-white' },
    tagHeader:         'w-full flex items-center justify-between px-4 py-2.5 text-[10px] font-black uppercase tracking-widest text-[#111] hover:text-[#E63946] transition-colors border-b border-[#E5E5E5]',
    tagChevron:        'w-3 h-3 transition-transform',
    tagCount:          'text-[10px] text-[#777] font-mono',
    endpointItem:      { base: 'nav-endpoint w-full flex items-center gap-2.5 px-4 py-2 text-left transition-colors text-[#333] hover:bg-[#EFEFEF] hover:text-[#111] border-b border-[#E5E5E5]', active: 'bg-[#111] text-white border-b border-[#111]' },
    endpointPath:      'truncate text-[11px] font-mono',
    methodBadge:       { base: badge, get: 'bg-[#111] text-white', post: 'bg-[#E63946] text-white', put: 'bg-[#555] text-white', delete: 'bg-[#E63946] text-white', patch: 'bg-[#777] text-white', options: 'bg-[#999] text-white', head: 'bg-[#999] text-white' },
    schemaItem:        { base: 'w-full text-left gap-2.5 px-4 py-2 transition-colors hover:bg-[#EFEFEF] border-b border-[#E5E5E5]', active: 'bg-[#111]' },
    schemaName:        { base: 'truncate text-[11px] font-mono text-[#333]', active: 'text-white' },
    schemaTypeBadge:   'shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] bg-[#E5E5E5] text-[#111] uppercase',
    schemaDescription: 'mt-0.5 text-[10px] text-[#777] truncate pl-[38px]',
    emptyState:        'text-[11px] text-[#777]',
  },

  endpoint: {
    container:           'h-full flex flex-col',
    header:              'flex items-center gap-3 px-6 py-5 border-b-2 border-[#111] shrink-0 h-[50px]',
    methodBadge:         { base: badge, get: 'bg-[#111] text-white', post: 'bg-[#E63946] text-white', put: 'bg-[#555] text-white', delete: 'bg-[#E63946] text-white', patch: 'bg-[#777] text-white', options: 'bg-[#999] text-white', head: 'bg-[#999] text-white' },
    path:                'font-mono text-sm text-[#111]',
    summary:             'text-sm text-[#111] mb-2 font-bold',
    description:         'text-xs text-[#333] font-serif italic',
    deprecated:          'ml-auto text-[10px] bg-[#FFF3CD] text-[#7A5A00] border border-[#CCC] px-2 py-0.5 font-sans',
    paramSection:        'border-2 border-[#111] overflow-hidden',
    paramSectionTitle:   'text-xs font-black uppercase tracking-wider text-[#111] mb-4',
    paramLocTitle:       'text-[10px] font-black uppercase tracking-wider text-[#111] mb-3',
    paramRow:            'border-b border-[#E5E5E5] last:border-0 bg-white hover:bg-[#F7F7F7] transition-colors',
    paramName:           'font-mono text-[11px] text-[#111]',
    paramType:           'text-[10px] bg-[#EFEFEF] text-[#333] px-1.5 py-0.5 font-mono',
    paramRequired:       'text-[#E63946] text-[9px] font-black ml-1',
    paramDescription:    'px-4 py-3 w-full text-xs text-[#333] font-serif',
    mutedText:           'text-[#777]',
    responseAccordion:   'border-2 border-[#111] overflow-hidden divide-y divide-[#E5E5E5]',
    responseHeader:      'w-full flex items-center gap-3 px-4 py-3.5 hover:bg-[#F7F7F7] transition-colors text-left',
    responseStatusCode:  { base: 'text-xs font-mono font-black', success: 'text-[#1A5C1A]', redirect: 'text-[#1A3A8B]', clientError: 'text-[#7A5A00]', serverError: 'text-[#E63946]' },
    responseDescription: 'text-xs text-[#333] flex-1 font-serif',
    bodySection:         'px-3 py-1.5 bg-[#F0F0F0] border-b border-[#E5E5E5] flex items-center gap-2',
    bodyContentType:     'text-[10px] text-[#777] font-mono',
  },

  topBar: {
    container:              'relative flex items-center gap-4 px-6 h-16 border-b-2 border-[#111] bg-white shrink-0 z-10',
    specTitle:              'text-sm font-bold text-[#111] truncate tracking-tight',
    specVersion:            'text-[10px] text-[#777] border border-[#CCC] px-1.5 py-px font-mono shrink-0 leading-tight',
    specDescription:        'text-[10px] text-[#777] truncate leading-tight mt-px font-serif italic',
    noSpecIcon:             'w-7 h-7 bg-[#EFEFEF] flex items-center justify-center shrink-0',
    noSpecIconSvg:          'w-4 h-4 text-[#777]',
    noSpecTitle:            'text-sm font-bold text-[#777]',
    divider:                'w-px h-5 bg-[#CCC] mx-1 shrink-0',
    authButtonConfigured:   'flex items-center gap-1.5 text-xs px-2.5 py-1.5 font-bold border-2 transition-all shrink-0 text-[#1A5C1A] bg-[#E8F5E8] border-[#1A5C1A] hover:bg-[#D0ECD0]',
    authButtonUnconfigured: 'flex items-center gap-1.5 text-xs px-2.5 py-1.5 font-bold border-2 transition-all shrink-0 text-[#111] bg-white border-[#111] hover:bg-[#F0F0F0]',
    neutralButton:          'flex items-center gap-1.5 text-xs px-2.5 py-1.5 font-bold border-2 transition-all shrink-0 text-[#111] bg-white border-[#111] hover:bg-[#F0F0F0]',
    loadButton:             'flex items-center gap-1.5 text-xs text-white bg-[#E63946] hover:bg-[#C42D3A] active:bg-[#A81E29] px-3 py-1.5 font-bold transition-colors shrink-0',
  },

  themePicker: {
    dropdown: 'bg-white border-2 border-[#111] shadow-[4px_4px_0_#111] py-1.5 overflow-hidden',
    item:     { base: 'w-full flex items-center gap-3 px-3 py-2 text-left hover:bg-[#F0F0F0] transition-colors', active: 'bg-[#F0F0F0]' },
    name:     'text-sm text-[#111] font-bold flex-1',
    check:    'w-3.5 h-3.5 text-[#E63946] shrink-0',
  },

  modal: {
    backdrop:    'fixed inset-0 bg-black/50 flex items-center justify-center z-50',
    container:   'bg-white w-full mx-4 overflow-hidden border-2 border-[#111] shadow-[4px_4px_0_#111]',
    header:      'flex items-center justify-between px-5 py-4 border-b-2 border-[#111]',
    closeButton: 'text-[#777] hover:text-[#111] text-xl leading-none',
    footer:      'px-5 py-3 bg-[#F0F0F0] border-t-2 border-[#111]',
  },

  loadModal: {
    title:        'text-sm font-bold text-[#111]',
    footerText:   'text-[10px] text-[#777]',
    petstoreLink: 'text-xs text-[#1A3A8B] hover:underline',
    urlLabel:     'block text-xs font-bold text-[#111] mb-1.5',
    urlInput:     'flex-1 text-xs border-2 border-[#111] px-3 py-2 bg-white text-[#111] placeholder-[#999] focus:outline-none focus:border-[#E63946] transition-colors font-mono',
    dividerLine:  'flex-1 border-t border-[#CCC]',
    dividerText:  'text-[10px] text-[#777] uppercase tracking-wider',
    fileLabel:    'block text-xs font-bold text-[#111] mb-1.5',
    fileDropZone: 'flex items-center justify-center gap-2 border-2 border-dashed border-[#CCC] px-4 py-5 cursor-pointer hover:border-[#111] hover:bg-[#F7F7F7] transition-colors',
    fileDropIcon: 'w-4 h-4 text-[#777]',
    fileDropText: 'text-xs text-[#333]',
    errorBanner:  'text-xs text-[#E63946] bg-[#FEEAEB] border border-[#F5A0A6] px-3 py-2',
  },

  authModal: {
    tabBar:            'flex gap-0 px-4 py-2 bg-[#F0F0F0] border-b-2 border-[#111] overflow-x-auto',
    tabActive:         'px-3 py-1.5 text-[11px] font-bold bg-[#111] text-white flex items-center gap-1.5 shrink-0',
    tabInactive:       'px-3 py-1.5 text-[11px] font-bold text-[#777] hover:text-[#111] transition-colors flex items-center gap-1.5 shrink-0',
    titleIcon:         'w-4 h-4 text-[#333]',
    titleText:         'text-sm font-bold text-[#111]',
    closeButton:       'text-xs bg-[#111] hover:bg-[#333] text-white px-4 py-2 font-bold transition-colors',
    schemeType:        'text-[10px] text-[#777]',
    authorizedBadge:   'text-[9px] text-[#1A5C1A] bg-[#E8F5E8] border border-[#9EC09E] px-1.5 py-0.5 font-bold uppercase tracking-wide',
    schemeDescription: 'text-[10px] text-[#777] font-serif italic',
    fieldLabel:        'block text-[10px] font-bold text-[#111] mb-1',
    fieldLabelHint:    'text-[#777] font-sans',
    input:             'w-full text-xs border-2 border-[#111] px-3 py-2 bg-white text-[#111] placeholder-[#AAA] focus:outline-none focus:border-[#E63946] font-mono',
    tokenWrapper:      'flex items-stretch border-2 border-[#111] overflow-hidden bg-white focus-within:border-[#E63946] transition-all',
    tokenPrefix:       'px-2.5 flex items-center text-[10px] text-[#777] bg-[#F0F0F0] border-r-2 border-[#111] font-mono shrink-0 select-none',
    tokenField:        'flex-1 text-xs px-2.5 py-2 bg-white text-[#111] placeholder-[#AAA] focus:outline-none font-mono min-w-0',
    saveButton:        'text-xs bg-[#E63946] hover:bg-[#C42D3A] text-white px-3 py-1.5 font-bold transition-colors',
    clearButton:       'text-xs border-2 border-[#111] text-[#111] hover:bg-[#F0F0F0] px-3 py-1.5 font-bold transition-colors',
  },

  serverConfig: {
    chip: {
      base: 'flex items-center gap-1.5 text-[11px] font-mono px-2.5 py-1.5 border-2 transition-colors shrink-0 text-[#111] border-[#111] bg-white hover:bg-[#F0F0F0]',
      open: 'bg-[#111] text-white border-[#111] hover:bg-[#333] hover:border-[#333]',
    },
    chipIcon:            'w-3 h-3 shrink-0 text-[#777]',
    backdrop:            'fixed inset-0 bg-black/50 flex items-center justify-center z-[60]',
    popover:             'bg-white w-full max-w-sm mx-4 overflow-hidden border-2 border-[#111] shadow-[4px_4px_0_#111]',
    popoverHeader:       'flex items-center justify-between px-5 py-4 border-b-2 border-[#111]',
    headerIcon:          'w-4 h-4 text-[#333]',
    headerTitle:         'text-sm font-bold text-[#111]',
    closeButton:         'text-[#777] hover:text-[#111] text-xl leading-none',
    sectionDivider:      'px-5 py-4 border-b border-[#E5E5E5]',
    sectionLabel:        'block text-[10px] font-black uppercase tracking-wider text-[#111]',
    serverSelect:        'w-full text-[11px] font-mono border-2 border-[#111] px-3 py-2 bg-white text-[#111] focus:outline-none focus:border-[#E63946] cursor-pointer',
    variableName:        'text-[11px] font-mono font-bold text-[#111]',
    variableDescription: 'text-[10px] text-[#777] leading-tight mt-0.5 font-serif italic',
    variableInput:       'text-[11px] font-mono border-2 border-[#111] px-2.5 py-1.5 bg-white text-[#111] focus:outline-none focus:border-[#E63946] w-full',
    resolvedSection:     'px-5 py-4 bg-[#F0F0F0]',
    resolvedLabel:       'text-[10px] font-black uppercase tracking-wider text-[#777] mb-1.5',
    resolvedValue:       'text-[11px] font-mono text-[#111] break-all',
  },

  commandBar: {
    backdrop:       'fixed inset-0 bg-black/60 z-[60] flex items-start justify-center pt-[12vh]',
    container:      'bg-white w-full max-w-lg mx-4 flex flex-col overflow-hidden border-2 border-[#111] shadow-[4px_4px_0_#111] max-h-[70vh]',
    searchRow:      'flex items-center gap-3 px-4 py-3 border-b-2 border-[#111] shrink-0',
    searchIcon:     'w-4 h-4 text-[#777] shrink-0',
    input:          'flex-1 bg-transparent text-sm text-[#111] placeholder-[#999] outline-none',
    clearButton:    'text-[#777] hover:text-[#111] text-lg leading-none shrink-0 transition-colors',
    groupTitle:     'px-4 py-1.5 text-[10px] font-black uppercase tracking-widest text-[#777] select-none',
    resultItem:     { base: 'w-full flex items-center gap-3 px-4 py-2.5 text-left transition-colors hover:bg-[#F0F0F0] border-b border-[#F0F0F0]', active: 'bg-[#111] hover:bg-[#111]' },
    actionIcon:     { base: 'w-7 h-7 flex items-center justify-center shrink-0 bg-[#F0F0F0] text-[#333]', active: 'bg-[#E63946] text-white' },
    resultLabel:    'text-sm font-bold text-[#111] truncate',
    resultSubtitle: 'text-xs text-[#777] truncate mt-0.5',
    activeChevron:  'w-3.5 h-3.5 text-[#E63946] shrink-0',
    emptyIcon:      'w-8 h-8 text-[#CCC] mb-3',
    emptyText:      'text-sm text-[#777]',
    footer:         'shrink-0 flex items-center gap-4 px-4 py-2 border-t-2 border-[#111] bg-[#F0F0F0]',
    shortcutText:   'flex items-center gap-1 text-[11px] text-[#777]',
    shortcutBadge:  'font-mono text-[10px] bg-white border border-[#CCC] px-1 py-px',
    specTitle:      'ml-auto text-[11px] text-[#CCC] truncate',
    highlightMark:  'bg-[#FFF3CD] text-inherit not-italic',
  },

  schema: {
    tabBar:       'flex gap-0 px-3 py-2 bg-[#F0F0F0] border-b-2 border-[#111]',
    tabActive:    'px-3 py-1 text-[11px] font-bold bg-[#111] text-white',
    tabInactive:  'px-3 py-1 text-[11px] font-bold text-[#777] hover:text-[#111] transition-colors',
    description:  'px-4 pt-3 pb-0 text-[11px] text-[#333] leading-relaxed font-serif italic',
    exampleBlock: 'text-[11px] bg-[#F7F7F7] border border-[#E5E5E5] p-3 overflow-x-auto text-[#111] font-mono leading-relaxed',
  },

  schemaNode: {
    name:          'font-mono text-[11px] text-[#111]',
    typeBadge:     'text-[10px] px-1.5 py-0.5 font-mono',
    nullableBadge: 'text-[9px] bg-[#EFEFEF] text-[#777] px-1 font-mono',
    constraint:    'text-[9px] font-mono text-[#777]',
    enumValue:     'text-[9px] text-[#777] font-mono',
    description:   'text-[11px] text-[#333] mt-0.5 leading-relaxed font-serif italic',
    enumKey:       'font-mono text-[#111]',
    enumDesc:      'text-[#777]',
    nestedBorder:  'border-l-2 border-[#111] ml-3 pl-3 mt-0.5',
    typeBadgeColors: {
      string:  'bg-[#E8F5E8] text-[#1A5C1A]',
      integer: 'bg-[#E8EEF8] text-[#1A3A8B]',
      number:  'bg-[#E8EEF8] text-[#1A3A8B]',
      boolean: 'bg-[#F0E8F8] text-[#5A1A8B]',
      object:  'bg-[#F7F7F7] text-[#111]',
      array:   'bg-[#E8F7F5] text-[#1A5C58]',
      default: 'bg-[#EFEFEF] text-[#333]',
    },
  },

  schemaDetail: {
    header:      'flex items-center gap-3 px-6 py-5 border-b-2 border-[#111] shrink-0',
    typeBadge:   'text-[9px] font-bold font-mono px-[5px] py-[2px] uppercase',
    schemaName:  'font-mono text-sm text-[#111]',
    description: 'text-sm text-[#333] mb-6 leading-relaxed font-serif italic',
    sectionLabel:'text-xs font-black uppercase tracking-wider text-[#111] mb-4',
    schemaBox:   'border-2 border-[#111] overflow-hidden bg-white',
    typeBadgeColors: {
      string:  'bg-[#E8F5E8] text-[#1A5C1A]',
      integer: 'bg-[#E8EEF8] text-[#1A3A8B]',
      number:  'bg-[#E8EEF8] text-[#1A3A8B]',
      boolean: 'bg-[#F0E8F8] text-[#5A1A8B]',
      object:  'bg-[#F7F7F7] text-[#111]',
      array:   'bg-[#E8F7F5] text-[#1A5C58]',
      default: 'bg-[#EFEFEF] text-[#333]',
    },
  },

  playground: {
    container:           'h-full flex flex-col bg-white',
    header:              'flex items-center gap-2 px-5 border-b-2 border-[#111] shrink-0 h-[50px]',
    headerTitle:         'text-xs font-bold text-[#111] uppercase tracking-wide',
    emptyState:          'h-full flex flex-col items-center justify-center text-center px-6 gap-3 bg-white',
    emptyIconWrapper:    'w-10 h-10 bg-[#F0F0F0] flex items-center justify-center',
    emptyIcon:           'w-5 h-5 text-[#777]',
    emptyText:           'text-sm text-[#777] font-serif italic',
    inputLabel:          'text-[10px] font-black uppercase tracking-wider text-[#111] mb-3',
    textInput:           'w-full text-xs border-2 border-[#111] px-3 py-2 bg-white text-[#111] placeholder-[#AAA] focus:outline-none focus:border-[#E63946] transition-colors font-mono',
    selectInput:         'w-full text-xs border-2 border-[#111] px-3 py-2 bg-white text-[#111] focus:outline-none focus:border-[#E63946] cursor-pointer transition-colors',
    fileInput:           'block w-full text-xs text-[#333] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:border-0 file:text-xs file:font-bold file:bg-[#EFEFEF] file:text-[#111] hover:file:bg-[#E5E5E5]',
    fileInputButton:     { base: 'file:py-1.5 file:px-3 file:border-0 file:text-xs file:font-bold file:bg-[#EFEFEF] file:text-[#111] hover:file:bg-[#E5E5E5]', hasFile: 'file:bg-[#E5E5E5]' },
    bodyEditor:          'w-full text-[11px] border-2 border-[#111] px-3 py-2.5 bg-white text-[#111] placeholder-[#AAA] focus:outline-none focus:border-[#E63946] font-mono resize-y transition-colors leading-relaxed',
    contentTypeSelector: 'text-[10px] font-mono text-[#777] border border-[#CCC] px-2 py-0.5 bg-[#F0F0F0]',
    sendButton:          { base: 'shrink-0 px-4 text-xs font-bold transition-all bg-[#E63946] hover:bg-[#C42D3A] active:scale-[0.98] text-white', loading: 'bg-[#F0F0F0] text-[#777] cursor-not-allowed', disabled: 'bg-[#F0F0F0] text-[#777] cursor-not-allowed' },
    responsePanel:       'h-full border-t-2 border-[#111] flex flex-col',
    responseStatus:      { base: 'text-[10px] px-1.5 py-0.5 font-mono font-bold border bg-[#F0F0F0] text-[#333] border-[#CCC]', success: 'bg-[#E8F5E8] text-[#1A5C1A] border-[#9EC09E]', redirect: 'bg-[#E8EEF8] text-[#1A3A8B] border-[#9EB4D8]', clientError: 'bg-[#FFF3CD] text-[#7A5A00] border-[#DDB870]', serverError: 'bg-[#FEEAEB] text-[#C01020] border-[#F5A0A6]' },
    responseTime:        'text-[10px] text-[#777] font-mono border border-[#CCC] px-1.5 py-0.5',
    responseSize:        'text-[10px] text-[#777] font-mono',
    responseTabs:        'flex items-center gap-0 px-4 py-2 border-b border-[#E5E5E5] bg-[#F7F7F7] shrink-0',
    responseTab:         { base: 'px-2.5 py-1 text-[10px] font-bold transition-colors text-[#777] hover:text-[#111] uppercase tracking-wide', active: 'bg-white text-[#111] border border-[#CCC]' },
    responseBody:        'flex-1 overflow-auto bg-white',
    responseEmpty:       'shrink-0 border-t border-[#E5E5E5] h-10 flex items-center justify-center text-[10px] text-[#CCC]',
    errorBanner:         'mx-5 mb-4 px-3 py-2 bg-[#FEEAEB] border border-[#F5A0A6] text-xs text-[#C01020]',
  },

  authStatus: {
    sectionLabel:      'text-[10px] font-black uppercase tracking-wider text-[#111] mb-3',
    emptyText:         'text-[10px] text-[#777] font-serif italic',
    schemeRow:         'flex items-center justify-between py-2.5 px-3 border border-[#E5E5E5] bg-[#F7F7F7]',
    schemeName:        'text-[11px] font-mono text-[#111]',
    schemeType:        'ml-1.5 text-[10px] text-[#777]',
    authorizedBadge:   'text-[9px] text-[#1A5C1A] bg-[#E8F5E8] border border-[#9EC09E] px-1.5 py-0.5 font-bold uppercase tracking-wide',
    unauthorizedBadge: 'text-[9px] text-[#777] bg-[#F0F0F0] border border-[#CCC] px-1.5 py-0.5 uppercase tracking-wide',
  },

  bodyEditor: {
    fileInput:    'block w-full text-xs text-[#333] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:border-0 file:text-xs file:font-bold file:bg-[#EFEFEF] file:text-[#111] hover:file:bg-[#E5E5E5]',
    formatButton: 'absolute top-1.5 right-1.5 z-10 text-[10px] text-[#777] hover:text-[#E63946] transition-colors px-1.5 py-0.5 hover:bg-[#F7F7F7]',
    textarea:     'w-full text-[11px] border-2 border-[#111] px-3 py-2.5 bg-white text-[#111] placeholder-[#AAA] focus:outline-none focus:border-[#E63946] font-mono resize-y transition-colors leading-relaxed',
  },

  paramLabel: {
    nameText:        'font-mono text-[11px] text-[#111]',
    nameDeprecated:  'font-mono text-[11px] line-through text-[#AAA]',
    locPath:         'text-[9px] font-mono px-1.5 py-0.5 leading-none text-[#111] bg-[#E5E5E5]',
    locQuery:        'text-[9px] font-mono px-1.5 py-0.5 leading-none text-[#111] bg-[#E5E5E5]',
    locHeader:       'text-[9px] font-mono px-1.5 py-0.5 leading-none text-[#111] bg-[#E5E5E5]',
    locCookie:       'text-[9px] font-mono px-1.5 py-0.5 leading-none text-[#111] bg-[#E5E5E5]',
    locForm:         'text-[9px] font-mono px-1.5 py-0.5 leading-none text-[#111] bg-[#E5E5E5]',
    locDefault:      'text-[9px] font-mono px-1.5 py-0.5 leading-none text-[#111] bg-[#E5E5E5]',
    typeBadge:       'text-[9px] font-mono text-[#111] bg-[#EFEFEF] px-1.5 py-0.5 leading-none',
    requiredBadge:   'text-[9px] font-bold text-[#E63946] bg-[#FEEAEB] px-1.5 py-0.5 leading-none',
    deprecatedBadge: 'text-[9px] font-bold text-[#7A5A00] bg-[#FFF3CD] px-1.5 py-0.5 leading-none',
    constraintBadge: 'text-[9px] font-mono text-[#333] bg-[#EFEFEF] px-1.5 py-0.5 leading-none',
    tooltipIcon:     'w-3.5 h-3.5 text-[#777] cursor-help hover:text-[#111] transition-colors',
    tooltipPopup:    'pointer-events-none absolute bottom-full right-0 mb-2 w-56 bg-[#111] px-2.5 py-2 text-[10px] text-white leading-snug shadow-lg opacity-0 group-hover/tip:opacity-100 transition-opacity z-50',
  },

  responsePanel: {
    loadingState:  'shrink-0 border-t-2 border-[#111] h-16 flex items-center justify-center gap-2 text-xs text-[#777] bg-[#F7F7F7]',
    emptyState:    'shrink-0 border-t-2 border-[#111] h-10 flex items-center justify-center',
    emptyText:     'text-[10px] text-[#CCC]',
    container:     'h-full border-t-2 border-[#111] flex flex-col',
    tabBar:        'flex items-center gap-0 px-4 py-2 border-b border-[#E5E5E5] bg-[#F7F7F7] shrink-0',
    tab:           { base: 'px-2.5 py-1 text-[10px] font-bold transition-colors text-[#777] hover:text-[#111] uppercase', active: 'bg-white text-[#111] border border-[#CCC]' },
    tabDivider:    'w-px h-3 bg-[#CCC] mx-1',
    headerCount:   'ml-0.5 text-[#CCC]',
    copyButton:    { base: 'flex items-center gap-1 text-[10px] px-2 py-1 hover:bg-[#F0F0F0] transition-colors text-[#777] hover:text-[#111]', copied: 'text-[#1A5C1A]' },
    statusNeutral: 'text-[10px] border px-1.5 py-0.5 font-mono font-bold text-[#333] bg-[#F0F0F0] border-[#CCC]',
    statusSuccess: 'text-[10px] border px-1.5 py-0.5 font-mono font-bold text-[#1A5C1A] bg-[#E8F5E8] border-[#9EC09E]',
    statusError:   'text-[10px] border px-1.5 py-0.5 font-mono font-bold text-[#C01020] bg-[#FEEAEB] border-[#F5A0A6]',
    bodyContainer: 'flex-1 overflow-auto bg-white',
    bodyPre:       'text-[11px] p-3 text-[#111] font-mono leading-relaxed',
    headersPre:    'text-[11px] p-3 text-[#333] font-mono leading-relaxed',
  },

  sendBar: {
    container:          'px-5 py-3 border-b-2 border-[#111] shrink-0 bg-[#F7F7F7]',
    urlBox:             'flex items-center gap-2 flex-1 min-w-0 bg-white px-2.5 py-2 border-2 border-[#111]',
    urlCode:            'text-[10px] text-[#333] leading-tight flex-1 min-w-0 break-all',
    sendButtonActive:   'shrink-0 px-4 text-xs font-bold transition-all bg-[#E63946] hover:bg-[#C42D3A] active:scale-[0.98] text-white',
    sendButtonDisabled: 'shrink-0 px-4 text-xs font-bold transition-all bg-[#F0F0F0] text-[#AAA] cursor-not-allowed',
  },

  inputScalar: {
    input:        'w-full text-xs border-2 border-[#111] px-3 py-2 bg-white text-[#111] placeholder-[#AAA] focus:outline-none focus:border-[#E63946] transition-colors font-mono',
    inputInvalid: 'w-full text-xs border-2 border-[#E63946] px-3 py-2 bg-white text-[#111] placeholder-[#AAA] focus:outline-none focus:border-[#C42D3A] transition-colors font-mono',
  },

  inputBoolean: {
    select:        'w-full text-xs border-2 border-[#111] px-3 py-2 bg-white text-[#111] focus:outline-none focus:border-[#E63946] transition-colors font-mono',
    selectInvalid: 'w-full text-xs border-2 border-[#E63946] px-3 py-2 bg-white text-[#111] focus:outline-none focus:border-[#C42D3A] transition-colors font-mono',
  },

  inputEnum: {
    select:        'w-full text-xs border-2 border-[#111] px-3 py-2 bg-white text-[#111] focus:outline-none focus:border-[#E63946] transition-colors font-mono',
    selectInvalid: 'w-full text-xs border-2 border-[#E63946] px-3 py-2 bg-white text-[#111] focus:outline-none focus:border-[#C42D3A] transition-colors font-mono',
  },

  inputFile: {
    input: 'block w-full text-xs text-[#333] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:border-0 file:text-xs file:font-bold file:bg-[#EFEFEF] file:text-[#111] hover:file:bg-[#E5E5E5]',
  },

  inputArray: {
    rowInput:        'flex-1 text-xs border-2 border-[#111] px-3 py-2 bg-white text-[#111] placeholder-[#AAA] focus:outline-none focus:border-[#E63946] transition-colors font-mono',
    rowInputInvalid: 'flex-1 text-xs border-2 border-[#E63946] px-3 py-2 bg-white text-[#111] placeholder-[#AAA] focus:outline-none transition-colors font-mono',
    rowIndex:        'text-[9px] text-[#CCC] font-mono w-4 text-right shrink-0',
    removeButton:    'shrink-0 w-5 h-5 flex items-center justify-center text-[#CCC] hover:text-[#E63946] hover:bg-[#FEEAEB] disabled:opacity-0 transition-colors',
    addButton:       'flex items-center gap-1 text-[10px] text-[#E63946] hover:text-[#C42D3A] transition-colors font-bold',
    hint:            'text-[9px] text-[#CCC] font-mono',
  },

  inputMultiSelect: {
    trigger:        'w-full text-xs border-2 border-[#111] px-3 py-2 bg-white text-[#111] focus:outline-none focus:border-[#E63946] transition-colors font-mono flex items-center justify-between text-left',
    triggerInvalid: 'w-full text-xs border-2 border-[#E63946] px-3 py-2 bg-white text-[#111] focus:outline-none transition-colors font-mono flex items-center justify-between text-left',
    placeholder:    'text-[#AAA]',
    dropdown:       'absolute z-20 mt-1 w-full border-2 border-[#111] bg-white shadow-[4px_4px_0_#111] py-1',
    dropdownItem:   'flex items-center gap-2 px-3 py-1.5 hover:bg-[#F0F0F0] cursor-pointer',
    optionText:     'text-xs font-mono text-[#111]',
  },

  inputObject: {
    textarea:        'w-full text-xs border-2 border-[#111] px-3 py-2 bg-white text-[#111] placeholder-[#AAA] focus:outline-none focus:border-[#E63946] transition-colors font-mono resize-y',
    textareaInvalid: 'w-full text-xs border-2 border-[#E63946] px-3 py-2 bg-white text-[#111] placeholder-[#AAA] focus:outline-none transition-colors font-mono resize-y',
  },

  detailPane: {
    spinner:      'w-5 h-5 animate-spin text-[#E63946]',
    errorIcon:    'w-10 h-10 bg-[#FEEAEB] flex items-center justify-center shrink-0 text-[#C01020]',
    errorMessage: 'text-sm text-[#C01020] font-serif',
    retryLink:    'text-xs text-[#777] hover:text-[#111] underline underline-offset-2',
    emptyIcon:    'w-10 h-10 bg-[#F0F0F0] flex items-center justify-center text-[#777]',
    emptyMessage: 'text-sm text-[#777] font-serif italic',
  },

  verticalResizable: {
    handle: 'w-8 h-0.5 bg-[#CCC] group-hover:bg-[#E63946] transition-colors',
  },

  syntax: {
    key:     '#1A3A8B',
    string:  '#1A5C1A',
    boolean: '#5A1A8B',
    null:    '#777777',
    number:  '#7A5A00',
  },

  paneHandle:  'bg-[#E5E5E5] group-hover:bg-[#E63946] group-hover:w-0.5 group-[.dragging]:bg-[#C42D3A] group-[.dragging]:w-0.5',
  focusRing:   'focus:ring-2 focus:ring-[#E63946] focus:ring-offset-1',
  scrollbar:   { thumb: 'bg-[#CCCCCC]', thumbHover: 'bg-[#AAAAAA]' },
};