/**
 * Catppuccin Mocha theme preset — warm lavender-purple dark theme based on the Catppuccin Mocha palette.
 * Base (#1E1E2E–#45475A) for backgrounds, #CDD6F4 for text,
 * Mauve (#CBA6F7) for interactive accents, semantic Aurora-equivalent colors throughout.
 */
import type { AppTheme } from '../contract';

const methodBadgeBase = 'method-badge shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] rounded uppercase w-[36px] text-center';

export const catppuccinTheme: AppTheme = {
  name: 'catppuccin',

  appRoot: {
    root:              'flex flex-col h-full overflow-hidden bg-[#1E1E2E]',
    navPane:           'shrink-0 bg-[#313244] overflow-y-auto flex flex-col',
    detailPane:        'flex-1 min-w-0 bg-[#1E1E2E] overflow-hidden',
    tryPane:           'shrink-0 bg-[#1E1E2E] overflow-hidden',
    shortcutsBackdrop: 'fixed inset-0 bg-black/60 flex items-center justify-center z-50',
    shortcutsPanel:    'bg-[#313244] rounded-xl shadow-xl w-72 mx-4 overflow-hidden',
    shortcutsHeader:   'flex items-center justify-between px-5 py-3.5 border-b border-[#45475A]',
    shortcutsTitle:    'text-sm font-semibold text-[#CDD6F4]',
    shortcutsClose:    'text-[#6C7086] hover:text-[#CDD6F4] text-xl leading-none transition-colors',
    shortcutsRow:      'flex items-center justify-between py-1.5 border-b border-[#45475A]/40 last:border-0',
    shortcutsDesc:     'text-xs text-[#BAC2DE]',
    shortcutsKbd:      'text-[10px] font-mono bg-[#45475A] text-[#CBA6F7] px-2 py-0.5 rounded border border-[#585B70] shrink-0',
  },

  nav: {
    container:         'shrink-0 bg-[#313244] overflow-y-auto flex flex-col h-full',
    divider:           'mt-1 border-t border-[#45475A]',
    searchWrapper:     'px-4 py-3 border-b border-[#45475A] shrink-0',
    searchInput:       'w-full pl-7 pr-6 py-2 text-[11px] border border-[#45475A] rounded-md bg-[#1E1E2E] text-[#CDD6F4] placeholder-[#6C7086] focus:outline-none focus:ring-1 focus:ring-[#CBA6F7] focus:border-[#CBA6F7] transition-colors',
    searchIcon:        'absolute left-2.5 top-1/2 -translate-y-1/2 w-3 h-3 text-[#6C7086] pointer-events-none',
    searchClearButton: 'absolute right-2 top-1/2 -translate-y-1/2 text-[#6C7086] hover:text-[#CDD6F4] leading-none text-sm',
    searchHint:        'absolute right-2 top-1/2 -translate-y-1/2 text-[9px] text-[#6C7086] border border-[#45475A] rounded px-1 font-mono pointer-events-none leading-none',
    loadingSpinner:    'w-5 h-5 animate-spin text-[#CBA6F7]',
    tabBar:            'flex gap-1 px-4 py-2 border-b border-[#45475A]',
    tab:               { base: 'px-2.5 py-1 text-[11px] font-medium rounded transition-colors text-[#6C7086] hover:text-[#CDD6F4]', active: 'bg-[#45475A] text-[#CDD6F4] border border-[#585B70] shadow-sm' },
    tagHeader:         'w-full flex items-center justify-between px-4 py-2.5 text-[10px] font-semibold uppercase tracking-widest text-[#6C7086] hover:text-[#CBA6F7] transition-colors',
    tagChevron:        'w-3 h-3 transition-transform',
    tagCount:          'text-[10px] text-[#6C7086] font-mono',
    endpointItem:      { base: 'nav-endpoint w-full flex items-center gap-2.5 px-4 py-2 text-left transition-colors text-[#A6ADC8] hover:bg-[#45475A]/50 hover:text-[#CDD6F4]', active: 'bg-[#45475A] text-[#CDD6F4]' },
    endpointPath:      'truncate text-[11px] font-mono',
    methodBadge:       { base: methodBadgeBase, get: 'bg-[#89B4FA]/20 text-[#89B4FA]', post: 'bg-[#A6E3A1]/20 text-[#A6E3A1]', put: 'bg-[#FAB387]/20 text-[#FAB387]', delete: 'bg-[#F38BA8]/20 text-[#F38BA8]', patch: 'bg-[#CBA6F7]/20 text-[#CBA6F7]', options: 'bg-[#45475A] text-[#7F849C]', head: 'bg-[#45475A] text-[#7F849C]' },
    schemaItem:        { base: 'w-full text-left gap-2.5 px-4 py-2 transition-colors hover:bg-[#45475A]/50', active: 'bg-[#45475A]' },
    schemaName:        { base: 'truncate text-[11px] font-mono text-[#A6ADC8]', active: 'text-[#CDD6F4]' },
    schemaTypeBadge:   'shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] rounded bg-[#CBA6F7]/20 text-[#CBA6F7] uppercase',
    schemaDescription: 'mt-0.5 text-[10px] text-[#6C7086] truncate pl-[38px]',
    emptyState:        'text-[11px] text-[#6C7086]',
  },

  endpoint: {
    container:           'h-full flex flex-col',
    header:              'flex items-center gap-3 px-6 py-5 border-b border-[#45475A] shrink-0 h-[50px]',
    methodBadge:         { base: methodBadgeBase, get: 'bg-[#89B4FA]/20 text-[#89B4FA]', post: 'bg-[#A6E3A1]/20 text-[#A6E3A1]', put: 'bg-[#FAB387]/20 text-[#FAB387]', delete: 'bg-[#F38BA8]/20 text-[#F38BA8]', patch: 'bg-[#CBA6F7]/20 text-[#CBA6F7]', options: 'bg-[#45475A] text-[#7F849C]', head: 'bg-[#45475A] text-[#7F849C]' },
    path:                'font-mono text-sm text-[#CDD6F4]',
    summary:             'text-sm text-[#CDD6F4] mb-2 font-medium',
    description:         'text-xs text-[#A6ADC8]',
    deprecated:          'ml-auto text-[10px] bg-[#F9E2AF]/15 text-[#F9E2AF] border border-[#F9E2AF]/30 rounded px-2 py-0.5',
    paramSection:        'border border-[#45475A] rounded-lg overflow-hidden',
    paramSectionTitle:   'text-xs font-semibold uppercase tracking-wider text-[#6C7086] mb-4',
    paramLocTitle:       'text-[10px] font-semibold uppercase tracking-wider text-[#6C7086] mb-3',
    paramRow:            'border-b border-[#45475A] last:border-0 bg-[#313244]/50 hover:bg-[#45475A]/40 transition-colors',
    paramName:           'font-mono text-[11px] text-[#CDD6F4]',
    paramType:           'text-[10px] bg-[#45475A] text-[#A6ADC8] rounded px-1.5 py-0.5 font-mono',
    paramRequired:       'text-[#F38BA8] text-[9px] font-semibold ml-1',
    paramDescription:    'px-4 py-3 w-full text-xs text-[#A6ADC8]',
    mutedText:           'text-[#6C7086]',
    responseAccordion:   'border border-[#45475A] rounded-lg overflow-hidden divide-y divide-[#45475A]',
    responseHeader:      'w-full flex items-center gap-3 px-4 py-3.5 hover:bg-[#45475A]/40 transition-colors text-left',
    responseStatusCode:  { base: 'text-xs font-mono font-semibold', success: 'text-[#A6E3A1]', redirect: 'text-[#89B4FA]', clientError: 'text-[#F9E2AF]', serverError: 'text-[#F38BA8]' },
    responseDescription: 'text-xs text-[#A6ADC8] flex-1',
    bodySection:         'px-3 py-1.5 bg-[#313244] border-b border-[#45475A] flex items-center gap-2',
    bodyContentType:     'text-[10px] text-[#6C7086] font-mono',
  },

  topBar: {
    container:              'relative flex items-center gap-4 px-6 h-16 border-b border-[#45475A] bg-[#1E1E2E] shrink-0 z-10',
    specTitle:              'text-sm font-semibold text-[#CDD6F4] truncate',
    specVersion:            'text-[10px] text-[#6C7086] border border-[#45475A] rounded-full px-1.5 py-px font-mono shrink-0 leading-tight',
    specDescription:        'text-[10px] text-[#6C7086] truncate leading-tight mt-px',
    noSpecIcon:             'w-7 h-7 rounded-lg bg-gradient-to-br from-[#313244] to-[#45475A] flex items-center justify-center shrink-0',
    noSpecIconSvg:          'w-4 h-4 text-[#6C7086]',
    noSpecTitle:            'text-sm font-semibold text-[#6C7086]',
    divider:                'w-px h-5 bg-[#45475A] mx-1 shrink-0',
    authButtonConfigured:   'flex items-center gap-1.5 text-xs rounded-md px-2.5 py-1.5 font-medium border transition-all shrink-0 text-[#A6E3A1] bg-[#A6E3A1]/10 border-[#A6E3A1]/30 hover:bg-[#A6E3A1]/20',
    authButtonUnconfigured: 'flex items-center gap-1.5 text-xs rounded-md px-2.5 py-1.5 font-medium border transition-all shrink-0 text-[#A6ADC8] bg-[#313244] border-[#45475A] hover:bg-[#45475A] hover:border-[#CBA6F7]',
    neutralButton:          'flex items-center gap-1.5 text-xs rounded-md px-2.5 py-1.5 font-medium border transition-all shrink-0 text-[#A6ADC8] bg-[#313244] border-[#45475A] hover:bg-[#45475A] hover:border-[#CBA6F7]',
    loadButton:             'flex items-center gap-1.5 text-xs text-[#1E1E2E] bg-[#CBA6F7] hover:bg-[#B4BEFE] active:bg-[#B4BEFE] rounded-md px-3 py-1.5 font-semibold transition-colors shrink-0 shadow-sm',
  },

  themePicker: {
    dropdown: 'bg-[#313244] border border-[#45475A] rounded-xl shadow-xl py-1.5 overflow-hidden',
    item:     { base: 'w-full flex items-center gap-3 px-3 py-2 text-left hover:bg-[#45475A]/50 transition-colors', active: 'bg-[#45475A]' },
    name:     'text-sm text-[#CDD6F4] font-medium flex-1',
    check:    'w-3.5 h-3.5 text-[#CBA6F7] shrink-0',
  },

  modal: {
    backdrop:    'fixed inset-0 bg-black/60 flex items-center justify-center z-50',
    container:   'bg-[#313244] rounded-xl shadow-xl w-full mx-4 overflow-hidden',
    header:      'flex items-center justify-between px-5 py-4 border-b border-[#45475A]',
    closeButton: 'text-[#6C7086] hover:text-[#CDD6F4] text-xl leading-none',
    footer:      'px-5 py-3 bg-[#45475A]/30 border-t border-[#45475A]',
  },

  loadModal: {
    title:        'text-sm font-semibold text-[#CDD6F4]',
    footerText:   'text-[10px] text-[#6C7086]',
    petstoreLink: 'text-xs text-[#89B4FA] hover:underline',
    urlLabel:     'block text-xs font-medium text-[#A6ADC8] mb-1.5',
    urlInput:     'flex-1 text-xs border border-[#45475A] rounded-md px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] placeholder-[#6C7086] focus:outline-none focus:ring-1 focus:ring-[#CBA6F7] focus:border-[#CBA6F7] transition-colors',
    dividerLine:  'flex-1 border-t border-[#45475A]',
    dividerText:  'text-[10px] text-[#6C7086] uppercase tracking-wider',
    fileLabel:    'block text-xs font-medium text-[#A6ADC8] mb-1.5',
    fileDropZone: 'flex items-center justify-center gap-2 border-2 border-dashed border-[#45475A] rounded-lg px-4 py-5 cursor-pointer hover:border-[#CBA6F7] hover:bg-[#CBA6F7]/5 transition-colors',
    fileDropIcon: 'w-4 h-4 text-[#6C7086]',
    fileDropText: 'text-xs text-[#A6ADC8]',
    errorBanner:  'text-xs text-[#F38BA8] bg-[#F38BA8]/10 border border-[#F38BA8]/30 rounded-md px-3 py-2',
  },

  authModal: {
    tabBar:            'flex gap-1 px-4 py-2 bg-[#313244]/80 border-b border-[#45475A] overflow-x-auto',
    tabActive:         'px-3 py-1.5 text-[11px] font-medium rounded-md bg-[#45475A] text-[#CDD6F4] border border-[#585B70] flex items-center gap-1.5 shrink-0',
    tabInactive:       'px-3 py-1.5 text-[11px] font-medium rounded-md text-[#6C7086] hover:text-[#CDD6F4] transition-colors flex items-center gap-1.5 shrink-0',
    titleIcon:         'w-4 h-4 text-[#A6ADC8]',
    titleText:         'text-sm font-semibold text-[#CDD6F4]',
    closeButton:       'text-xs bg-[#CDD6F4] hover:bg-[#BAC2DE] text-[#1E1E2E] px-4 py-2 rounded-md font-medium transition-colors',
    schemeType:        'text-[10px] text-[#6C7086]',
    authorizedBadge:   'text-[9px] text-[#A6E3A1] bg-[#A6E3A1]/10 border border-[#A6E3A1]/30 rounded px-1.5 py-0.5 font-semibold uppercase tracking-wide',
    schemeDescription: 'text-[10px] text-[#6C7086]',
    fieldLabel:        'block text-[10px] text-[#A6ADC8] mb-1',
    fieldLabelHint:    'text-[#6C7086] font-sans',
    input:             'w-full text-xs border border-[#45475A] rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] placeholder-[#6C7086] focus:outline-none focus:ring-1 focus:ring-[#CBA6F7] focus:border-[#CBA6F7] font-mono',
    tokenWrapper:      'flex items-stretch border border-[#45475A] rounded-lg overflow-hidden bg-[#1E1E2E] focus-within:ring-1 focus-within:ring-[#CBA6F7] focus-within:border-[#CBA6F7] transition-all',
    tokenPrefix:       'px-2.5 flex items-center text-[10px] text-[#6C7086] bg-[#313244] border-r border-[#45475A] font-mono shrink-0 select-none',
    tokenField:        'flex-1 text-xs px-2.5 py-2 bg-[#1E1E2E] text-[#CDD6F4] placeholder-[#6C7086] focus:outline-none font-mono min-w-0',
    saveButton:        'text-xs bg-[#CBA6F7] hover:bg-[#B4BEFE] text-[#1E1E2E] px-3 py-1.5 rounded-md font-semibold transition-colors',
    clearButton:       'text-xs border border-[#45475A] text-[#A6ADC8] hover:border-[#CBA6F7] hover:text-[#CDD6F4] px-3 py-1.5 rounded-md font-medium transition-colors',
  },

  serverConfig: {
    chip: {
      base: 'flex items-center gap-1.5 text-[11px] font-mono px-2.5 py-1.5 rounded-lg border transition-colors shrink-0 text-[#A6ADC8] border-[#45475A] bg-[#313244] hover:bg-[#45475A] hover:border-[#CBA6F7]',
      open: 'bg-[#CBA6F7]/15 text-[#CBA6F7] border-[#CBA6F7]/40 hover:bg-[#CBA6F7]/15 hover:border-[#CBA6F7]/40',
    },
    chipIcon:            'w-3 h-3 shrink-0 text-[#6C7086]',
    backdrop:            'fixed inset-0 bg-black/60 flex items-center justify-center z-[60]',
    popover:             'bg-[#313244] rounded-xl shadow-xl w-full max-w-sm mx-4 overflow-hidden',
    popoverHeader:       'flex items-center justify-between px-5 py-4 border-b border-[#45475A]',
    headerIcon:          'w-4 h-4 text-[#A6ADC8]',
    headerTitle:         'text-sm font-semibold text-[#CDD6F4]',
    closeButton:         'text-[#6C7086] hover:text-[#CDD6F4] text-xl leading-none',
    sectionDivider:      'px-5 py-4 border-b border-[#45475A]',
    sectionLabel:        'block text-[10px] font-semibold uppercase tracking-wider text-[#6C7086]',
    serverSelect:        'w-full text-[11px] font-mono border border-[#45475A] rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] focus:outline-none focus:ring-1 focus:ring-[#CBA6F7] cursor-pointer',
    variableName:        'text-[11px] font-mono font-medium text-[#CDD6F4]',
    variableDescription: 'text-[10px] text-[#6C7086] leading-tight mt-0.5',
    variableInput:       'text-[11px] font-mono border border-[#45475A] rounded-lg px-2.5 py-1.5 bg-[#1E1E2E] text-[#CDD6F4] focus:outline-none focus:ring-1 focus:ring-[#CBA6F7] w-full',
    resolvedSection:     'px-5 py-4 bg-[#45475A]/30',
    resolvedLabel:       'text-[10px] font-semibold uppercase tracking-wider text-[#6C7086] mb-1.5',
    resolvedValue:       'text-[11px] font-mono text-[#CBA6F7] break-all',
  },

  commandBar: {
    backdrop:       'fixed inset-0 bg-black/70 z-[60] flex items-start justify-center pt-[12vh]',
    container:      'bg-[#1E1E2E] rounded-xl shadow-2xl w-full max-w-lg mx-4 flex flex-col overflow-hidden border border-[#45475A] max-h-[70vh]',
    searchRow:      'flex items-center gap-3 px-4 py-3 border-b border-[#313244] shrink-0',
    searchIcon:     'w-4 h-4 text-[#6C7086] shrink-0',
    input:          'flex-1 bg-transparent text-sm text-[#CDD6F4] placeholder-[#6C7086] outline-none',
    clearButton:    'text-[#6C7086] hover:text-[#CDD6F4] text-lg leading-none shrink-0 transition-colors',
    groupTitle:     'px-4 py-1.5 text-[10px] font-semibold uppercase tracking-widest text-[#6C7086] select-none',
    resultItem:     { base: 'w-full flex items-center gap-3 px-4 py-2.5 text-left transition-colors hover:bg-[#313244]/80', active: 'bg-[#CBA6F7]/10 hover:bg-[#CBA6F7]/10' },
    actionIcon:     { base: 'w-7 h-7 rounded-md flex items-center justify-center shrink-0 bg-[#313244] text-[#6C7086]', active: 'bg-[#CBA6F7]/20 text-[#CBA6F7]' },
    resultLabel:    'text-sm font-medium text-[#CDD6F4] truncate',
    resultSubtitle: 'text-xs text-[#6C7086] truncate mt-0.5',
    activeChevron:  'w-3.5 h-3.5 text-[#CBA6F7] shrink-0',
    emptyIcon:      'w-8 h-8 text-[#6C7086] mb-3',
    emptyText:      'text-sm text-[#6C7086]',
    footer:         'shrink-0 flex items-center gap-4 px-4 py-2 border-t border-[#313244] bg-[#313244]/50',
    shortcutText:   'flex items-center gap-1 text-[11px] text-[#6C7086]',
    shortcutBadge:  'font-mono text-[10px] bg-[#45475A] border border-[#585B70] rounded px-1 py-px',
    specTitle:      'ml-auto text-[11px] text-[#6C7086] truncate',
    highlightMark:  'bg-[#F9E2AF]/20 text-inherit not-italic rounded-sm',
  },

  schema: {
    tabBar:       'flex gap-1 px-3 py-2 bg-[#313244]/80 border-b border-[#45475A]',
    tabActive:    'px-3 py-1 text-[11px] font-medium rounded-md bg-[#45475A] text-[#CDD6F4] border border-[#585B70]',
    tabInactive:  'px-3 py-1 text-[11px] font-medium rounded-md text-[#6C7086] hover:text-[#CDD6F4] transition-colors',
    description:  'px-4 pt-3 pb-0 text-[11px] text-[#A6ADC8] leading-relaxed',
    exampleBlock: 'text-[11px] bg-[#1E1E2E] rounded-md p-3 overflow-x-auto text-[#CDD6F4] font-mono leading-relaxed',
  },

  schemaNode: {
    name:          'font-mono text-[11px] text-[#CDD6F4]',
    typeBadge:     'text-[10px] rounded px-1.5 py-0.5 font-mono',
    nullableBadge: 'text-[9px] bg-[#45475A] text-[#A6ADC8] rounded px-1 font-mono',
    constraint:    'text-[9px] font-mono text-[#6C7086]',
    enumValue:     'text-[9px] text-[#6C7086] font-mono',
    description:   'text-[11px] text-[#A6ADC8] mt-0.5 leading-relaxed',
    enumKey:       'font-mono text-[#BAC2DE]',
    enumDesc:      'text-[#6C7086]',
    nestedBorder:  'border-l-2 border-[#45475A] ml-3 pl-3 mt-0.5',
    typeBadgeColors: {
      string:  'bg-[#A6E3A1]/20 text-[#A6E3A1]',
      integer: 'bg-[#89B4FA]/20 text-[#89B4FA]',
      number:  'bg-[#89B4FA]/20 text-[#89B4FA]',
      boolean: 'bg-[#CBA6F7]/20 text-[#CBA6F7]',
      object:  'bg-[#FAB387]/20 text-[#FAB387]',
      array:   'bg-[#89DCEB]/20 text-[#89DCEB]',
      default: 'bg-[#45475A] text-[#7F849C]',
    },
  },

  schemaDetail: {
    header:      'flex items-center gap-3 px-6 py-5 border-b border-[#45475A] shrink-0',
    typeBadge:   'text-[9px] font-bold font-mono px-[5px] py-[2px] rounded uppercase',
    schemaName:  'font-mono text-sm text-[#CDD6F4]',
    description: 'text-sm text-[#A6ADC8] mb-6 leading-relaxed',
    sectionLabel:'text-xs font-semibold uppercase tracking-wider text-[#6C7086] mb-4',
    schemaBox:   'border border-[#45475A] rounded-lg overflow-hidden bg-[#313244]/50',
    typeBadgeColors: {
      string:  'bg-[#A6E3A1]/20 text-[#A6E3A1]',
      integer: 'bg-[#89B4FA]/20 text-[#89B4FA]',
      number:  'bg-[#89B4FA]/20 text-[#89B4FA]',
      boolean: 'bg-[#CBA6F7]/20 text-[#CBA6F7]',
      object:  'bg-[#FAB387]/20 text-[#FAB387]',
      array:   'bg-[#89DCEB]/20 text-[#89DCEB]',
      default: 'bg-[#45475A] text-[#7F849C]',
    },
  },

  playground: {
    container:           'h-full flex flex-col bg-[#1E1E2E]',
    header:              'flex items-center gap-2 px-5 border-b border-[#45475A] shrink-0 h-[50px]',
    headerTitle:         'text-xs font-semibold text-[#A6ADC8]',
    emptyState:          'h-full flex flex-col items-center justify-center text-center px-6 gap-3 bg-[#1E1E2E]',
    emptyIconWrapper:    'w-10 h-10 rounded-full bg-[#313244] flex items-center justify-center',
    emptyIcon:           'w-5 h-5 text-[#6C7086]',
    emptyText:           'text-sm text-[#6C7086]',
    inputLabel:          'text-[10px] font-semibold uppercase tracking-wider text-[#6C7086] mb-3',
    textInput:           'w-full text-xs border border-[#45475A] rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] placeholder-[#6C7086] focus:outline-none focus:ring-1 focus:ring-[#CBA6F7] focus:border-[#CBA6F7] transition-colors font-mono',
    selectInput:         'w-full text-xs border border-[#45475A] rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] focus:outline-none focus:ring-1 focus:ring-[#CBA6F7] cursor-pointer transition-colors',
    fileInput:           'block w-full text-xs text-[#A6ADC8] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-[#CBA6F7]/20 file:text-[#CBA6F7] hover:file:bg-[#CBA6F7]/30',
    fileInputButton:     { base: 'file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-[#CBA6F7]/20 file:text-[#CBA6F7] hover:file:bg-[#CBA6F7]/30', hasFile: 'file:bg-[#CBA6F7]/30' },
    bodyEditor:          'w-full text-[11px] border border-[#45475A] rounded-lg px-3 py-2.5 bg-[#313244] text-[#CDD6F4] placeholder-[#6C7086] focus:outline-none focus:ring-1 focus:ring-[#CBA6F7] focus:border-[#CBA6F7] font-mono resize-y transition-colors leading-relaxed',
    contentTypeSelector: 'text-[10px] font-mono text-[#6C7086] border border-[#45475A] rounded px-2 py-0.5 bg-[#313244]',
    sendButton:          { base: 'shrink-0 px-4 rounded-lg text-xs font-semibold transition-all bg-[#CBA6F7] hover:bg-[#B4BEFE] active:scale-[0.98] text-[#1E1E2E] shadow-sm', loading: 'bg-[#45475A] text-[#6C7086] cursor-not-allowed shadow-none', disabled: 'bg-[#45475A] text-[#6C7086] cursor-not-allowed shadow-none' },
    responsePanel:       'h-full border-t border-[#45475A] flex flex-col',
    responseStatus:      { base: 'text-[10px] rounded px-1.5 py-0.5 font-mono font-semibold border bg-[#313244] text-[#A6ADC8] border-[#45475A]', success: 'bg-[#A6E3A1]/15 text-[#A6E3A1] border-[#A6E3A1]/30', redirect: 'bg-[#89B4FA]/15 text-[#89B4FA] border-[#89B4FA]/30', clientError: 'bg-[#F9E2AF]/15 text-[#F9E2AF] border-[#F9E2AF]/30', serverError: 'bg-[#F38BA8]/15 text-[#F38BA8] border-[#F38BA8]/30' },
    responseTime:        'text-[10px] text-[#6C7086] font-mono border border-[#45475A] rounded px-1.5 py-0.5',
    responseSize:        'text-[10px] text-[#6C7086] font-mono',
    responseTabs:        'flex items-center gap-2 px-4 py-2 border-b border-[#45475A] bg-[#313244]/30 shrink-0',
    responseTab:         { base: 'px-2.5 py-1 text-[10px] rounded font-medium transition-colors text-[#6C7086] hover:text-[#CDD6F4]', active: 'bg-[#45475A] shadow-sm text-[#CDD6F4] border border-[#585B70]' },
    responseBody:        'flex-1 overflow-auto bg-[#1E1E2E]',
    responseEmpty:       'shrink-0 border-t border-[#45475A] h-10 flex items-center justify-center text-[10px] text-[#6C7086]',
    errorBanner:         'mx-5 mb-4 px-3 py-2 bg-[#F38BA8]/15 border border-[#F38BA8]/30 rounded-lg text-xs text-[#F38BA8]',
  },

  authStatus: {
    sectionLabel:      'text-[10px] font-semibold uppercase tracking-wider text-[#6C7086] mb-3',
    emptyText:         'text-[10px] text-[#6C7086]',
    schemeRow:         'flex items-center justify-between py-2.5 px-3 rounded-lg border border-[#45475A] bg-[#45475A]/30',
    schemeName:        'text-[11px] font-mono text-[#CDD6F4]',
    schemeType:        'ml-1.5 text-[10px] text-[#6C7086]',
    authorizedBadge:   'text-[9px] text-[#A6E3A1] bg-[#A6E3A1]/10 border border-[#A6E3A1]/30 rounded px-1.5 py-0.5 font-semibold uppercase tracking-wide',
    unauthorizedBadge: 'text-[9px] text-[#6C7086] bg-[#45475A] border border-[#45475A] rounded px-1.5 py-0.5 uppercase tracking-wide',
  },

  bodyEditor: {
    fileInput:    'block w-full text-xs text-[#A6ADC8] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-[#CBA6F7]/20 file:text-[#CBA6F7] hover:file:bg-[#CBA6F7]/30',
    formatButton: 'absolute top-1.5 right-1.5 z-10 text-[10px] text-[#6C7086] hover:text-[#CBA6F7] transition-colors px-1.5 py-0.5 rounded hover:bg-[#CBA6F7]/10',
    textarea:     'w-full text-[11px] border border-[#45475A] rounded-lg px-3 py-2.5 bg-[#313244] text-[#CDD6F4] placeholder-[#6C7086] focus:outline-none focus:ring-1 focus:ring-[#CBA6F7] focus:border-[#CBA6F7] font-mono resize-y transition-colors leading-relaxed',
  },

  paramLabel: {
    nameText:        'font-mono text-[11px] text-[#CDD6F4]',
    nameDeprecated:  'font-mono text-[11px] line-through text-[#6C7086]',
    locPath:         'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#FAB387] bg-[#FAB387]/15',
    locQuery:        'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#94E2D5] bg-[#94E2D5]/15',
    locHeader:       'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#B4BEFE] bg-[#B4BEFE]/15',
    locCookie:       'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#CBA6F7] bg-[#CBA6F7]/15',
    locForm:         'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#89B4FA] bg-[#89B4FA]/15',
    locDefault:      'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#A6ADC8] bg-[#45475A]',
    typeBadge:       'text-[9px] font-mono text-[#CBA6F7] bg-[#CBA6F7]/15 rounded px-1.5 py-0.5 leading-none',
    requiredBadge:   'text-[9px] font-semibold text-[#F38BA8] bg-[#F38BA8]/15 rounded px-1.5 py-0.5 leading-none',
    deprecatedBadge: 'text-[9px] font-semibold text-[#F9E2AF] bg-[#F9E2AF]/15 rounded px-1.5 py-0.5 leading-none',
    constraintBadge: 'text-[9px] font-mono text-[#6C7086] bg-[#45475A] rounded px-1.5 py-0.5 leading-none',
    tooltipIcon:     'w-3.5 h-3.5 text-[#6C7086] cursor-help hover:text-[#CDD6F4] transition-colors',
    tooltipPopup:    'pointer-events-none absolute bottom-full right-0 mb-2 w-56 rounded-lg bg-[#181825] border border-[#45475A] px-2.5 py-2 text-[10px] text-[#CDD6F4] leading-snug shadow-lg opacity-0 group-hover/tip:opacity-100 transition-opacity z-50',
  },

  responsePanel: {
    loadingState:  'shrink-0 border-t border-[#45475A] h-16 flex items-center justify-center gap-2 text-xs text-[#6C7086] bg-[#313244]/30',
    emptyState:    'shrink-0 border-t border-[#45475A] h-10 flex items-center justify-center',
    emptyText:     'text-[10px] text-[#6C7086]',
    container:     'h-full border-t border-[#45475A] flex flex-col',
    tabBar:        'flex items-center gap-2 px-4 py-2 border-b border-[#45475A] bg-[#313244]/30 shrink-0',
    tab:           { base: 'px-2.5 py-1 text-[10px] rounded font-medium transition-colors text-[#6C7086] hover:text-[#CDD6F4]', active: 'bg-[#45475A] shadow-sm text-[#CDD6F4] border border-[#585B70]' },
    tabDivider:    'w-px h-3 bg-[#45475A] mx-1',
    headerCount:   'ml-0.5 text-[#6C7086]',
    copyButton:    { base: 'flex items-center gap-1 text-[10px] px-2 py-1 rounded hover:bg-[#45475A] transition-colors text-[#6C7086] hover:text-[#CDD6F4]', copied: 'text-[#A6E3A1]' },
    statusNeutral: 'text-[10px] border rounded px-1.5 py-0.5 font-mono font-semibold text-[#A6ADC8] bg-[#313244] border-[#45475A]',
    statusSuccess: 'text-[10px] border rounded px-1.5 py-0.5 font-mono font-semibold text-[#A6E3A1] bg-[#A6E3A1]/15 border-[#A6E3A1]/30',
    statusError:   'text-[10px] border rounded px-1.5 py-0.5 font-mono font-semibold text-[#F38BA8] bg-[#F38BA8]/15 border-[#F38BA8]/30',
    bodyContainer: 'flex-1 overflow-auto bg-[#1E1E2E]',
    bodyPre:       'text-[11px] p-3 text-[#CDD6F4] font-mono leading-relaxed',
    headersPre:    'text-[11px] p-3 text-[#A6ADC8] font-mono leading-relaxed',
  },

  sendBar: {
    container:          'px-5 py-3 border-b border-[#45475A] shrink-0 bg-[#313244]/30',
    urlBox:             'flex items-center gap-2 flex-1 min-w-0 bg-[#313244] rounded-lg px-2.5 py-2 border border-[#45475A]',
    urlCode:            'text-[10px] text-[#A6ADC8] leading-tight flex-1 min-w-0 break-all',
    sendButtonActive:   'shrink-0 px-4 rounded-lg text-xs font-semibold transition-all bg-[#CBA6F7] hover:bg-[#B4BEFE] active:scale-[0.98] text-[#1E1E2E] shadow-sm',
    sendButtonDisabled: 'shrink-0 px-4 rounded-lg text-xs font-semibold transition-all bg-[#45475A] text-[#6C7086] cursor-not-allowed',
  },

  inputScalar: {
    input:        'w-full text-xs border border-[#45475A] rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] placeholder-[#6C7086] focus:outline-none focus:ring-1 focus:ring-[#CBA6F7] focus:border-[#CBA6F7] transition-colors font-mono',
    inputInvalid: 'w-full text-xs border border-[#F38BA8]/60 rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] placeholder-[#6C7086] focus:outline-none focus:ring-1 focus:ring-[#F38BA8]/60 focus:border-[#F38BA8]/60 transition-colors font-mono',
  },

  inputBoolean: {
    select:        'w-full text-xs border border-[#45475A] rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] focus:outline-none focus:ring-1 focus:ring-[#CBA6F7] focus:border-[#CBA6F7] transition-colors font-mono',
    selectInvalid: 'w-full text-xs border border-[#F38BA8]/60 rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] focus:outline-none focus:ring-1 focus:ring-[#F38BA8]/60 focus:border-[#F38BA8]/60 transition-colors font-mono',
  },

  inputEnum: {
    select:        'w-full text-xs border border-[#45475A] rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] focus:outline-none focus:ring-1 focus:ring-[#CBA6F7] focus:border-[#CBA6F7] transition-colors font-mono',
    selectInvalid: 'w-full text-xs border border-[#F38BA8]/60 rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] focus:outline-none focus:ring-1 focus:ring-[#F38BA8]/60 focus:border-[#F38BA8]/60 transition-colors font-mono',
  },

  inputFile: {
    input: 'block w-full text-xs text-[#A6ADC8] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-[#CBA6F7]/20 file:text-[#CBA6F7] hover:file:bg-[#CBA6F7]/30',
  },

  inputArray: {
    rowInput:        'flex-1 text-xs border border-[#45475A] rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] placeholder-[#6C7086] focus:outline-none focus:ring-1 focus:ring-[#CBA6F7] focus:border-[#CBA6F7] transition-colors font-mono',
    rowInputInvalid: 'flex-1 text-xs border border-[#F38BA8]/60 rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] placeholder-[#6C7086] focus:outline-none focus:ring-1 focus:ring-[#F38BA8]/60 focus:border-[#F38BA8]/60 transition-colors font-mono',
    rowIndex:        'text-[9px] text-[#6C7086] font-mono w-4 text-right shrink-0',
    removeButton:    'shrink-0 w-5 h-5 flex items-center justify-center rounded text-[#6C7086] hover:text-[#F38BA8] hover:bg-[#F38BA8]/15 disabled:opacity-0 transition-colors',
    addButton:       'flex items-center gap-1 text-[10px] text-[#CBA6F7] hover:text-[#B4BEFE] transition-colors',
    hint:            'text-[9px] text-[#6C7086] font-mono',
  },

  inputMultiSelect: {
    trigger:        'w-full text-xs border border-[#45475A] rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] focus:outline-none focus:ring-1 focus:ring-[#CBA6F7] focus:border-[#CBA6F7] transition-colors font-mono flex items-center justify-between text-left',
    triggerInvalid: 'w-full text-xs border border-[#F38BA8]/60 rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] focus:outline-none focus:ring-1 focus:ring-[#F38BA8]/60 focus:border-[#F38BA8]/60 transition-colors font-mono flex items-center justify-between text-left',
    placeholder:    'text-[#6C7086]',
    dropdown:       'absolute z-20 mt-1 w-full rounded-lg border border-[#45475A] bg-[#313244] shadow-lg py-1',
    dropdownItem:   'flex items-center gap-2 px-3 py-1.5 hover:bg-[#45475A]/60 cursor-pointer',
    optionText:     'text-xs font-mono text-[#CDD6F4]',
  },

  inputObject: {
    textarea:        'w-full text-xs border border-[#45475A] rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] placeholder-[#6C7086] focus:outline-none focus:ring-1 focus:ring-[#CBA6F7] focus:border-[#CBA6F7] transition-colors font-mono resize-y',
    textareaInvalid: 'w-full text-xs border border-[#F38BA8]/60 rounded-lg px-3 py-2 bg-[#1E1E2E] text-[#CDD6F4] placeholder-[#6C7086] focus:outline-none focus:ring-1 focus:ring-[#F38BA8]/60 focus:border-[#F38BA8]/60 transition-colors font-mono resize-y',
  },

  detailPane: {
    spinner:      'w-5 h-5 animate-spin text-[#CBA6F7]',
    errorIcon:    'w-10 h-10 rounded-full bg-[#F38BA8]/15 flex items-center justify-center shrink-0 text-[#F38BA8]',
    errorMessage: 'text-sm text-[#F38BA8]',
    retryLink:    'text-xs text-[#6C7086] hover:text-[#CDD6F4] underline underline-offset-2',
    emptyIcon:    'w-10 h-10 rounded-full bg-[#313244] flex items-center justify-center text-[#6C7086]',
    emptyMessage: 'text-sm text-[#6C7086]',
  },

  verticalResizable: {
    handle: 'w-8 h-0.5 rounded-full bg-[#45475A] group-hover:bg-[#CBA6F7] transition-colors',
  },

  syntax: {
    key:     '#89B4FA',
    string:  '#A6E3A1',
    boolean: '#CBA6F7',
    null:    '#6C7086',
    number:  '#F9E2AF',
  },

  paneHandle:  'bg-[#45475A] group-hover:bg-[#CBA6F7] group-hover:w-0.5 group-[.dragging]:bg-[#89B4FA] group-[.dragging]:w-0.5',
  fontFamily:  "'IBM Plex Sans', ui-sans-serif, system-ui, sans-serif",
  focusRing:   'focus:ring-2 focus:ring-[#CBA6F7] focus:ring-offset-1',
  scrollbar:   { thumb: 'bg-[#45475A]', thumbHover: 'bg-[#585B70]' },
};