/**
 * Dark theme preset.
 * All Tailwind class strings for the dark appearance live here.
 */
import type { AppTheme } from '../contract';

const methodBadgeBase = 'method-badge shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] rounded uppercase w-[36px] text-center';

export const darkTheme: AppTheme = {
  name: 'dark',

  appRoot: {
    root:              'flex flex-col h-full overflow-hidden bg-gray-900',
    navPane:           'shrink-0 bg-gray-800 overflow-y-auto flex flex-col',
    detailPane:        'flex-1 min-w-0 bg-gray-900 overflow-hidden',
    tryPane:           'shrink-0 bg-gray-900 overflow-hidden',
    shortcutsBackdrop: 'fixed inset-0 bg-black/50 flex items-center justify-center z-50',
    shortcutsPanel:    'bg-gray-800 rounded-xl shadow-xl w-72 mx-4 overflow-hidden',
    shortcutsHeader:   'flex items-center justify-between px-5 py-3.5 border-b border-gray-700',
    shortcutsTitle:    'text-sm font-semibold text-gray-200',
    shortcutsClose:    'text-gray-500 hover:text-gray-300 text-xl leading-none transition-colors',
    shortcutsRow:      'flex items-center justify-between py-1.5 border-b border-gray-700/50 last:border-0',
    shortcutsDesc:     'text-xs text-gray-300',
    shortcutsKbd:      'text-[10px] font-mono bg-gray-700 text-gray-400 px-2 py-0.5 rounded border border-gray-600 shrink-0',
  },

  nav: {
    container:         'shrink-0 bg-gray-800 overflow-y-auto flex flex-col h-full',
    divider:           'mt-1 border-t border-gray-700',
    searchWrapper:     'px-4 py-3 border-b border-gray-700 shrink-0',
    searchInput:       'w-full pl-7 pr-6 py-2 text-[11px] border border-gray-600 rounded-md bg-gray-700 text-gray-300 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 transition-colors',
    searchIcon:        'absolute left-2.5 top-1/2 -translate-y-1/2 w-3 h-3 text-gray-500 pointer-events-none',
    searchClearButton: 'absolute right-2 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-300 leading-none text-sm',
    searchHint:        'absolute right-2 top-1/2 -translate-y-1/2 text-[9px] text-gray-600 border border-gray-600 rounded px-1 font-mono pointer-events-none leading-none',
    loadingSpinner:    'w-5 h-5 animate-spin text-blue-500',
    tabBar:            'flex gap-1 px-4 py-2 border-b border-gray-700',
    tab:               { base: 'px-2.5 py-1 text-[11px] font-medium rounded transition-colors text-gray-500 hover:text-gray-300', active: 'bg-gray-700 text-gray-200 border border-gray-600 shadow-sm' },
    tagHeader:         'w-full flex items-center justify-between px-4 py-2.5 text-[10px] font-semibold uppercase tracking-widest text-gray-500 hover:text-gray-300 transition-colors',
    tagChevron:        'w-3 h-3 transition-transform',
    tagCount:          'text-[10px] text-gray-500 font-mono',
    endpointItem:      { base: 'nav-endpoint w-full flex items-center gap-2.5 px-4 py-2 text-left transition-colors text-gray-400 hover:bg-gray-700/50 hover:text-gray-200', active: 'bg-gray-700 text-gray-100' },
    endpointPath:      'truncate text-[11px] font-mono',
    methodBadge:       { base: methodBadgeBase, get: 'bg-blue-900/30 text-blue-400', post: 'bg-green-900/30 text-green-400', put: 'bg-amber-900/30 text-amber-400', delete: 'bg-red-900/30 text-red-400', patch: 'bg-pink-900/30 text-pink-400', options: 'bg-gray-700 text-gray-400', head: 'bg-gray-700 text-gray-400' },
    schemaItem:        { base: 'w-full text-left gap-2.5 px-4 py-2 transition-colors hover:bg-gray-700/50', active: 'bg-gray-700' },
    schemaName:        { base: 'truncate text-[11px] font-mono text-gray-300', active: 'text-gray-100' },
    schemaTypeBadge:   'shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] rounded bg-purple-900/30 text-purple-400 uppercase',
    schemaDescription: 'mt-0.5 text-[10px] text-gray-500 truncate pl-[38px]',
    emptyState:        'text-[11px] text-gray-500',
  },

  endpoint: {
    container:           'h-full flex flex-col',
    header:              'flex items-center gap-3 px-6 py-5 border-b border-gray-700 shrink-0 h-[50px]',
    methodBadge:         { base: methodBadgeBase, get: 'bg-blue-900/30 text-blue-400', post: 'bg-green-900/30 text-green-400', put: 'bg-amber-900/30 text-amber-400', delete: 'bg-red-900/30 text-red-400', patch: 'bg-pink-900/30 text-pink-400', options: 'bg-gray-700 text-gray-400', head: 'bg-gray-700 text-gray-400' },
    path:                'font-mono text-sm text-gray-200',
    summary:             'text-sm text-gray-200 mb-2 font-medium',
    description:         'text-xs text-gray-400',
    deprecated:          'ml-auto text-[10px] bg-amber-900/30 text-amber-400 border border-amber-700 rounded px-2 py-0.5',
    paramSection:        'border border-gray-700 rounded-lg overflow-hidden',
    paramSectionTitle:   'text-xs font-semibold uppercase tracking-wider text-gray-500 mb-4',
    paramLocTitle:       'text-[10px] font-semibold uppercase tracking-wider text-gray-500 mb-3',
    paramRow:            'border-b border-gray-700 last:border-0 bg-gray-800/50 hover:bg-gray-700/50 transition-colors',
    paramName:           'font-mono text-[11px] text-gray-200',
    paramType:           'text-[10px] bg-gray-700 text-gray-400 rounded px-1.5 py-0.5 font-mono',
    paramRequired:       'text-red-500 text-[9px] font-semibold ml-1',
    paramDescription:    'px-4 py-3 w-full text-xs text-gray-400',
    mutedText:           'text-gray-500',
    responseAccordion:   'border border-gray-700 rounded-lg overflow-hidden divide-y divide-gray-700',
    responseHeader:      'w-full flex items-center gap-3 px-4 py-3.5 hover:bg-gray-800/50 transition-colors text-left',
    responseStatusCode:  { base: 'text-xs font-mono font-semibold', success: 'text-green-400', redirect: 'text-blue-400', clientError: 'text-amber-400', serverError: 'text-red-400' },
    responseDescription: 'text-xs text-gray-400 flex-1',
    bodySection:         'px-3 py-1.5 bg-gray-800 border-b border-gray-700 flex items-center gap-2',
    bodyContentType:     'text-[10px] text-gray-400 font-mono',
  },

  topBar: {
    container:              'relative flex items-center gap-4 px-6 h-16 border-b border-gray-700 bg-gray-900 shrink-0 z-10',
    specTitle:              'text-sm font-semibold text-gray-100 truncate',
    specVersion:            'text-[10px] text-gray-500 border border-gray-600 rounded-full px-1.5 py-px font-mono shrink-0 leading-tight',
    specDescription:        'text-[10px] text-gray-500 truncate leading-tight mt-px',
    noSpecIcon:             'w-7 h-7 rounded-lg bg-gradient-to-br from-gray-700 to-gray-600 flex items-center justify-center shrink-0',
    noSpecIconSvg:          'w-4 h-4 text-gray-500',
    noSpecTitle:            'text-sm font-semibold text-gray-500',
    divider:                'w-px h-5 bg-gray-700 mx-1 shrink-0',
    authButtonConfigured:   'flex items-center gap-1.5 text-xs rounded-md px-2.5 py-1.5 font-medium border transition-all shrink-0 text-emerald-400 bg-emerald-900/30 border-emerald-700 hover:bg-emerald-900/50',
    authButtonUnconfigured: 'flex items-center gap-1.5 text-xs rounded-md px-2.5 py-1.5 font-medium border transition-all shrink-0 text-gray-400 bg-gray-800 border-gray-600 hover:bg-gray-700 hover:border-gray-500',
    neutralButton:          'flex items-center gap-1.5 text-xs rounded-md px-2.5 py-1.5 font-medium border transition-all shrink-0 text-gray-400 bg-gray-800 border-gray-600 hover:bg-gray-700 hover:border-gray-500',
    loadButton:             'flex items-center gap-1.5 text-xs text-white bg-blue-600 hover:bg-blue-700 active:bg-blue-800 rounded-md px-3 py-1.5 font-medium transition-colors shrink-0 shadow-sm',
  },

  themePicker: {
    dropdown: 'bg-gray-800 border border-gray-700 rounded-xl shadow-xl py-1.5 overflow-hidden',
    item:     { base: 'w-full flex items-center gap-3 px-3 py-2 text-left hover:bg-gray-700/50 transition-colors', active: 'bg-gray-700' },
    name:     'text-sm text-gray-200 font-medium flex-1',
    check:    'w-3.5 h-3.5 text-blue-400 shrink-0',
  },

  modal: {
    backdrop:    'fixed inset-0 bg-black/50 flex items-center justify-center z-50',
    container:   'bg-gray-800 rounded-xl shadow-xl w-full mx-4 overflow-hidden',
    header:      'flex items-center justify-between px-5 py-4 border-b border-gray-700',
    closeButton: 'text-gray-500 hover:text-gray-300 text-xl leading-none',
    footer:      'px-5 py-3 bg-gray-700/50 border-t border-gray-700',
  },

  loadModal: {
    title:        'text-sm font-semibold text-gray-200',
    footerText:   'text-[10px] text-gray-500',
    petstoreLink: 'text-xs text-blue-400 hover:underline',
    urlLabel:     'block text-xs font-medium text-gray-400 mb-1.5',
    urlInput:     'flex-1 text-xs border border-gray-600 rounded-md px-3 py-2 bg-gray-700 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 transition-colors',
    dividerLine:  'flex-1 border-t border-gray-700',
    dividerText:  'text-[10px] text-gray-500 uppercase tracking-wider',
    fileLabel:    'block text-xs font-medium text-gray-400 mb-1.5',
    fileDropZone: 'flex items-center justify-center gap-2 border-2 border-dashed border-gray-600 rounded-lg px-4 py-5 cursor-pointer hover:border-blue-500 hover:bg-blue-900/20 transition-colors',
    fileDropIcon: 'w-4 h-4 text-gray-500',
    fileDropText: 'text-xs text-gray-400',
    errorBanner:  'text-xs text-red-400 bg-red-900/30 border border-red-700 rounded-md px-3 py-2',
  },

  authModal: {
    tabBar:            'flex gap-1 px-4 py-2 bg-gray-800/80 border-b border-gray-700 overflow-x-auto',
    tabActive:         'px-3 py-1.5 text-[11px] font-medium rounded-md bg-gray-700 text-gray-200 border border-gray-600 flex items-center gap-1.5 shrink-0',
    tabInactive:       'px-3 py-1.5 text-[11px] font-medium rounded-md text-gray-500 hover:text-gray-300 transition-colors flex items-center gap-1.5 shrink-0',
    titleIcon:         'w-4 h-4 text-gray-400',
    titleText:         'text-sm font-semibold text-gray-200',
    closeButton:       'text-xs bg-gray-200 hover:bg-white text-gray-900 px-4 py-2 rounded-md font-medium transition-colors',
    schemeType:        'text-[10px] text-gray-500',
    authorizedBadge:   'text-[9px] text-green-400 bg-green-900/30 border border-green-700 rounded px-1.5 py-0.5 font-semibold uppercase tracking-wide',
    schemeDescription: 'text-[10px] text-gray-500',
    fieldLabel:        'block text-[10px] text-gray-400 mb-1',
    fieldLabelHint:    'text-gray-500 font-sans',
    input:             'w-full text-xs border border-gray-600 rounded-lg px-3 py-2 bg-gray-700 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 font-mono',
    tokenWrapper:      'flex items-stretch border border-gray-600 rounded-lg overflow-hidden bg-gray-700 focus-within:ring-1 focus-within:ring-blue-400 focus-within:border-blue-400 transition-all',
    tokenPrefix:       'px-2.5 flex items-center text-[10px] text-gray-500 bg-gray-600 border-r border-gray-600 font-mono shrink-0 select-none',
    tokenField:        'flex-1 text-xs px-2.5 py-2 bg-gray-700 text-gray-200 placeholder-gray-500 focus:outline-none font-mono min-w-0',
    saveButton:        'text-xs bg-blue-600 hover:bg-blue-700 text-white px-3 py-1.5 rounded-md font-medium transition-colors',
    clearButton:       'text-xs border border-gray-600 text-gray-400 hover:border-gray-500 hover:text-gray-200 px-3 py-1.5 rounded-md font-medium transition-colors',
  },

  serverConfig: {
    chip: {
      base: 'flex items-center gap-1.5 text-[11px] font-mono px-2.5 py-1.5 rounded-lg border transition-colors shrink-0 text-gray-400 border-gray-600 bg-gray-800 hover:bg-gray-700 hover:border-gray-500',
      open: 'bg-blue-900/30 text-blue-400 border-blue-700 hover:bg-blue-900/30 hover:border-blue-700',
    },
    chipIcon:            'w-3 h-3 shrink-0 text-gray-500',
    backdrop:            'fixed inset-0 bg-black/50 flex items-center justify-center z-[60]',
    popover:             'bg-gray-800 rounded-xl shadow-xl w-full max-w-sm mx-4 overflow-hidden',
    popoverHeader:       'flex items-center justify-between px-5 py-4 border-b border-gray-700',
    headerIcon:          'w-4 h-4 text-gray-400',
    headerTitle:         'text-sm font-semibold text-gray-200',
    closeButton:         'text-gray-500 hover:text-gray-300 text-xl leading-none',
    sectionDivider:      'px-5 py-4 border-b border-gray-700',
    sectionLabel:        'block text-[10px] font-semibold uppercase tracking-wider text-gray-500',
    serverSelect:        'w-full text-[11px] font-mono border border-gray-600 rounded-lg px-3 py-2 bg-gray-700 text-gray-300 focus:outline-none focus:ring-1 focus:ring-blue-400 cursor-pointer',
    variableName:        'text-[11px] font-mono font-medium text-gray-300',
    variableDescription: 'text-[10px] text-gray-500 leading-tight mt-0.5',
    variableInput:       'text-[11px] font-mono border border-gray-600 rounded-lg px-2.5 py-1.5 bg-gray-700 text-gray-300 focus:outline-none focus:ring-1 focus:ring-blue-400 w-full',
    resolvedSection:     'px-5 py-4 bg-gray-700/50',
    resolvedLabel:       'text-[10px] font-semibold uppercase tracking-wider text-gray-500 mb-1.5',
    resolvedValue:       'text-[11px] font-mono text-gray-300 break-all',
  },

  commandBar: {
    backdrop:       'fixed inset-0 bg-black/60 z-[60] flex items-start justify-center pt-[12vh]',
    container:      'bg-gray-900 rounded-xl shadow-2xl w-full max-w-lg mx-4 flex flex-col overflow-hidden border border-gray-700 max-h-[70vh]',
    searchRow:      'flex items-center gap-3 px-4 py-3 border-b border-gray-800 shrink-0',
    searchIcon:     'w-4 h-4 text-gray-500 shrink-0',
    input:          'flex-1 bg-transparent text-sm text-gray-200 placeholder-gray-500 outline-none',
    clearButton:    'text-gray-500 hover:text-gray-300 text-lg leading-none shrink-0 transition-colors',
    groupTitle:     'px-4 py-1.5 text-[10px] font-semibold uppercase tracking-widest text-gray-500 select-none',
    resultItem:     { base: 'w-full flex items-center gap-3 px-4 py-2.5 text-left transition-colors hover:bg-gray-800/60', active: 'bg-blue-900/30 hover:bg-blue-900/30' },
    actionIcon:     { base: 'w-7 h-7 rounded-md flex items-center justify-center shrink-0 bg-gray-800 text-gray-400', active: 'bg-blue-800/50 text-blue-400' },
    resultLabel:    'text-sm font-medium text-gray-200 truncate',
    resultSubtitle: 'text-xs text-gray-500 truncate mt-0.5',
    activeChevron:  'w-3.5 h-3.5 text-blue-500 shrink-0',
    emptyIcon:      'w-8 h-8 text-gray-600 mb-3',
    emptyText:      'text-sm text-gray-500',
    footer:         'shrink-0 flex items-center gap-4 px-4 py-2 border-t border-gray-800 bg-gray-800/50',
    shortcutText:   'flex items-center gap-1 text-[11px] text-gray-500',
    shortcutBadge:  'font-mono text-[10px] bg-gray-700 border border-gray-600 rounded px-1 py-px',
    specTitle:      'ml-auto text-[11px] text-gray-600 truncate',
    highlightMark:  'bg-yellow-900/50 text-inherit not-italic rounded-sm',
  },

  schema: {
    tabBar:       'flex gap-1 px-3 py-2 bg-gray-800/80 border-b border-gray-700',
    tabActive:    'px-3 py-1 text-[11px] font-medium rounded-md bg-gray-700 text-gray-200 border border-gray-600',
    tabInactive:  'px-3 py-1 text-[11px] font-medium rounded-md text-gray-500 hover:text-gray-300 transition-colors',
    description:  'px-4 pt-3 pb-0 text-[11px] text-gray-400 leading-relaxed',
    exampleBlock: 'text-[11px] bg-gray-900 rounded-md p-3 overflow-x-auto text-gray-300 font-mono leading-relaxed',
  },

  schemaNode: {
    name:          'font-mono text-[11px] text-gray-200',
    typeBadge:     'text-[10px] rounded px-1.5 py-0.5 font-mono',
    nullableBadge: 'text-[9px] bg-gray-700 text-gray-400 rounded px-1 font-mono',
    constraint:    'text-[9px] font-mono text-gray-500',
    enumValue:     'text-[9px] text-gray-500 font-mono',
    description:   'text-[11px] text-gray-400 mt-0.5 leading-relaxed',
    enumKey:       'font-mono text-gray-300',
    enumDesc:      'text-gray-500',
    nestedBorder:  'border-l-2 border-gray-700 ml-3 pl-3 mt-0.5',
    typeBadgeColors: {
      string:  'bg-emerald-900/30 text-emerald-400',
      integer: 'bg-blue-900/30 text-blue-400',
      number:  'bg-blue-900/30 text-blue-400',
      boolean: 'bg-purple-900/30 text-purple-400',
      object:  'bg-amber-900/30 text-amber-400',
      array:   'bg-cyan-900/30 text-cyan-400',
      default: 'bg-gray-700 text-gray-400',
    },
  },

  schemaDetail: {
    header:      'flex items-center gap-3 px-6 py-5 border-b border-gray-700 shrink-0',
    typeBadge:   'text-[9px] font-bold font-mono px-[5px] py-[2px] rounded uppercase',
    schemaName:  'font-mono text-sm text-gray-200',
    description: 'text-sm text-gray-400 mb-6 leading-relaxed',
    sectionLabel:'text-xs font-semibold uppercase tracking-wider text-gray-500 mb-4',
    schemaBox:   'border border-gray-700 rounded-lg overflow-hidden bg-gray-800/50',
    typeBadgeColors: {
      string:  'bg-emerald-900/30 text-emerald-400',
      integer: 'bg-blue-900/30 text-blue-400',
      number:  'bg-blue-900/30 text-blue-400',
      boolean: 'bg-purple-900/30 text-purple-400',
      object:  'bg-amber-900/30 text-amber-400',
      array:   'bg-cyan-900/30 text-cyan-400',
      default: 'bg-gray-700 text-gray-400',
    },
  },

  playground: {
    container:           'h-full flex flex-col bg-gray-900',
    header:              'flex items-center gap-2 px-5 border-b border-gray-700 shrink-0 h-[50px]',
    headerTitle:         'text-xs font-semibold text-gray-300',
    emptyState:          'h-full flex flex-col items-center justify-center text-center px-6 gap-3 bg-gray-900',
    emptyIconWrapper:    'w-10 h-10 rounded-full bg-gray-700 flex items-center justify-center',
    emptyIcon:           'w-5 h-5 text-gray-500',
    emptyText:           'text-sm text-gray-500',
    inputLabel:          'text-[10px] font-semibold uppercase tracking-wider text-gray-500 mb-3',
    textInput:           'w-full text-xs border border-gray-600 rounded-lg px-3 py-2 bg-gray-700 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 transition-colors font-mono',
    selectInput:         'w-full text-xs border border-gray-600 rounded-lg px-3 py-2 bg-gray-700 text-gray-300 focus:outline-none focus:ring-1 focus:ring-blue-400 cursor-pointer transition-colors',
    fileInput:           'block w-full text-xs text-gray-400 cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-blue-900/40 file:text-blue-400 hover:file:bg-blue-900/60',
    fileInputButton:     { base: 'file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-blue-900/40 file:text-blue-400 hover:file:bg-blue-900/60', hasFile: 'file:bg-blue-900/60' },
    bodyEditor:          'w-full text-[11px] border border-gray-600 rounded-lg px-3 py-2.5 bg-gray-800 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 font-mono resize-y transition-colors leading-relaxed',
    contentTypeSelector: 'text-[10px] font-mono text-gray-400 border border-gray-600 rounded px-2 py-0.5 bg-gray-700',
    sendButton:          { base: 'shrink-0 px-4 rounded-lg text-xs font-semibold transition-all bg-blue-600 hover:bg-blue-700 active:scale-[0.98] text-white shadow-sm', loading: 'bg-gray-700 text-gray-500 cursor-not-allowed shadow-none', disabled: 'bg-gray-700 text-gray-500 cursor-not-allowed shadow-none' },
    responsePanel:       'h-full border-t border-gray-700 flex flex-col',
    responseStatus:      { base: 'text-[10px] rounded px-1.5 py-0.5 font-mono font-semibold border bg-gray-800 text-gray-400 border-gray-600', success: 'bg-green-900/30 text-green-400 border-green-700', redirect: 'bg-blue-900/30 text-blue-400 border-blue-700', clientError: 'bg-amber-900/30 text-amber-400 border-amber-700', serverError: 'bg-red-900/30 text-red-400 border-red-700' },
    responseTime:        'text-[10px] text-gray-500 font-mono border border-gray-600 rounded px-1.5 py-0.5',
    responseSize:        'text-[10px] text-gray-500 font-mono',
    responseTabs:        'flex items-center gap-2 px-4 py-2 border-b border-gray-700 bg-gray-800/30 shrink-0',
    responseTab:         { base: 'px-2.5 py-1 text-[10px] rounded font-medium transition-colors text-gray-500 hover:text-gray-300', active: 'bg-gray-700 shadow-sm text-gray-200 border border-gray-600' },
    responseBody:        'flex-1 overflow-auto bg-gray-900',
    responseEmpty:       'shrink-0 border-t border-gray-700 h-10 flex items-center justify-center text-[10px] text-gray-600',
    errorBanner:         'mx-5 mb-4 px-3 py-2 bg-red-900/30 border border-red-700 rounded-lg text-xs text-red-400',
  },

  authStatus: {
    sectionLabel:      'text-[10px] font-semibold uppercase tracking-wider text-gray-500 mb-3',
    emptyText:         'text-[10px] text-gray-500',
    schemeRow:         'flex items-center justify-between py-2.5 px-3 rounded-lg border border-gray-700 bg-gray-700/30',
    schemeName:        'text-[11px] font-mono text-gray-300',
    schemeType:        'ml-1.5 text-[10px] text-gray-500',
    authorizedBadge:   'text-[9px] text-green-400 bg-green-900/30 border border-green-700 rounded px-1.5 py-0.5 font-semibold uppercase tracking-wide',
    unauthorizedBadge: 'text-[9px] text-gray-500 bg-gray-700 border border-gray-600 rounded px-1.5 py-0.5 uppercase tracking-wide',
  },

  bodyEditor: {
    fileInput:    'block w-full text-xs text-gray-400 cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-blue-900/40 file:text-blue-400 hover:file:bg-blue-900/60',
    formatButton: 'absolute top-1.5 right-1.5 z-10 text-[10px] text-gray-500 hover:text-blue-400 transition-colors px-1.5 py-0.5 rounded hover:bg-blue-900/30',
    textarea:     'w-full text-[11px] border border-gray-600 rounded-lg px-3 py-2.5 bg-gray-800 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 font-mono resize-y transition-colors leading-relaxed',
  },

  paramLabel: {
    nameText:        'font-mono text-[11px] text-gray-200',
    nameDeprecated:  'font-mono text-[11px] line-through text-gray-500',
    locPath:         'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-orange-400 bg-orange-900/30',
    locQuery:        'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-teal-400 bg-teal-900/30',
    locHeader:       'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-indigo-400 bg-indigo-900/30',
    locCookie:       'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-purple-400 bg-purple-900/30',
    locForm:         'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-blue-400 bg-blue-900/30',
    locDefault:      'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-gray-400 bg-gray-700',
    typeBadge:       'text-[9px] font-mono text-violet-400 bg-violet-900/30 rounded px-1.5 py-0.5 leading-none',
    requiredBadge:   'text-[9px] font-semibold text-red-400 bg-red-900/30 rounded px-1.5 py-0.5 leading-none',
    deprecatedBadge: 'text-[9px] font-semibold text-amber-400 bg-amber-900/30 rounded px-1.5 py-0.5 leading-none',
    constraintBadge: 'text-[9px] font-mono text-gray-400 bg-gray-700/60 rounded px-1.5 py-0.5 leading-none',
    tooltipIcon:     'w-3.5 h-3.5 text-gray-500 cursor-help hover:text-gray-300 transition-colors',
    tooltipPopup:    'pointer-events-none absolute bottom-full right-0 mb-2 w-56 rounded-lg bg-gray-950 px-2.5 py-2 text-[10px] text-gray-100 leading-snug shadow-lg opacity-0 group-hover/tip:opacity-100 transition-opacity z-50',
  },

  responsePanel: {
    loadingState:  'shrink-0 border-t border-gray-700 h-16 flex items-center justify-center gap-2 text-xs text-gray-500 bg-gray-800/30',
    emptyState:    'shrink-0 border-t border-gray-700 h-10 flex items-center justify-center',
    emptyText:     'text-[10px] text-gray-600',
    container:     'h-full border-t border-gray-700 flex flex-col',
    tabBar:        'flex items-center gap-2 px-4 py-2 border-b border-gray-700 bg-gray-800/30 shrink-0',
    tab:           { base: 'px-2.5 py-1 text-[10px] rounded font-medium transition-colors text-gray-500 hover:text-gray-300', active: 'bg-gray-700 shadow-sm text-gray-200 border border-gray-600' },
    tabDivider:    'w-px h-3 bg-gray-700 mx-1',
    headerCount:   'ml-0.5 text-gray-600',
    copyButton:    { base: 'flex items-center gap-1 text-[10px] px-2 py-1 rounded hover:bg-gray-700 transition-colors text-gray-500 hover:text-gray-300', copied: 'text-green-400' },
    statusNeutral: 'text-[10px] border rounded px-1.5 py-0.5 font-mono font-semibold text-gray-400 bg-gray-800 border-gray-600',
    statusSuccess: 'text-[10px] border rounded px-1.5 py-0.5 font-mono font-semibold text-green-400 bg-green-900/30 border-green-700',
    statusError:   'text-[10px] border rounded px-1.5 py-0.5 font-mono font-semibold text-red-400 bg-red-900/30 border-red-700',
    bodyContainer: 'flex-1 overflow-auto bg-gray-900',
    bodyPre:       'text-[11px] p-3 text-gray-300 font-mono leading-relaxed',
    headersPre:    'text-[11px] p-3 text-gray-400 font-mono leading-relaxed',
  },

  sendBar: {
    container:          'px-5 py-3 border-b border-gray-700 shrink-0 bg-gray-800/30',
    urlBox:             'flex items-center gap-2 flex-1 min-w-0 bg-gray-800 rounded-lg px-2.5 py-2 border border-gray-600',
    urlCode:            'text-[10px] text-gray-400 leading-tight flex-1 min-w-0 break-all',
    sendButtonActive:   'shrink-0 px-4 rounded-lg text-xs font-semibold transition-all bg-blue-600 hover:bg-blue-700 active:scale-[0.98] text-white shadow-sm',
    sendButtonDisabled: 'shrink-0 px-4 rounded-lg text-xs font-semibold transition-all bg-gray-700 text-gray-500 cursor-not-allowed',
  },

  inputScalar: {
    input:        'w-full text-xs border border-gray-600 rounded-lg px-3 py-2 bg-gray-800 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 transition-colors font-mono',
    inputInvalid: 'w-full text-xs border border-red-500 rounded-lg px-3 py-2 bg-gray-800 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-red-400 focus:border-red-400 transition-colors font-mono',
  },

  inputBoolean: {
    select:        'w-full text-xs border border-gray-600 rounded-lg px-3 py-2 bg-gray-800 text-gray-200 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 transition-colors font-mono',
    selectInvalid: 'w-full text-xs border border-red-500 rounded-lg px-3 py-2 bg-gray-800 text-gray-200 focus:outline-none focus:ring-1 focus:ring-red-400 focus:border-red-400 transition-colors font-mono',
  },

  inputEnum: {
    select:        'w-full text-xs border border-gray-600 rounded-lg px-3 py-2 bg-gray-800 text-gray-200 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 transition-colors font-mono',
    selectInvalid: 'w-full text-xs border border-red-500 rounded-lg px-3 py-2 bg-gray-800 text-gray-200 focus:outline-none focus:ring-1 focus:ring-red-400 focus:border-red-400 transition-colors font-mono',
  },

  inputFile: {
    input: 'block w-full text-xs text-gray-400 cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-blue-900/40 file:text-blue-400 hover:file:bg-blue-900/60',
  },

  inputArray: {
    rowInput:        'flex-1 text-xs border border-gray-600 rounded-lg px-3 py-2 bg-gray-800 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 transition-colors font-mono',
    rowInputInvalid: 'flex-1 text-xs border border-red-500 rounded-lg px-3 py-2 bg-gray-800 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-red-400 focus:border-red-400 transition-colors font-mono',
    rowIndex:        'text-[9px] text-gray-600 font-mono w-4 text-right shrink-0',
    removeButton:    'shrink-0 w-5 h-5 flex items-center justify-center rounded text-gray-600 hover:text-red-400 hover:bg-red-900/20 disabled:opacity-0 transition-colors',
    addButton:       'flex items-center gap-1 text-[10px] text-blue-400 hover:text-blue-300 transition-colors',
    hint:            'text-[9px] text-gray-600 font-mono',
  },

  inputMultiSelect: {
    trigger:        'w-full text-xs border border-gray-600 rounded-lg px-3 py-2 bg-gray-800 text-gray-200 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 transition-colors font-mono flex items-center justify-between text-left',
    triggerInvalid: 'w-full text-xs border border-red-500 rounded-lg px-3 py-2 bg-gray-800 text-gray-200 focus:outline-none focus:ring-1 focus:ring-red-400 focus:border-red-400 transition-colors font-mono flex items-center justify-between text-left',
    placeholder:    'text-gray-500',
    dropdown:       'absolute z-20 mt-1 w-full rounded-lg border border-gray-600 bg-gray-800 shadow-lg py-1',
    dropdownItem:   'flex items-center gap-2 px-3 py-1.5 hover:bg-gray-700/60 cursor-pointer',
    optionText:     'text-xs font-mono text-gray-300',
  },

  inputObject: {
    textarea:        'w-full text-xs border border-gray-600 rounded-lg px-3 py-2 bg-gray-800 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 transition-colors font-mono resize-y',
    textareaInvalid: 'w-full text-xs border border-red-500 rounded-lg px-3 py-2 bg-gray-800 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-red-400 focus:border-red-400 transition-colors font-mono resize-y',
  },

  detailPane: {
    spinner:      'w-5 h-5 animate-spin text-blue-500',
    errorIcon:    'w-10 h-10 rounded-full bg-red-900/30 flex items-center justify-center shrink-0 text-red-500',
    errorMessage: 'text-sm text-red-400',
    retryLink:    'text-xs text-gray-500 hover:text-gray-300 underline underline-offset-2',
    emptyIcon:    'w-10 h-10 rounded-full bg-gray-800 flex items-center justify-center text-gray-500',
    emptyMessage: 'text-sm text-gray-500',
  },

  verticalResizable: {
    handle: 'w-8 h-0.5 rounded-full bg-gray-600 group-hover:bg-blue-500 transition-colors',
  },

  syntax: {
    key:     '#60a5fa',
    string:  '#4ade80',
    boolean: '#c084fc',
    null:    '#6b7280',
    number:  '#fbbf24',
  },

  paneHandle:  'bg-gray-600 group-hover:bg-blue-400 group-hover:w-0.5 group-[.dragging]:bg-blue-500 group-[.dragging]:w-0.5',
  fontFamily:  "'IBM Plex Sans', ui-sans-serif, system-ui, sans-serif",
  focusRing:   'focus:ring-2 focus:ring-blue-400 focus:ring-offset-1',
  scrollbar:   { thumb: 'bg-gray-600', thumbHover: 'bg-gray-500' },
};