/**
 * Dark theme — derived from current dark-mode Tailwind classes (the dark: variants from the original components).
 */
import type { AppTheme } from '../contract';

const methodBadge = {
  base:    'method-badge shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] rounded uppercase w-[36px] text-center',
  get:     'bg-blue-900/30 text-blue-400',
  post:    'bg-green-900/30 text-green-400',
  put:     'bg-amber-900/30 text-amber-400',
  delete:  'bg-red-900/30 text-red-400',
  patch:   'bg-pink-900/30 text-pink-400',
  options: 'bg-gray-700 text-gray-400',
  head:    'bg-gray-700 text-gray-400',
};

export const darkTheme: AppTheme = {
  name: 'dark',

  nav: {
    container:         'shrink-0 bg-gray-800 overflow-y-auto flex flex-col h-full',
    divider:           'border-t border-gray-700',
    searchWrapper:     'px-4 py-3 border-b border-gray-700 shrink-0',
    searchInput:       'w-full pl-7 pr-6 py-2 text-[11px] border border-gray-600 rounded-md bg-gray-700 text-gray-300 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 transition-colors',
    searchIcon:        'absolute left-2.5 top-1/2 -translate-y-1/2 w-3 h-3 text-gray-500 pointer-events-none',
    searchClearButton: 'absolute right-2 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-300 leading-none text-sm',
    tabBar:            'flex gap-1 px-4 py-2 border-b border-gray-700',
    tab:               { base: 'px-2.5 py-1 text-[11px] font-medium rounded transition-colors text-gray-500 hover:text-gray-300', active: 'bg-gray-700 text-gray-200 border border-gray-600 shadow-sm' },
    tagHeader:         'w-full flex items-center justify-between px-4 py-2.5 text-[10px] font-semibold uppercase tracking-widest text-gray-500 hover:text-gray-300 transition-colors',
    tagChevron:        { base: 'w-3 h-3 transition-transform -rotate-90', open: 'rotate-0' },
    tagCount:          'text-[10px] text-gray-500 font-mono',
    endpointItem:      { base: 'nav-endpoint w-full flex items-center gap-2.5 px-4 py-2 text-left transition-colors text-gray-400 hover:bg-gray-700/50 hover:text-gray-200', active: 'bg-gray-700 text-gray-100', deprecated: 'opacity-60' },
    endpointPath:      'truncate text-[11px] font-mono',
    methodBadge,
    schemaItem:        { base: 'w-full text-left flex flex-col gap-0.5 px-4 py-2 transition-colors hover:bg-gray-700/50', active: 'bg-gray-700' },
    schemaName:        'truncate text-[11px] font-mono text-gray-300',
    schemaTypeBadge:   'shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] rounded bg-purple-900/30 text-purple-400 uppercase',
    emptyState:        'flex flex-col items-center justify-center px-4 py-8 text-center text-[11px] text-gray-500',
  },

  endpoint: {
    container:          'h-full flex flex-col',
    header:             'flex items-center gap-3 px-6 py-5 border-b border-gray-700 shrink-0 h-[50px]',
    methodBadge,
    path:               'font-mono text-sm text-gray-200',
    summary:            'text-sm text-gray-200 mb-2 font-medium',
    description:        'text-xs text-gray-400 mb-8 leading-relaxed',
    deprecated:         'ml-auto text-[10px] bg-amber-900/30 text-amber-400 border border-amber-700 rounded px-2 py-0.5',
    paramSection:       'mb-8',
    paramSectionTitle:  'text-xs font-semibold uppercase tracking-wider text-gray-500 mb-4',
    paramRow:           { base: 'border-b border-gray-700 last:border-0 bg-gray-800/50 hover:bg-gray-700/50 transition-colors', required: '' },
    paramName:          'font-mono text-[11px] text-gray-200',
    paramType:          'text-[10px] bg-gray-700 text-gray-400 rounded px-1.5 py-0.5 font-mono',
    paramRequired:      'text-red-400 text-[9px] font-semibold ml-1',
    paramDescription:   'text-xs text-gray-400',
    responseAccordion:  'border border-gray-700 rounded-lg overflow-hidden divide-y divide-gray-700',
    responseHeader:     { base: 'w-full flex items-center gap-3 px-4 py-3.5 hover:bg-gray-800/50 transition-colors text-left', open: '' },
    responseStatusCode: { base: 'text-xs font-mono font-semibold', success: 'text-green-400', redirect: 'text-blue-400', clientError: 'text-amber-400', serverError: 'text-red-400' },
    responseDescription:'text-xs text-gray-400 flex-1',
    bodySection:        'mb-8',
    bodyContentType:    'text-[10px] text-gray-400 font-mono',
  },

  playground: {
    container:           'h-full flex flex-col bg-gray-900',
    header:              'flex items-center gap-2 px-5 border-b border-gray-700 shrink-0 h-[50px]',
    inputLabel:          'text-[10px] font-semibold uppercase tracking-wider text-gray-500 mb-3',
    textInput:           'w-full text-xs border border-gray-600 rounded-lg px-3 py-2 bg-gray-700 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 transition-colors font-mono',
    selectInput:         'w-full text-xs border border-gray-600 rounded-lg px-3 py-2 bg-gray-700 text-gray-300 focus:outline-none focus:ring-1 focus:ring-blue-400 cursor-pointer transition-colors',
    fileInput:           'block w-full text-xs text-gray-400 cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-blue-900/40 file:text-blue-400 hover:file:bg-blue-900/60',
    fileInputButton:     { base: 'file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-blue-900/40 file:text-blue-400 hover:file:bg-blue-900/60', hasFile: 'file:bg-blue-900/60' },
    bodyEditor:          'w-full text-[11px] border border-gray-600 rounded-lg px-3 py-2.5 bg-gray-800 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 font-mono resize-y transition-colors leading-relaxed',
    contentTypeSelector: 'text-[10px] font-mono text-gray-400 border border-gray-600 rounded px-2 py-0.5 bg-gray-700',
    sendButton:          { base: 'shrink-0 px-4 rounded-lg text-xs font-semibold transition-all bg-blue-600 hover:bg-blue-700 active:scale-[0.98] text-white shadow-sm', loading: 'bg-gray-700 text-gray-500 cursor-not-allowed shadow-none', disabled: 'bg-gray-700 text-gray-500 cursor-not-allowed shadow-none' },
    responsePanel:       'h-full border-t border-gray-700 flex flex-col',
    responseStatus:      { base: 'text-[10px] rounded px-1.5 py-0.5 font-mono font-semibold border bg-gray-800 text-gray-400 border-gray-600', success: 'bg-green-900/30 text-green-400 border-green-700', redirect: 'bg-blue-900/30 text-blue-400 border-blue-700', clientError: 'bg-amber-900/30 text-amber-400 border-amber-700', serverError: 'bg-red-900/30 text-red-400 border-red-700' },
    responseTime:        'text-[10px] text-gray-500 font-mono border border-gray-600 rounded px-1.5 py-0.5',
    responseSize:        'text-[10px] text-gray-500 font-mono',
    responseTabs:        'flex items-center gap-2 px-4 py-2 border-b border-gray-700 bg-gray-800/30 shrink-0',
    responseTab:         { base: 'px-2.5 py-1 text-[10px] rounded font-medium transition-colors text-gray-500 hover:text-gray-300', active: 'bg-gray-700 shadow-sm text-gray-200 border border-gray-600' },
    responseBody:        'flex-1 overflow-auto bg-gray-900',
    responseEmpty:       'shrink-0 border-t border-gray-700 h-10 flex items-center justify-center text-[10px] text-gray-600',
    errorBanner:         'mx-5 mb-4 px-3 py-2 bg-red-900/30 border border-red-700 rounded-lg text-xs text-red-400',
  },

  topBar: {
    container:       'relative flex items-center gap-4 px-6 h-16 border-b border-gray-700 bg-gray-900 shrink-0 z-10',
    title:           'text-sm font-semibold text-gray-100 truncate',
    serverChip:      { base: 'flex items-center gap-1.5 text-[11px] font-mono px-2.5 py-1.5 rounded-lg border transition-colors shrink-0 text-gray-400 border-gray-600 bg-gray-800 hover:bg-gray-700 hover:border-gray-500', open: 'bg-blue-900/30 text-blue-400 border-blue-700' },
    themeButton:     'flex items-center gap-1.5 text-xs rounded-md px-2.5 py-1.5 font-medium border transition-all shrink-0 text-gray-400 bg-gray-800 border-gray-600 hover:bg-gray-700 hover:border-gray-500',
    authButton:      { base: 'flex items-center gap-1.5 text-xs rounded-md px-2.5 py-1.5 font-medium border transition-all shrink-0 text-gray-400 bg-gray-800 border-gray-600 hover:bg-gray-700 hover:border-gray-500', configured: 'text-emerald-400 bg-emerald-900/30 border-emerald-700 hover:bg-emerald-900/50' },
    shortcutsButton: 'flex items-center gap-1.5 text-xs rounded-md px-2.5 py-1.5 font-medium border transition-all shrink-0 text-gray-400 bg-gray-800 border-gray-600 hover:bg-gray-700 hover:border-gray-500',
    loadButton:      'flex items-center gap-1.5 text-xs text-white bg-blue-600 hover:bg-blue-700 active:bg-blue-800 rounded-md px-3 py-1.5 font-medium transition-colors shrink-0 shadow-sm',
  },

  modal: {
    backdrop:    'fixed inset-0 bg-black/50 flex items-center justify-center z-50',
    container:   'bg-gray-800 rounded-xl shadow-xl w-full mx-4 overflow-hidden',
    header:      'flex items-center justify-between px-5 py-4 border-b border-gray-700',
    title:       'text-sm font-semibold text-gray-200',
    closeButton: 'text-gray-500 hover:text-gray-300 text-xl leading-none',
    body:        '',
    footer:      'px-5 py-3 bg-gray-700/50 border-t border-gray-700',
  },

  schema: {
    container:      '',
    tabBar:         'flex gap-1 px-3 py-2 bg-gray-800/80 border-b border-gray-700',
    tab:            { base: 'px-3 py-1 text-[11px] font-medium rounded-md text-gray-500 hover:text-gray-300 transition-colors', active: 'bg-gray-700 text-gray-200 border border-gray-600' },
    nodeRow:        'py-0.5',
    nodeKey:        'font-mono text-[11px] text-gray-200',
    nodeType:       { base: 'text-[10px] rounded px-1.5 py-0.5 font-mono', string: 'bg-emerald-900/30 text-emerald-400', integer: 'bg-blue-900/30 text-blue-400', number: 'bg-blue-900/30 text-blue-400', boolean: 'bg-purple-900/30 text-purple-400', object: 'bg-amber-900/30 text-amber-400', array: 'bg-cyan-900/30 text-cyan-400' },
    nodeDescription:'text-[11px] text-gray-400 mt-0.5 leading-relaxed',
    nodeRequired:   'text-red-400 text-[9px] font-semibold',
    nodeExpandButton: { base: 'w-3.5 h-3.5 transition-transform', open: 'rotate-90' },
    nodeNested:     'border-l-2 border-gray-700 ml-3 pl-3 mt-0.5',
    exampleBlock:   'text-[11px] bg-gray-900 rounded-md p-3 overflow-x-auto text-gray-300 font-mono leading-relaxed',
  },

  authModal: {
    schemeSection:    '',
    schemeName:       'text-sm font-semibold text-gray-200',
    schemeType:       'text-[10px] text-gray-500',
    schemeDescription:'text-[10px] text-gray-500',
    tokenInput:       'w-full text-xs border border-gray-600 rounded-lg px-3 py-2 bg-gray-700 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 font-mono',
    usernameInput:    'w-full text-xs border border-gray-600 rounded-lg px-3 py-2 bg-gray-700 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 font-mono',
    passwordInput:    'w-full text-xs border border-gray-600 rounded-lg px-3 py-2 bg-gray-700 text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 font-mono',
    saveButton:       'text-xs bg-blue-600 hover:bg-blue-700 text-white px-3 py-1.5 rounded-md font-medium transition-colors',
    clearButton:      'text-xs border border-gray-600 text-gray-400 hover:border-gray-500 hover:text-gray-200 px-3 py-1.5 rounded-md font-medium transition-colors',
  },

  serverConfig: {
    chip:               { base: 'flex items-center gap-1.5 text-[11px] font-mono px-2.5 py-1.5 rounded-lg border transition-colors shrink-0 text-gray-400 border-gray-600 bg-gray-800 hover:bg-gray-700 hover:border-gray-500', open: 'bg-blue-900/30 text-blue-400 border-blue-700' },
    popover:            'bg-gray-800 rounded-xl shadow-xl w-full max-w-sm mx-4 overflow-hidden',
    serverOption:       { base: 'w-full text-[11px] font-mono border border-gray-600 rounded-lg px-3 py-2 bg-gray-700 text-gray-300 focus:outline-none focus:ring-1 focus:ring-blue-400 cursor-pointer', selected: '' },
    variableLabel:      'text-[11px] font-mono font-medium text-gray-300',
    variableInput:      'text-[11px] font-mono border border-gray-600 rounded-lg px-2.5 py-1.5 bg-gray-700 text-gray-300 focus:outline-none focus:ring-1 focus:ring-blue-400 w-full',
    variableDescription:'text-[10px] text-gray-500 leading-tight mt-0.5',
  },

  commandBar: {
    backdrop:      'fixed inset-0 bg-black/60 z-[60] flex items-start justify-center pt-[12vh]',
    container:     'bg-gray-900 rounded-xl shadow-2xl w-full max-w-lg mx-4 flex flex-col overflow-hidden border border-gray-700 max-h-[70vh]',
    input:         'flex-1 bg-transparent text-sm text-gray-200 placeholder-gray-500 outline-none',
    resultItem:    { base: 'w-full flex items-center gap-3 px-4 py-2.5 text-left transition-colors hover:bg-gray-800/60', highlighted: 'bg-blue-900/30' },
    resultLabel:   'text-sm font-medium text-gray-200 truncate',
    resultCategory:'px-4 py-1.5 text-[10px] font-semibold uppercase tracking-widest text-gray-500 select-none',
    emptyState:    'flex flex-col items-center justify-center py-12 text-center text-sm text-gray-500',
    shortcutBadge: 'font-mono text-[10px] bg-gray-700 border border-gray-600 rounded px-1 py-px',
  },

  syntax: {
    key:     '#c084fc',
    string:  '#7dd3fc',
    boolean: '#86efac',
    null:    '#fca5a5',
    number:  '#fcd34d',
  },

  paneHandle: 'bg-gray-700',
  focusRing:  'ring-2 ring-blue-500',
  scrollbar:  { thumb: 'bg-gray-600', thumbHover: 'bg-gray-500' },
};