/**
 * Nord theme preset — arctic, blue-grey dark theme based on the Nord color palette.
 * Polar Night (#2E3440–#4C566A) for backgrounds, Snow Storm (#D8DEE9–#ECEFF4) for text,
 * Frost (#5E81AC–#8FBCBB) for interactive accents, Aurora colors for semantic states.
 */
import type { AppTheme } from '../contract';

const methodBadgeBase = 'method-badge shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] rounded uppercase w-[36px] text-center';

export const nordTheme: AppTheme = {
  name: 'nord',

  appRoot: {
    root:              'flex flex-col h-full overflow-hidden bg-[#2E3440]',
    navPane:           'shrink-0 bg-[#3B4252] overflow-y-auto flex flex-col',
    detailPane:        'flex-1 min-w-0 bg-[#2E3440] overflow-hidden',
    tryPane:           'shrink-0 bg-[#2E3440] overflow-hidden',
    shortcutsBackdrop: 'fixed inset-0 bg-black/60 flex items-center justify-center z-50',
    shortcutsPanel:    'bg-[#3B4252] rounded-xl shadow-xl w-72 mx-4 overflow-hidden',
    shortcutsHeader:   'flex items-center justify-between px-5 py-3.5 border-b border-[#4C566A]',
    shortcutsTitle:    'text-sm font-semibold text-[#ECEFF4]',
    shortcutsClose:    'text-[#4C566A] hover:text-[#D8DEE9] text-xl leading-none transition-colors',
    shortcutsRow:      'flex items-center justify-between py-1.5 border-b border-[#4C566A]/40 last:border-0',
    shortcutsDesc:     'text-xs text-[#D8DEE9]',
    shortcutsKbd:      'text-[10px] font-mono bg-[#434C5E] text-[#81A1C1] px-2 py-0.5 rounded border border-[#4C566A] shrink-0',
  },

  nav: {
    container:         'shrink-0 bg-[#3B4252] overflow-y-auto flex flex-col h-full',
    divider:           'mt-1 border-t border-[#4C566A]',
    searchWrapper:     'px-4 py-3 border-b border-[#4C566A] shrink-0',
    searchInput:       'w-full pl-7 pr-6 py-2 text-[11px] border border-[#4C566A] rounded-md bg-[#2E3440] text-[#D8DEE9] placeholder-[#4C566A] focus:outline-none focus:ring-1 focus:ring-[#88C0D0] focus:border-[#88C0D0] transition-colors',
    searchIcon:        'absolute left-2.5 top-1/2 -translate-y-1/2 w-3 h-3 text-[#4C566A] pointer-events-none',
    searchClearButton: 'absolute right-2 top-1/2 -translate-y-1/2 text-[#4C566A] hover:text-[#D8DEE9] leading-none text-sm',
    searchHint:        'absolute right-2 top-1/2 -translate-y-1/2 text-[9px] text-[#4C566A] border border-[#4C566A] rounded px-1 font-mono pointer-events-none leading-none',
    loadingSpinner:    'w-5 h-5 animate-spin text-[#88C0D0]',
    tabBar:            'flex gap-1 px-4 py-2 border-b border-[#4C566A]',
    tab:               { base: 'px-2.5 py-1 text-[11px] font-medium rounded transition-colors text-[#4C566A] hover:text-[#D8DEE9]', active: 'bg-[#434C5E] text-[#ECEFF4] border border-[#4C566A] shadow-sm' },
    tagHeader:         'w-full flex items-center justify-between px-4 py-2.5 text-[10px] font-semibold uppercase tracking-widest text-[#4C566A] hover:text-[#88C0D0] transition-colors',
    tagChevron:        'w-3 h-3 transition-transform',
    tagCount:          'text-[10px] text-[#4C566A] font-mono',
    endpointItem:      { base: 'nav-endpoint w-full flex items-center gap-2.5 px-4 py-2 text-left transition-colors text-[#81A1C1] hover:bg-[#434C5E]/60 hover:text-[#ECEFF4]', active: 'bg-[#434C5E] text-[#ECEFF4]' },
    endpointPath:      'truncate text-[11px] font-mono',
    methodBadge:       { base: methodBadgeBase, get: 'bg-[#5E81AC]/25 text-[#88C0D0]', post: 'bg-[#A3BE8C]/20 text-[#A3BE8C]', put: 'bg-[#EBCB8B]/20 text-[#EBCB8B]', delete: 'bg-[#BF616A]/20 text-[#BF616A]', patch: 'bg-[#B48EAD]/20 text-[#B48EAD]', options: 'bg-[#434C5E] text-[#81A1C1]', head: 'bg-[#434C5E] text-[#81A1C1]' },
    schemaItem:        { base: 'w-full text-left gap-2.5 px-4 py-2 transition-colors hover:bg-[#434C5E]/60', active: 'bg-[#434C5E]' },
    schemaName:        { base: 'truncate text-[11px] font-mono text-[#81A1C1]', active: 'text-[#ECEFF4]' },
    schemaTypeBadge:   'shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] rounded bg-[#B48EAD]/20 text-[#B48EAD] uppercase',
    schemaDescription: 'mt-0.5 text-[10px] text-[#4C566A] truncate pl-[38px]',
    emptyState:        'text-[11px] text-[#4C566A]',
  },

  endpoint: {
    container:           'h-full flex flex-col',
    header:              'flex items-center gap-3 px-6 py-5 border-b border-[#4C566A] shrink-0 h-[50px]',
    methodBadge:         { base: methodBadgeBase, get: 'bg-[#5E81AC]/25 text-[#88C0D0]', post: 'bg-[#A3BE8C]/20 text-[#A3BE8C]', put: 'bg-[#EBCB8B]/20 text-[#EBCB8B]', delete: 'bg-[#BF616A]/20 text-[#BF616A]', patch: 'bg-[#B48EAD]/20 text-[#B48EAD]', options: 'bg-[#434C5E] text-[#81A1C1]', head: 'bg-[#434C5E] text-[#81A1C1]' },
    path:                'font-mono text-sm text-[#ECEFF4]',
    summary:             'text-sm text-[#E5E9F0] mb-2 font-medium',
    description:         'text-xs text-[#81A1C1]',
    deprecated:          'ml-auto text-[10px] bg-[#EBCB8B]/15 text-[#EBCB8B] border border-[#EBCB8B]/30 rounded px-2 py-0.5',
    paramSection:        'border border-[#4C566A] rounded-lg overflow-hidden',
    paramSectionTitle:   'text-xs font-semibold uppercase tracking-wider text-[#4C566A] mb-4',
    paramLocTitle:       'text-[10px] font-semibold uppercase tracking-wider text-[#4C566A] mb-3',
    paramRow:            'border-b border-[#4C566A] last:border-0 bg-[#3B4252]/50 hover:bg-[#434C5E]/50 transition-colors',
    paramName:           'font-mono text-[11px] text-[#ECEFF4]',
    paramType:           'text-[10px] bg-[#434C5E] text-[#81A1C1] rounded px-1.5 py-0.5 font-mono',
    paramRequired:       'text-[#BF616A] text-[9px] font-semibold ml-1',
    paramDescription:    'px-4 py-3 w-full text-xs text-[#81A1C1]',
    mutedText:           'text-[#4C566A]',
    responseAccordion:   'border border-[#4C566A] rounded-lg overflow-hidden divide-y divide-[#4C566A]',
    responseHeader:      'w-full flex items-center gap-3 px-4 py-3.5 hover:bg-[#434C5E]/50 transition-colors text-left',
    responseStatusCode:  { base: 'text-xs font-mono font-semibold', success: 'text-[#A3BE8C]', redirect: 'text-[#88C0D0]', clientError: 'text-[#EBCB8B]', serverError: 'text-[#BF616A]' },
    responseDescription: 'text-xs text-[#81A1C1] flex-1',
    bodySection:         'px-3 py-1.5 bg-[#3B4252] border-b border-[#4C566A] flex items-center gap-2',
    bodyContentType:     'text-[10px] text-[#4C566A] font-mono',
  },

  topBar: {
    container:              'relative flex items-center gap-4 px-6 h-16 border-b border-[#4C566A] bg-[#2E3440] shrink-0 z-10',
    specTitle:              'text-sm font-semibold text-[#ECEFF4] truncate',
    specVersion:            'text-[10px] text-[#4C566A] border border-[#4C566A] rounded-full px-1.5 py-px font-mono shrink-0 leading-tight',
    specDescription:        'text-[10px] text-[#4C566A] truncate leading-tight mt-px',
    noSpecIcon:             'w-7 h-7 rounded-lg bg-gradient-to-br from-[#3B4252] to-[#434C5E] flex items-center justify-center shrink-0',
    noSpecIconSvg:          'w-4 h-4 text-[#4C566A]',
    noSpecTitle:            'text-sm font-semibold text-[#4C566A]',
    divider:                'w-px h-5 bg-[#4C566A] mx-1 shrink-0',
    authButtonConfigured:   'flex items-center gap-1.5 text-xs rounded-md px-2.5 py-1.5 font-medium border transition-all shrink-0 text-[#A3BE8C] bg-[#A3BE8C]/10 border-[#A3BE8C]/30 hover:bg-[#A3BE8C]/20',
    authButtonUnconfigured: 'flex items-center gap-1.5 text-xs rounded-md px-2.5 py-1.5 font-medium border transition-all shrink-0 text-[#81A1C1] bg-[#3B4252] border-[#4C566A] hover:bg-[#434C5E] hover:border-[#81A1C1]',
    neutralButton:          'flex items-center gap-1.5 text-xs rounded-md px-2.5 py-1.5 font-medium border transition-all shrink-0 text-[#81A1C1] bg-[#3B4252] border-[#4C566A] hover:bg-[#434C5E] hover:border-[#81A1C1]',
    loadButton:             'flex items-center gap-1.5 text-xs text-[#ECEFF4] bg-[#5E81AC] hover:bg-[#81A1C1] active:bg-[#4C6A96] rounded-md px-3 py-1.5 font-medium transition-colors shrink-0 shadow-sm',
  },

  themePicker: {
    dropdown: 'bg-[#3B4252] border border-[#4C566A] rounded-xl shadow-xl py-1.5 overflow-hidden',
    item:     { base: 'w-full flex items-center gap-3 px-3 py-2 text-left hover:bg-[#434C5E]/60 transition-colors', active: 'bg-[#434C5E]' },
    name:     'text-sm text-[#ECEFF4] font-medium flex-1',
    check:    'w-3.5 h-3.5 text-[#88C0D0] shrink-0',
  },

  modal: {
    backdrop:    'fixed inset-0 bg-black/60 flex items-center justify-center z-50',
    container:   'bg-[#3B4252] rounded-xl shadow-xl w-full mx-4 overflow-hidden',
    header:      'flex items-center justify-between px-5 py-4 border-b border-[#4C566A]',
    closeButton: 'text-[#4C566A] hover:text-[#D8DEE9] text-xl leading-none',
    footer:      'px-5 py-3 bg-[#434C5E]/50 border-t border-[#4C566A]',
  },

  loadModal: {
    title:        'text-sm font-semibold text-[#ECEFF4]',
    footerText:   'text-[10px] text-[#4C566A]',
    petstoreLink: 'text-xs text-[#88C0D0] hover:underline',
    urlLabel:     'block text-xs font-medium text-[#81A1C1] mb-1.5',
    urlInput:     'flex-1 text-xs border border-[#4C566A] rounded-md px-3 py-2 bg-[#2E3440] text-[#D8DEE9] placeholder-[#4C566A] focus:outline-none focus:ring-1 focus:ring-[#88C0D0] focus:border-[#88C0D0] transition-colors',
    dividerLine:  'flex-1 border-t border-[#4C566A]',
    dividerText:  'text-[10px] text-[#4C566A] uppercase tracking-wider',
    fileLabel:    'block text-xs font-medium text-[#81A1C1] mb-1.5',
    fileDropZone: 'flex items-center justify-center gap-2 border-2 border-dashed border-[#4C566A] rounded-lg px-4 py-5 cursor-pointer hover:border-[#88C0D0] hover:bg-[#88C0D0]/5 transition-colors',
    fileDropIcon: 'w-4 h-4 text-[#4C566A]',
    fileDropText: 'text-xs text-[#81A1C1]',
    errorBanner:  'text-xs text-[#BF616A] bg-[#BF616A]/10 border border-[#BF616A]/30 rounded-md px-3 py-2',
  },

  authModal: {
    tabBar:            'flex gap-1 px-4 py-2 bg-[#3B4252]/80 border-b border-[#4C566A] overflow-x-auto',
    tabActive:         'px-3 py-1.5 text-[11px] font-medium rounded-md bg-[#434C5E] text-[#ECEFF4] border border-[#4C566A] flex items-center gap-1.5 shrink-0',
    tabInactive:       'px-3 py-1.5 text-[11px] font-medium rounded-md text-[#4C566A] hover:text-[#D8DEE9] transition-colors flex items-center gap-1.5 shrink-0',
    titleIcon:         'w-4 h-4 text-[#81A1C1]',
    titleText:         'text-sm font-semibold text-[#ECEFF4]',
    closeButton:       'text-xs bg-[#D8DEE9] hover:bg-[#ECEFF4] text-[#2E3440] px-4 py-2 rounded-md font-medium transition-colors',
    schemeType:        'text-[10px] text-[#4C566A]',
    authorizedBadge:   'text-[9px] text-[#A3BE8C] bg-[#A3BE8C]/10 border border-[#A3BE8C]/30 rounded px-1.5 py-0.5 font-semibold uppercase tracking-wide',
    schemeDescription: 'text-[10px] text-[#4C566A]',
    fieldLabel:        'block text-[10px] text-[#81A1C1] mb-1',
    fieldLabelHint:    'text-[#4C566A] font-sans',
    input:             'w-full text-xs border border-[#4C566A] rounded-lg px-3 py-2 bg-[#2E3440] text-[#D8DEE9] placeholder-[#4C566A] focus:outline-none focus:ring-1 focus:ring-[#88C0D0] focus:border-[#88C0D0] font-mono',
    tokenWrapper:      'flex items-stretch border border-[#4C566A] rounded-lg overflow-hidden bg-[#2E3440] focus-within:ring-1 focus-within:ring-[#88C0D0] focus-within:border-[#88C0D0] transition-all',
    tokenPrefix:       'px-2.5 flex items-center text-[10px] text-[#4C566A] bg-[#3B4252] border-r border-[#4C566A] font-mono shrink-0 select-none',
    tokenField:        'flex-1 text-xs px-2.5 py-2 bg-[#2E3440] text-[#D8DEE9] placeholder-[#4C566A] focus:outline-none font-mono min-w-0',
    saveButton:        'text-xs bg-[#5E81AC] hover:bg-[#81A1C1] text-[#ECEFF4] px-3 py-1.5 rounded-md font-medium transition-colors',
    clearButton:       'text-xs border border-[#4C566A] text-[#81A1C1] hover:border-[#81A1C1] hover:text-[#D8DEE9] px-3 py-1.5 rounded-md font-medium transition-colors',
  },

  serverConfig: {
    chip: {
      base: 'flex items-center gap-1.5 text-[11px] font-mono px-2.5 py-1.5 rounded-lg border transition-colors shrink-0 text-[#81A1C1] border-[#4C566A] bg-[#3B4252] hover:bg-[#434C5E] hover:border-[#81A1C1]',
      open: 'bg-[#5E81AC]/20 text-[#88C0D0] border-[#5E81AC]/50 hover:bg-[#5E81AC]/20 hover:border-[#5E81AC]/50',
    },
    chipIcon:            'w-3 h-3 shrink-0 text-[#4C566A]',
    backdrop:            'fixed inset-0 bg-black/60 flex items-center justify-center z-[60]',
    popover:             'bg-[#3B4252] rounded-xl shadow-xl w-full max-w-sm mx-4 overflow-hidden',
    popoverHeader:       'flex items-center justify-between px-5 py-4 border-b border-[#4C566A]',
    headerIcon:          'w-4 h-4 text-[#81A1C1]',
    headerTitle:         'text-sm font-semibold text-[#ECEFF4]',
    closeButton:         'text-[#4C566A] hover:text-[#D8DEE9] text-xl leading-none',
    sectionDivider:      'px-5 py-4 border-b border-[#4C566A]',
    sectionLabel:        'block text-[10px] font-semibold uppercase tracking-wider text-[#4C566A]',
    serverSelect:        'w-full text-[11px] font-mono border border-[#4C566A] rounded-lg px-3 py-2 bg-[#2E3440] text-[#D8DEE9] focus:outline-none focus:ring-1 focus:ring-[#88C0D0] cursor-pointer',
    variableName:        'text-[11px] font-mono font-medium text-[#D8DEE9]',
    variableDescription: 'text-[10px] text-[#4C566A] leading-tight mt-0.5',
    variableInput:       'text-[11px] font-mono border border-[#4C566A] rounded-lg px-2.5 py-1.5 bg-[#2E3440] text-[#D8DEE9] focus:outline-none focus:ring-1 focus:ring-[#88C0D0] w-full',
    resolvedSection:     'px-5 py-4 bg-[#434C5E]/40',
    resolvedLabel:       'text-[10px] font-semibold uppercase tracking-wider text-[#4C566A] mb-1.5',
    resolvedValue:       'text-[11px] font-mono text-[#88C0D0] break-all',
  },

  commandBar: {
    backdrop:       'fixed inset-0 bg-black/70 z-[60] flex items-start justify-center pt-[12vh]',
    container:      'bg-[#2E3440] rounded-xl shadow-2xl w-full max-w-lg mx-4 flex flex-col overflow-hidden border border-[#4C566A] max-h-[70vh]',
    searchRow:      'flex items-center gap-3 px-4 py-3 border-b border-[#3B4252] shrink-0',
    searchIcon:     'w-4 h-4 text-[#4C566A] shrink-0',
    input:          'flex-1 bg-transparent text-sm text-[#ECEFF4] placeholder-[#4C566A] outline-none',
    clearButton:    'text-[#4C566A] hover:text-[#D8DEE9] text-lg leading-none shrink-0 transition-colors',
    groupTitle:     'px-4 py-1.5 text-[10px] font-semibold uppercase tracking-widest text-[#4C566A] select-none',
    resultItem:     { base: 'w-full flex items-center gap-3 px-4 py-2.5 text-left transition-colors hover:bg-[#3B4252]/80', active: 'bg-[#5E81AC]/15 hover:bg-[#5E81AC]/15' },
    actionIcon:     { base: 'w-7 h-7 rounded-md flex items-center justify-center shrink-0 bg-[#3B4252] text-[#4C566A]', active: 'bg-[#5E81AC]/20 text-[#88C0D0]' },
    resultLabel:    'text-sm font-medium text-[#ECEFF4] truncate',
    resultSubtitle: 'text-xs text-[#4C566A] truncate mt-0.5',
    activeChevron:  'w-3.5 h-3.5 text-[#88C0D0] shrink-0',
    emptyIcon:      'w-8 h-8 text-[#4C566A] mb-3',
    emptyText:      'text-sm text-[#4C566A]',
    footer:         'shrink-0 flex items-center gap-4 px-4 py-2 border-t border-[#3B4252] bg-[#3B4252]/50',
    shortcutText:   'flex items-center gap-1 text-[11px] text-[#4C566A]',
    shortcutBadge:  'font-mono text-[10px] bg-[#434C5E] border border-[#4C566A] rounded px-1 py-px',
    specTitle:      'ml-auto text-[11px] text-[#4C566A] truncate',
    highlightMark:  'bg-[#EBCB8B]/20 text-inherit not-italic rounded-sm',
  },

  schema: {
    tabBar:       'flex gap-1 px-3 py-2 bg-[#3B4252]/80 border-b border-[#4C566A]',
    tabActive:    'px-3 py-1 text-[11px] font-medium rounded-md bg-[#434C5E] text-[#ECEFF4] border border-[#4C566A]',
    tabInactive:  'px-3 py-1 text-[11px] font-medium rounded-md text-[#4C566A] hover:text-[#D8DEE9] transition-colors',
    description:  'px-4 pt-3 pb-0 text-[11px] text-[#81A1C1] leading-relaxed',
    exampleBlock: 'text-[11px] bg-[#2E3440] rounded-md p-3 overflow-x-auto text-[#D8DEE9] font-mono leading-relaxed',
  },

  schemaNode: {
    name:          'font-mono text-[11px] text-[#ECEFF4]',
    typeBadge:     'text-[10px] rounded px-1.5 py-0.5 font-mono',
    nullableBadge: 'text-[9px] bg-[#434C5E] text-[#81A1C1] rounded px-1 font-mono',
    constraint:    'text-[9px] font-mono text-[#4C566A]',
    enumValue:     'text-[9px] text-[#4C566A] font-mono',
    description:   'text-[11px] text-[#81A1C1] mt-0.5 leading-relaxed',
    enumKey:       'font-mono text-[#D8DEE9]',
    enumDesc:      'text-[#4C566A]',
    nestedBorder:  'border-l-2 border-[#4C566A] ml-3 pl-3 mt-0.5',
    typeBadgeColors: {
      string:  'bg-[#A3BE8C]/20 text-[#A3BE8C]',
      integer: 'bg-[#5E81AC]/25 text-[#88C0D0]',
      number:  'bg-[#5E81AC]/25 text-[#88C0D0]',
      boolean: 'bg-[#B48EAD]/20 text-[#B48EAD]',
      object:  'bg-[#D08770]/20 text-[#D08770]',
      array:   'bg-[#8FBCBB]/20 text-[#8FBCBB]',
      default: 'bg-[#434C5E] text-[#81A1C1]',
    },
  },

  schemaDetail: {
    header:      'flex items-center gap-3 px-6 py-5 border-b border-[#4C566A] shrink-0',
    typeBadge:   'text-[9px] font-bold font-mono px-[5px] py-[2px] rounded uppercase',
    schemaName:  'font-mono text-sm text-[#ECEFF4]',
    description: 'text-sm text-[#81A1C1] mb-6 leading-relaxed',
    sectionLabel:'text-xs font-semibold uppercase tracking-wider text-[#4C566A] mb-4',
    schemaBox:   'border border-[#4C566A] rounded-lg overflow-hidden bg-[#3B4252]/50',
    typeBadgeColors: {
      string:  'bg-[#A3BE8C]/20 text-[#A3BE8C]',
      integer: 'bg-[#5E81AC]/25 text-[#88C0D0]',
      number:  'bg-[#5E81AC]/25 text-[#88C0D0]',
      boolean: 'bg-[#B48EAD]/20 text-[#B48EAD]',
      object:  'bg-[#D08770]/20 text-[#D08770]',
      array:   'bg-[#8FBCBB]/20 text-[#8FBCBB]',
      default: 'bg-[#434C5E] text-[#81A1C1]',
    },
  },

  playground: {
    container:           'h-full flex flex-col bg-[#2E3440]',
    header:              'flex items-center gap-2 px-5 border-b border-[#4C566A] shrink-0 h-[50px]',
    headerTitle:         'text-xs font-semibold text-[#81A1C1]',
    emptyState:          'h-full flex flex-col items-center justify-center text-center px-6 gap-3 bg-[#2E3440]',
    emptyIconWrapper:    'w-10 h-10 rounded-full bg-[#3B4252] flex items-center justify-center',
    emptyIcon:           'w-5 h-5 text-[#4C566A]',
    emptyText:           'text-sm text-[#4C566A]',
    inputLabel:          'text-[10px] font-semibold uppercase tracking-wider text-[#4C566A] mb-3',
    textInput:           'w-full text-xs border border-[#4C566A] rounded-lg px-3 py-2 bg-[#3B4252] text-[#D8DEE9] placeholder-[#4C566A] focus:outline-none focus:ring-1 focus:ring-[#88C0D0] focus:border-[#88C0D0] transition-colors font-mono',
    selectInput:         'w-full text-xs border border-[#4C566A] rounded-lg px-3 py-2 bg-[#3B4252] text-[#D8DEE9] focus:outline-none focus:ring-1 focus:ring-[#88C0D0] cursor-pointer transition-colors',
    fileInput:           'block w-full text-xs text-[#81A1C1] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-[#5E81AC]/20 file:text-[#88C0D0] hover:file:bg-[#5E81AC]/30',
    fileInputButton:     { base: 'file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-[#5E81AC]/20 file:text-[#88C0D0] hover:file:bg-[#5E81AC]/30', hasFile: 'file:bg-[#5E81AC]/30' },
    bodyEditor:          'w-full text-[11px] border border-[#4C566A] rounded-lg px-3 py-2.5 bg-[#3B4252] text-[#D8DEE9] placeholder-[#4C566A] focus:outline-none focus:ring-1 focus:ring-[#88C0D0] focus:border-[#88C0D0] font-mono resize-y transition-colors leading-relaxed',
    contentTypeSelector: 'text-[10px] font-mono text-[#4C566A] border border-[#4C566A] rounded px-2 py-0.5 bg-[#3B4252]',
    sendButton:          { base: 'shrink-0 px-4 rounded-lg text-xs font-semibold transition-all bg-[#5E81AC] hover:bg-[#81A1C1] active:scale-[0.98] text-[#ECEFF4] shadow-sm', loading: 'bg-[#434C5E] text-[#4C566A] cursor-not-allowed shadow-none', disabled: 'bg-[#434C5E] text-[#4C566A] cursor-not-allowed shadow-none' },
    responsePanel:       'h-full border-t border-[#4C566A] flex flex-col',
    responseStatus:      { base: 'text-[10px] rounded px-1.5 py-0.5 font-mono font-semibold border bg-[#3B4252] text-[#81A1C1] border-[#4C566A]', success: 'bg-[#A3BE8C]/15 text-[#A3BE8C] border-[#A3BE8C]/30', redirect: 'bg-[#88C0D0]/15 text-[#88C0D0] border-[#88C0D0]/30', clientError: 'bg-[#EBCB8B]/15 text-[#EBCB8B] border-[#EBCB8B]/30', serverError: 'bg-[#BF616A]/15 text-[#BF616A] border-[#BF616A]/30' },
    responseTime:        'text-[10px] text-[#4C566A] font-mono border border-[#4C566A] rounded px-1.5 py-0.5',
    responseSize:        'text-[10px] text-[#4C566A] font-mono',
    responseTabs:        'flex items-center gap-2 px-4 py-2 border-b border-[#4C566A] bg-[#3B4252]/30 shrink-0',
    responseTab:         { base: 'px-2.5 py-1 text-[10px] rounded font-medium transition-colors text-[#4C566A] hover:text-[#D8DEE9]', active: 'bg-[#434C5E] shadow-sm text-[#ECEFF4] border border-[#4C566A]' },
    responseBody:        'flex-1 overflow-auto bg-[#2E3440]',
    responseEmpty:       'shrink-0 border-t border-[#4C566A] h-10 flex items-center justify-center text-[10px] text-[#4C566A]',
    errorBanner:         'mx-5 mb-4 px-3 py-2 bg-[#BF616A]/15 border border-[#BF616A]/30 rounded-lg text-xs text-[#BF616A]',
  },

  authStatus: {
    sectionLabel:      'text-[10px] font-semibold uppercase tracking-wider text-[#4C566A] mb-3',
    emptyText:         'text-[10px] text-[#4C566A]',
    schemeRow:         'flex items-center justify-between py-2.5 px-3 rounded-lg border border-[#4C566A] bg-[#434C5E]/30',
    schemeName:        'text-[11px] font-mono text-[#D8DEE9]',
    schemeType:        'ml-1.5 text-[10px] text-[#4C566A]',
    authorizedBadge:   'text-[9px] text-[#A3BE8C] bg-[#A3BE8C]/10 border border-[#A3BE8C]/30 rounded px-1.5 py-0.5 font-semibold uppercase tracking-wide',
    unauthorizedBadge: 'text-[9px] text-[#4C566A] bg-[#434C5E] border border-[#4C566A] rounded px-1.5 py-0.5 uppercase tracking-wide',
  },

  bodyEditor: {
    fileInput:    'block w-full text-xs text-[#81A1C1] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-[#5E81AC]/20 file:text-[#88C0D0] hover:file:bg-[#5E81AC]/30',
    formatButton: 'absolute top-1.5 right-1.5 z-10 text-[10px] text-[#4C566A] hover:text-[#88C0D0] transition-colors px-1.5 py-0.5 rounded hover:bg-[#88C0D0]/10',
    textarea:     'w-full text-[11px] border border-[#4C566A] rounded-lg px-3 py-2.5 bg-[#3B4252] text-[#D8DEE9] placeholder-[#4C566A] focus:outline-none focus:ring-1 focus:ring-[#88C0D0] focus:border-[#88C0D0] font-mono resize-y transition-colors leading-relaxed',
  },

  paramLabel: {
    nameText:        'font-mono text-[11px] text-[#ECEFF4]',
    nameDeprecated:  'font-mono text-[11px] line-through text-[#4C566A]',
    locPath:         'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#D08770] bg-[#D08770]/15',
    locQuery:        'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#8FBCBB] bg-[#8FBCBB]/15',
    locHeader:       'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#81A1C1] bg-[#81A1C1]/15',
    locCookie:       'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#B48EAD] bg-[#B48EAD]/15',
    locForm:         'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#88C0D0] bg-[#88C0D0]/15',
    locDefault:      'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#81A1C1] bg-[#434C5E]',
    typeBadge:       'text-[9px] font-mono text-[#B48EAD] bg-[#B48EAD]/15 rounded px-1.5 py-0.5 leading-none',
    requiredBadge:   'text-[9px] font-semibold text-[#BF616A] bg-[#BF616A]/15 rounded px-1.5 py-0.5 leading-none',
    deprecatedBadge: 'text-[9px] font-semibold text-[#EBCB8B] bg-[#EBCB8B]/15 rounded px-1.5 py-0.5 leading-none',
    constraintBadge: 'text-[9px] font-mono text-[#4C566A] bg-[#434C5E] rounded px-1.5 py-0.5 leading-none',
    tooltipIcon:     'w-3.5 h-3.5 text-[#4C566A] cursor-help hover:text-[#D8DEE9] transition-colors',
    tooltipPopup:    'pointer-events-none absolute bottom-full right-0 mb-2 w-56 rounded-lg bg-[#2E3440] border border-[#4C566A] px-2.5 py-2 text-[10px] text-[#D8DEE9] leading-snug shadow-lg opacity-0 group-hover/tip:opacity-100 transition-opacity z-50',
  },

  responsePanel: {
    loadingState:  'shrink-0 border-t border-[#4C566A] h-16 flex items-center justify-center gap-2 text-xs text-[#4C566A] bg-[#3B4252]/30',
    emptyState:    'shrink-0 border-t border-[#4C566A] h-10 flex items-center justify-center',
    emptyText:     'text-[10px] text-[#4C566A]',
    container:     'h-full border-t border-[#4C566A] flex flex-col',
    tabBar:        'flex items-center gap-2 px-4 py-2 border-b border-[#4C566A] bg-[#3B4252]/30 shrink-0',
    tab:           { base: 'px-2.5 py-1 text-[10px] rounded font-medium transition-colors text-[#4C566A] hover:text-[#D8DEE9]', active: 'bg-[#434C5E] shadow-sm text-[#ECEFF4] border border-[#4C566A]' },
    tabDivider:    'w-px h-3 bg-[#4C566A] mx-1',
    headerCount:   'ml-0.5 text-[#4C566A]',
    copyButton:    { base: 'flex items-center gap-1 text-[10px] px-2 py-1 rounded hover:bg-[#434C5E] transition-colors text-[#4C566A] hover:text-[#D8DEE9]', copied: 'text-[#A3BE8C]' },
    statusNeutral: 'text-[10px] border rounded px-1.5 py-0.5 font-mono font-semibold text-[#81A1C1] bg-[#3B4252] border-[#4C566A]',
    statusSuccess: 'text-[10px] border rounded px-1.5 py-0.5 font-mono font-semibold text-[#A3BE8C] bg-[#A3BE8C]/15 border-[#A3BE8C]/30',
    statusError:   'text-[10px] border rounded px-1.5 py-0.5 font-mono font-semibold text-[#BF616A] bg-[#BF616A]/15 border-[#BF616A]/30',
    bodyContainer: 'flex-1 overflow-auto bg-[#2E3440]',
    bodyPre:       'text-[11px] p-3 text-[#D8DEE9] font-mono leading-relaxed',
    headersPre:    'text-[11px] p-3 text-[#81A1C1] font-mono leading-relaxed',
  },

  sendBar: {
    container:          'px-5 py-3 border-b border-[#4C566A] shrink-0 bg-[#3B4252]/30',
    urlBox:             'flex items-center gap-2 flex-1 min-w-0 bg-[#3B4252] rounded-lg px-2.5 py-2 border border-[#4C566A]',
    urlCode:            'text-[10px] text-[#81A1C1] leading-tight flex-1 min-w-0 break-all',
    sendButtonActive:   'shrink-0 px-4 rounded-lg text-xs font-semibold transition-all bg-[#5E81AC] hover:bg-[#81A1C1] active:scale-[0.98] text-[#ECEFF4] shadow-sm',
    sendButtonDisabled: 'shrink-0 px-4 rounded-lg text-xs font-semibold transition-all bg-[#434C5E] text-[#4C566A] cursor-not-allowed',
  },

  inputScalar: {
    input:        'w-full text-xs border border-[#4C566A] rounded-lg px-3 py-2 bg-[#3B4252] text-[#D8DEE9] placeholder-[#4C566A] focus:outline-none focus:ring-1 focus:ring-[#88C0D0] focus:border-[#88C0D0] transition-colors font-mono',
    inputInvalid: 'w-full text-xs border border-[#BF616A]/60 rounded-lg px-3 py-2 bg-[#3B4252] text-[#D8DEE9] placeholder-[#4C566A] focus:outline-none focus:ring-1 focus:ring-[#BF616A]/60 focus:border-[#BF616A]/60 transition-colors font-mono',
  },

  inputBoolean: {
    select:        'w-full text-xs border border-[#4C566A] rounded-lg px-3 py-2 bg-[#3B4252] text-[#D8DEE9] focus:outline-none focus:ring-1 focus:ring-[#88C0D0] focus:border-[#88C0D0] transition-colors font-mono',
    selectInvalid: 'w-full text-xs border border-[#BF616A]/60 rounded-lg px-3 py-2 bg-[#3B4252] text-[#D8DEE9] focus:outline-none focus:ring-1 focus:ring-[#BF616A]/60 focus:border-[#BF616A]/60 transition-colors font-mono',
  },

  inputEnum: {
    select:        'w-full text-xs border border-[#4C566A] rounded-lg px-3 py-2 bg-[#3B4252] text-[#D8DEE9] focus:outline-none focus:ring-1 focus:ring-[#88C0D0] focus:border-[#88C0D0] transition-colors font-mono',
    selectInvalid: 'w-full text-xs border border-[#BF616A]/60 rounded-lg px-3 py-2 bg-[#3B4252] text-[#D8DEE9] focus:outline-none focus:ring-1 focus:ring-[#BF616A]/60 focus:border-[#BF616A]/60 transition-colors font-mono',
  },

  inputFile: {
    input: 'block w-full text-xs text-[#81A1C1] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-[#5E81AC]/20 file:text-[#88C0D0] hover:file:bg-[#5E81AC]/30',
  },

  inputArray: {
    rowInput:        'flex-1 text-xs border border-[#4C566A] rounded-lg px-3 py-2 bg-[#3B4252] text-[#D8DEE9] placeholder-[#4C566A] focus:outline-none focus:ring-1 focus:ring-[#88C0D0] focus:border-[#88C0D0] transition-colors font-mono',
    rowInputInvalid: 'flex-1 text-xs border border-[#BF616A]/60 rounded-lg px-3 py-2 bg-[#3B4252] text-[#D8DEE9] placeholder-[#4C566A] focus:outline-none focus:ring-1 focus:ring-[#BF616A]/60 focus:border-[#BF616A]/60 transition-colors font-mono',
    rowIndex:        'text-[9px] text-[#4C566A] font-mono w-4 text-right shrink-0',
    removeButton:    'shrink-0 w-5 h-5 flex items-center justify-center rounded text-[#4C566A] hover:text-[#BF616A] hover:bg-[#BF616A]/15 disabled:opacity-0 transition-colors',
    addButton:       'flex items-center gap-1 text-[10px] text-[#88C0D0] hover:text-[#8FBCBB] transition-colors',
    hint:            'text-[9px] text-[#4C566A] font-mono',
  },

  inputMultiSelect: {
    trigger:        'w-full text-xs border border-[#4C566A] rounded-lg px-3 py-2 bg-[#3B4252] text-[#D8DEE9] focus:outline-none focus:ring-1 focus:ring-[#88C0D0] focus:border-[#88C0D0] transition-colors font-mono flex items-center justify-between text-left',
    triggerInvalid: 'w-full text-xs border border-[#BF616A]/60 rounded-lg px-3 py-2 bg-[#3B4252] text-[#D8DEE9] focus:outline-none focus:ring-1 focus:ring-[#BF616A]/60 focus:border-[#BF616A]/60 transition-colors font-mono flex items-center justify-between text-left',
    placeholder:    'text-[#4C566A]',
    dropdown:       'absolute z-20 mt-1 w-full rounded-lg border border-[#4C566A] bg-[#3B4252] shadow-lg py-1',
    dropdownItem:   'flex items-center gap-2 px-3 py-1.5 hover:bg-[#434C5E]/60 cursor-pointer',
    optionText:     'text-xs font-mono text-[#D8DEE9]',
  },

  inputObject: {
    textarea:        'w-full text-xs border border-[#4C566A] rounded-lg px-3 py-2 bg-[#3B4252] text-[#D8DEE9] placeholder-[#4C566A] focus:outline-none focus:ring-1 focus:ring-[#88C0D0] focus:border-[#88C0D0] transition-colors font-mono resize-y',
    textareaInvalid: 'w-full text-xs border border-[#BF616A]/60 rounded-lg px-3 py-2 bg-[#3B4252] text-[#D8DEE9] placeholder-[#4C566A] focus:outline-none focus:ring-1 focus:ring-[#BF616A]/60 focus:border-[#BF616A]/60 transition-colors font-mono resize-y',
  },

  detailPane: {
    spinner:      'w-5 h-5 animate-spin text-[#88C0D0]',
    errorIcon:    'w-10 h-10 rounded-full bg-[#BF616A]/15 flex items-center justify-center shrink-0 text-[#BF616A]',
    errorMessage: 'text-sm text-[#BF616A]',
    retryLink:    'text-xs text-[#4C566A] hover:text-[#D8DEE9] underline underline-offset-2',
    emptyIcon:    'w-10 h-10 rounded-full bg-[#3B4252] flex items-center justify-center text-[#4C566A]',
    emptyMessage: 'text-sm text-[#4C566A]',
  },

  verticalResizable: {
    handle: 'w-8 h-0.5 rounded-full bg-[#4C566A] group-hover:bg-[#88C0D0] transition-colors',
  },

  syntax: {
    key:     '#81A1C1',
    string:  '#A3BE8C',
    boolean: '#B48EAD',
    null:    '#4C566A',
    number:  '#EBCB8B',
  },

  paneHandle:  'border-l border-[#4C566A] group-hover:border-[#88C0D0] group-[.dragging]:border-[#81A1C1] transition-colors duration-150',
  fontFamily:  "'IBM Plex Sans', ui-sans-serif, system-ui, sans-serif",
  focusRing:   'focus:ring-2 focus:ring-[#88C0D0] focus:ring-offset-1',
  scrollbar:   { thumb: 'bg-[#4C566A]', thumbHover: 'bg-[#81A1C1]' },
};