/**
 * Parchment theme preset — warm cream backgrounds, dark ink text, and rust accents.
 * Inspired by handwritten notebooks and aged paper. Cozy, tactile, analog.
 * Palette: cream (#F5EFD7), ink (#2C2416), rust (#C4622D), warm tan borders (#D4C9A0).
 */
import type { AppTheme } from '../contract';

const methodBadgeBase = 'method-badge shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] rounded uppercase w-[36px] text-center';

export const parchmentTheme: AppTheme = {
  name: 'parchment',

  appRoot: {
    root:              'flex flex-col h-full overflow-hidden bg-[#F5EFD7]',
    navPane:           'shrink-0 bg-[#EDE6C8] overflow-y-auto flex flex-col',
    detailPane:        'flex-1 min-w-0 bg-[#F5EFD7] overflow-hidden',
    tryPane:           'shrink-0 bg-[#F5EFD7] overflow-hidden',
    shortcutsBackdrop: 'fixed inset-0 bg-[#2C2416]/40 flex items-center justify-center z-50',
    shortcutsPanel:    'bg-[#FAF6E8] rounded-xl shadow-xl w-72 mx-4 overflow-hidden border border-[#D4C9A0]',
    shortcutsHeader:   'flex items-center justify-between px-5 py-3.5 border-b border-[#D4C9A0]',
    shortcutsTitle:    'text-sm font-semibold text-[#2C2416]',
    shortcutsClose:    'text-[#8C7A5A] hover:text-[#2C2416] text-xl leading-none transition-colors',
    shortcutsRow:      'flex items-center justify-between py-1.5 border-b border-[#E3D9B8] last:border-0',
    shortcutsDesc:     'text-xs text-[#5C4A2A]',
    shortcutsKbd:      'text-[10px] font-mono bg-[#EDE6C8] text-[#C4622D] px-2 py-0.5 rounded border border-[#D4C9A0] shrink-0',
  },

  nav: {
    container:         'shrink-0 bg-[#EDE6C8] overflow-y-auto flex flex-col h-full',
    divider:           'mt-1 border-t border-[#D4C9A0]',
    searchWrapper:     'px-4 py-3 border-b border-[#D4C9A0] shrink-0',
    searchInput:       'w-full pl-7 pr-6 py-2 text-[11px] border border-[#D4C9A0] rounded-md bg-[#FAF6E8] text-[#2C2416] placeholder-[#8C7A5A] focus:outline-none focus:ring-1 focus:ring-[#C4622D] focus:border-[#C4622D] transition-colors',
    searchIcon:        'absolute left-2.5 top-1/2 -translate-y-1/2 w-3 h-3 text-[#8C7A5A] pointer-events-none',
    searchClearButton: 'absolute right-2 top-1/2 -translate-y-1/2 text-[#8C7A5A] hover:text-[#2C2416] leading-none text-sm',
    searchHint:        'absolute right-2 top-1/2 -translate-y-1/2 text-[9px] text-[#A89878] border border-[#D4C9A0] rounded px-1 font-mono pointer-events-none leading-none',
    loadingSpinner:    'w-5 h-5 animate-spin text-[#C4622D]',
    tabBar:            'flex gap-1 px-4 py-2 border-b border-[#D4C9A0]',
    tab:               { base: 'px-2.5 py-1 text-[11px] font-medium rounded transition-colors text-[#8C7A5A] hover:text-[#2C2416]', active: 'bg-[#FAF6E8] text-[#2C2416] border border-[#D4C9A0] shadow-sm' },
    tagHeader:         'w-full flex items-center justify-between px-4 py-2.5 text-[10px] font-semibold uppercase tracking-widest text-[#8C7A5A] hover:text-[#C4622D] transition-colors',
    tagChevron:        'w-3 h-3 transition-transform',
    tagCount:          'text-[10px] text-[#8C7A5A] font-mono',
    endpointItem:      { base: 'nav-endpoint w-full flex items-center gap-2.5 px-4 py-2 text-left transition-colors text-[#5C4A2A] hover:bg-[#D4C9A0]/40 hover:text-[#2C2416]', active: 'bg-[#D4C9A0]/60 text-[#2C2416]' },
    endpointPath:      'truncate text-[11px] font-mono',
    methodBadge:       { base: methodBadgeBase, get: 'bg-[#D5E4F0] text-[#2A5A8B]', post: 'bg-[#D5EDD0] text-[#3A6B30]', put: 'bg-[#F2E8C0] text-[#8B6914]', delete: 'bg-[#F2D5D5] text-[#8B2020]', patch: 'bg-[#F2DDD0] text-[#8B3A1A]', options: 'bg-[#E5DEC8] text-[#6B5A40]', head: 'bg-[#E5DEC8] text-[#6B5A40]' },
    schemaItem:        { base: 'w-full text-left gap-2.5 px-4 py-2 transition-colors hover:bg-[#D4C9A0]/40', active: 'bg-[#D4C9A0]/60' },
    schemaName:        { base: 'truncate text-[11px] font-mono text-[#5C4A2A]', active: 'text-[#2C2416]' },
    schemaTypeBadge:   'shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] rounded bg-[#F5E4D5] text-[#C4622D] uppercase',
    schemaDescription: 'mt-0.5 text-[10px] text-[#8C7A5A] truncate pl-[38px]',
    emptyState:        'text-[11px] text-[#8C7A5A]',
  },

  endpoint: {
    container:           'h-full flex flex-col',
    header:              'flex items-center gap-3 px-6 py-5 border-b border-[#D4C9A0] shrink-0 h-[50px]',
    methodBadge:         { base: methodBadgeBase, get: 'bg-[#D5E4F0] text-[#2A5A8B]', post: 'bg-[#D5EDD0] text-[#3A6B30]', put: 'bg-[#F2E8C0] text-[#8B6914]', delete: 'bg-[#F2D5D5] text-[#8B2020]', patch: 'bg-[#F2DDD0] text-[#8B3A1A]', options: 'bg-[#E5DEC8] text-[#6B5A40]', head: 'bg-[#E5DEC8] text-[#6B5A40]' },
    path:                'font-mono text-sm text-[#2C2416]',
    summary:             'text-sm text-[#2C2416] mb-2 font-medium',
    description:         'text-xs text-[#5C4A2A]',
    deprecated:          'ml-auto text-[10px] bg-[#F2E8C0] text-[#8B6914] border border-[#D4B84A] rounded px-2 py-0.5',
    paramSection:        'border border-[#D4C9A0] rounded-lg overflow-hidden',
    paramSectionTitle:   'text-xs font-semibold uppercase tracking-wider text-[#8C7A5A] mb-4',
    paramLocTitle:       'text-[10px] font-semibold uppercase tracking-wider text-[#8C7A5A] mb-3',
    paramRow:            'border-b border-[#E3D9B8] last:border-0 bg-[#FAF6E8] hover:bg-[#EDE6C8]/60 transition-colors',
    paramName:           'font-mono text-[11px] text-[#2C2416]',
    paramType:           'text-[10px] bg-[#EDE6C8] text-[#5C4A2A] rounded px-1.5 py-0.5 font-mono',
    paramRequired:       'text-[#8B2020] text-[9px] font-semibold ml-1',
    paramDescription:    'px-4 py-3 w-full text-xs text-[#5C4A2A]',
    mutedText:           'text-[#8C7A5A]',
    responseAccordion:   'border border-[#D4C9A0] rounded-lg overflow-hidden divide-y divide-[#D4C9A0]',
    responseHeader:      'w-full flex items-center gap-3 px-4 py-3.5 hover:bg-[#EDE6C8]/60 transition-colors text-left',
    responseStatusCode:  { base: 'text-xs font-mono font-semibold', success: 'text-[#3A6B30]', redirect: 'text-[#2A5A8B]', clientError: 'text-[#8B6914]', serverError: 'text-[#8B2020]' },
    responseDescription: 'text-xs text-[#5C4A2A] flex-1',
    bodySection:         'px-3 py-1.5 bg-[#EDE6C8] border-b border-[#D4C9A0] flex items-center gap-2',
    bodyContentType:     'text-[10px] text-[#8C7A5A] font-mono',
  },

  topBar: {
    container:              'relative flex items-center gap-4 px-6 h-16 border-b border-[#D4C9A0] bg-[#F5EFD7] shrink-0 z-10',
    specTitle:              'text-sm font-semibold text-[#2C2416] truncate',
    specVersion:            'text-[10px] text-[#8C7A5A] border border-[#D4C9A0] rounded-full px-1.5 py-px font-mono shrink-0 leading-tight',
    specDescription:        'text-[10px] text-[#8C7A5A] truncate leading-tight mt-px',
    noSpecIcon:             'w-7 h-7 rounded-lg bg-[#EDE6C8] flex items-center justify-center shrink-0',
    noSpecIconSvg:          'w-4 h-4 text-[#8C7A5A]',
    noSpecTitle:            'text-sm font-semibold text-[#8C7A5A]',
    divider:                'w-px h-5 bg-[#D4C9A0] mx-1 shrink-0',
    authButtonConfigured:   'flex items-center gap-1.5 text-xs rounded-md px-2.5 py-1.5 font-medium border transition-all shrink-0 text-[#3A6B30] bg-[#D5EDD0] border-[#A8C8A0] hover:bg-[#C0DDB8]',
    authButtonUnconfigured: 'flex items-center gap-1.5 text-xs rounded-md px-2.5 py-1.5 font-medium border transition-all shrink-0 text-[#5C4A2A] bg-[#FAF6E8] border-[#D4C9A0] hover:bg-[#EDE6C8] hover:border-[#C4622D]',
    neutralButton:          'flex items-center gap-1.5 text-xs rounded-md px-2.5 py-1.5 font-medium border transition-all shrink-0 text-[#5C4A2A] bg-[#FAF6E8] border-[#D4C9A0] hover:bg-[#EDE6C8] hover:border-[#C4622D]',
    loadButton:             'flex items-center gap-1.5 text-xs text-[#FAF6E8] bg-[#C4622D] hover:bg-[#A84E22] active:bg-[#8B3A18] rounded-md px-3 py-1.5 font-semibold transition-colors shrink-0 shadow-sm',
  },

  themePicker: {
    dropdown: 'bg-[#FAF6E8] border border-[#D4C9A0] rounded-xl shadow-xl py-1.5 overflow-hidden',
    item:     { base: 'w-full flex items-center gap-3 px-3 py-2 text-left hover:bg-[#EDE6C8] transition-colors', active: 'bg-[#EDE6C8]' },
    name:     'text-sm text-[#2C2416] font-medium flex-1',
    check:    'w-3.5 h-3.5 text-[#C4622D] shrink-0',
  },

  modal: {
    backdrop:    'fixed inset-0 bg-[#2C2416]/40 flex items-center justify-center z-50',
    container:   'bg-[#FAF6E8] rounded-xl shadow-xl w-full mx-4 overflow-hidden border border-[#D4C9A0]',
    header:      'flex items-center justify-between px-5 py-4 border-b border-[#D4C9A0]',
    closeButton: 'text-[#8C7A5A] hover:text-[#2C2416] text-xl leading-none',
    footer:      'px-5 py-3 bg-[#EDE6C8] border-t border-[#D4C9A0]',
  },

  loadModal: {
    title:        'text-sm font-semibold text-[#2C2416]',
    footerText:   'text-[10px] text-[#8C7A5A]',
    petstoreLink: 'text-xs text-[#2A5A8B] hover:underline',
    urlLabel:     'block text-xs font-medium text-[#5C4A2A] mb-1.5',
    urlInput:     'flex-1 text-xs border border-[#D4C9A0] rounded-md px-3 py-2 bg-[#FAF6E8] text-[#2C2416] placeholder-[#8C7A5A] focus:outline-none focus:ring-1 focus:ring-[#C4622D] focus:border-[#C4622D] transition-colors',
    dividerLine:  'flex-1 border-t border-[#D4C9A0]',
    dividerText:  'text-[10px] text-[#8C7A5A] uppercase tracking-wider',
    fileLabel:    'block text-xs font-medium text-[#5C4A2A] mb-1.5',
    fileDropZone: 'flex items-center justify-center gap-2 border-2 border-dashed border-[#D4C9A0] rounded-lg px-4 py-5 cursor-pointer hover:border-[#C4622D] hover:bg-[#F5E4D5]/40 transition-colors',
    fileDropIcon: 'w-4 h-4 text-[#8C7A5A]',
    fileDropText: 'text-xs text-[#5C4A2A]',
    errorBanner:  'text-xs text-[#8B2020] bg-[#F2D5D5] border border-[#C8A0A0] rounded-md px-3 py-2',
  },

  authModal: {
    tabBar:            'flex gap-1 px-4 py-2 bg-[#EDE6C8] border-b border-[#D4C9A0] overflow-x-auto',
    tabActive:         'px-3 py-1.5 text-[11px] font-medium rounded-md bg-[#FAF6E8] text-[#2C2416] border border-[#D4C9A0] flex items-center gap-1.5 shrink-0',
    tabInactive:       'px-3 py-1.5 text-[11px] font-medium rounded-md text-[#8C7A5A] hover:text-[#2C2416] transition-colors flex items-center gap-1.5 shrink-0',
    titleIcon:         'w-4 h-4 text-[#5C4A2A]',
    titleText:         'text-sm font-semibold text-[#2C2416]',
    closeButton:       'text-xs bg-[#2C2416] hover:bg-[#5C4A2A] text-[#FAF6E8] px-4 py-2 rounded-md font-medium transition-colors',
    schemeType:        'text-[10px] text-[#8C7A5A]',
    authorizedBadge:   'text-[9px] text-[#3A6B30] bg-[#D5EDD0] border border-[#A8C8A0] rounded px-1.5 py-0.5 font-semibold uppercase tracking-wide',
    schemeDescription: 'text-[10px] text-[#8C7A5A]',
    fieldLabel:        'block text-[10px] text-[#5C4A2A] mb-1',
    fieldLabelHint:    'text-[#8C7A5A] font-sans',
    input:             'w-full text-xs border border-[#D4C9A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] placeholder-[#A89878] focus:outline-none focus:ring-1 focus:ring-[#C4622D] focus:border-[#C4622D] font-mono',
    tokenWrapper:      'flex items-stretch border border-[#D4C9A0] rounded-lg overflow-hidden bg-[#FAF6E8] focus-within:ring-1 focus-within:ring-[#C4622D] focus-within:border-[#C4622D] transition-all',
    tokenPrefix:       'px-2.5 flex items-center text-[10px] text-[#8C7A5A] bg-[#EDE6C8] border-r border-[#D4C9A0] font-mono shrink-0 select-none',
    tokenField:        'flex-1 text-xs px-2.5 py-2 bg-[#FAF6E8] text-[#2C2416] placeholder-[#A89878] focus:outline-none font-mono min-w-0',
    saveButton:        'text-xs bg-[#C4622D] hover:bg-[#A84E22] text-[#FAF6E8] px-3 py-1.5 rounded-md font-semibold transition-colors',
    clearButton:       'text-xs border border-[#D4C9A0] text-[#5C4A2A] hover:border-[#C4622D] hover:text-[#2C2416] px-3 py-1.5 rounded-md font-medium transition-colors',
  },

  serverConfig: {
    chip: {
      base: 'flex items-center gap-1.5 text-[11px] font-mono px-2.5 py-1.5 rounded-lg border transition-colors shrink-0 text-[#5C4A2A] border-[#D4C9A0] bg-[#FAF6E8] hover:bg-[#EDE6C8] hover:border-[#C4622D]',
      open: 'bg-[#F5E4D5] text-[#C4622D] border-[#C4622D] hover:bg-[#F5E4D5] hover:border-[#C4622D]',
    },
    chipIcon:            'w-3 h-3 shrink-0 text-[#8C7A5A]',
    backdrop:            'fixed inset-0 bg-[#2C2416]/40 flex items-center justify-center z-[60]',
    popover:             'bg-[#FAF6E8] rounded-xl shadow-xl w-full max-w-sm mx-4 overflow-hidden border border-[#D4C9A0]',
    popoverHeader:       'flex items-center justify-between px-5 py-4 border-b border-[#D4C9A0]',
    headerIcon:          'w-4 h-4 text-[#5C4A2A]',
    headerTitle:         'text-sm font-semibold text-[#2C2416]',
    closeButton:         'text-[#8C7A5A] hover:text-[#2C2416] text-xl leading-none',
    sectionDivider:      'px-5 py-4 border-b border-[#D4C9A0]',
    sectionLabel:        'block text-[10px] font-semibold uppercase tracking-wider text-[#8C7A5A]',
    serverSelect:        'w-full text-[11px] font-mono border border-[#D4C9A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] focus:outline-none focus:ring-1 focus:ring-[#C4622D] cursor-pointer',
    variableName:        'text-[11px] font-mono font-medium text-[#2C2416]',
    variableDescription: 'text-[10px] text-[#8C7A5A] leading-tight mt-0.5',
    variableInput:       'text-[11px] font-mono border border-[#D4C9A0] rounded-lg px-2.5 py-1.5 bg-[#FAF6E8] text-[#2C2416] focus:outline-none focus:ring-1 focus:ring-[#C4622D] w-full',
    resolvedSection:     'px-5 py-4 bg-[#EDE6C8]',
    resolvedLabel:       'text-[10px] font-semibold uppercase tracking-wider text-[#8C7A5A] mb-1.5',
    resolvedValue:       'text-[11px] font-mono text-[#2C2416] break-all',
  },

  commandBar: {
    backdrop:       'fixed inset-0 bg-[#2C2416]/50 z-[60] flex items-start justify-center pt-[12vh]',
    container:      'bg-[#FAF6E8] rounded-xl shadow-2xl w-full max-w-lg mx-4 flex flex-col overflow-hidden border border-[#D4C9A0] max-h-[70vh]',
    searchRow:      'flex items-center gap-3 px-4 py-3 border-b border-[#D4C9A0] shrink-0',
    searchIcon:     'w-4 h-4 text-[#8C7A5A] shrink-0',
    input:          'flex-1 bg-transparent text-sm text-[#2C2416] placeholder-[#8C7A5A] outline-none',
    clearButton:    'text-[#8C7A5A] hover:text-[#2C2416] text-lg leading-none shrink-0 transition-colors',
    groupTitle:     'px-4 py-1.5 text-[10px] font-semibold uppercase tracking-widest text-[#8C7A5A] select-none',
    resultItem:     { base: 'w-full flex items-center gap-3 px-4 py-2.5 text-left transition-colors hover:bg-[#EDE6C8]', active: 'bg-[#F5E4D5] hover:bg-[#F5E4D5]' },
    actionIcon:     { base: 'w-7 h-7 rounded-md flex items-center justify-center shrink-0 bg-[#EDE6C8] text-[#5C4A2A]', active: 'bg-[#F5E4D5] text-[#C4622D]' },
    resultLabel:    'text-sm font-medium text-[#2C2416] truncate',
    resultSubtitle: 'text-xs text-[#8C7A5A] truncate mt-0.5',
    activeChevron:  'w-3.5 h-3.5 text-[#C4622D] shrink-0',
    emptyIcon:      'w-8 h-8 text-[#C4C0A8] mb-3',
    emptyText:      'text-sm text-[#8C7A5A]',
    footer:         'shrink-0 flex items-center gap-4 px-4 py-2 border-t border-[#D4C9A0] bg-[#EDE6C8]',
    shortcutText:   'flex items-center gap-1 text-[11px] text-[#8C7A5A]',
    shortcutBadge:  'font-mono text-[10px] bg-[#FAF6E8] border border-[#D4C9A0] rounded px-1 py-px',
    specTitle:      'ml-auto text-[11px] text-[#C4C0A8] truncate',
    highlightMark:  'bg-[#F2E8C0] text-inherit not-italic rounded-sm',
  },

  schema: {
    tabBar:       'flex gap-1 px-3 py-2 bg-[#EDE6C8] border-b border-[#D4C9A0]',
    tabActive:    'px-3 py-1 text-[11px] font-medium rounded-md bg-[#FAF6E8] text-[#2C2416] border border-[#D4C9A0]',
    tabInactive:  'px-3 py-1 text-[11px] font-medium rounded-md text-[#8C7A5A] hover:text-[#2C2416] transition-colors',
    description:  'px-4 pt-3 pb-0 text-[11px] text-[#5C4A2A] leading-relaxed',
    exampleBlock: 'text-[11px] bg-[#EDE6C8] rounded-md p-3 overflow-x-auto text-[#2C2416] font-mono leading-relaxed',
  },

  schemaNode: {
    name:          'font-mono text-[11px] text-[#2C2416]',
    typeBadge:     'text-[10px] rounded px-1.5 py-0.5 font-mono',
    nullableBadge: 'text-[9px] bg-[#EDE6C8] text-[#8C7A5A] rounded px-1 font-mono',
    constraint:    'text-[9px] font-mono text-[#8C7A5A]',
    enumValue:     'text-[9px] text-[#8C7A5A] font-mono',
    description:   'text-[11px] text-[#5C4A2A] mt-0.5 leading-relaxed',
    enumKey:       'font-mono text-[#2C2416]',
    enumDesc:      'text-[#8C7A5A]',
    nestedBorder:  'border-l-2 border-[#D4C9A0] ml-3 pl-3 mt-0.5',
    typeBadgeColors: {
      string:  'bg-[#D5EDD0] text-[#3A6B30]',
      integer: 'bg-[#D5E4F0] text-[#2A5A8B]',
      number:  'bg-[#D5E4F0] text-[#2A5A8B]',
      boolean: 'bg-[#EDD5F0] text-[#7B3A8B]',
      object:  'bg-[#F2E8C0] text-[#8B6914]',
      array:   'bg-[#D5F0EE] text-[#2A7B78]',
      default: 'bg-[#EDE6C8] text-[#5C4A2A]',
    },
  },

  schemaDetail: {
    header:      'flex items-center gap-3 px-6 py-5 border-b border-[#D4C9A0] shrink-0',
    typeBadge:   'text-[9px] font-bold font-mono px-[5px] py-[2px] rounded uppercase',
    schemaName:  'font-mono text-sm text-[#2C2416]',
    description: 'text-sm text-[#5C4A2A] mb-6 leading-relaxed',
    sectionLabel:'text-xs font-semibold uppercase tracking-wider text-[#8C7A5A] mb-4',
    schemaBox:   'border border-[#D4C9A0] rounded-lg overflow-hidden bg-[#FAF6E8]',
    typeBadgeColors: {
      string:  'bg-[#D5EDD0] text-[#3A6B30]',
      integer: 'bg-[#D5E4F0] text-[#2A5A8B]',
      number:  'bg-[#D5E4F0] text-[#2A5A8B]',
      boolean: 'bg-[#EDD5F0] text-[#7B3A8B]',
      object:  'bg-[#F2E8C0] text-[#8B6914]',
      array:   'bg-[#D5F0EE] text-[#2A7B78]',
      default: 'bg-[#EDE6C8] text-[#5C4A2A]',
    },
  },

  playground: {
    container:           'h-full flex flex-col bg-[#F5EFD7]',
    header:              'flex items-center gap-2 px-5 border-b border-[#D4C9A0] shrink-0 h-[50px]',
    headerTitle:         'text-xs font-semibold text-[#2C2416]',
    emptyState:          'h-full flex flex-col items-center justify-center text-center px-6 gap-3 bg-[#F5EFD7]',
    emptyIconWrapper:    'w-10 h-10 rounded-full bg-[#EDE6C8] flex items-center justify-center',
    emptyIcon:           'w-5 h-5 text-[#8C7A5A]',
    emptyText:           'text-sm text-[#8C7A5A]',
    inputLabel:          'text-[10px] font-semibold uppercase tracking-wider text-[#8C7A5A] mb-3',
    textInput:           'w-full text-xs border border-[#D4C9A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] placeholder-[#A89878] focus:outline-none focus:ring-1 focus:ring-[#C4622D] focus:border-[#C4622D] transition-colors font-mono',
    selectInput:         'w-full text-xs border border-[#D4C9A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] focus:outline-none focus:ring-1 focus:ring-[#C4622D] cursor-pointer transition-colors',
    fileInput:           'block w-full text-xs text-[#5C4A2A] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-[#F5E4D5] file:text-[#C4622D] hover:file:bg-[#EECFBF]',
    fileInputButton:     { base: 'file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-[#F5E4D5] file:text-[#C4622D] hover:file:bg-[#EECFBF]', hasFile: 'file:bg-[#EECFBF]' },
    bodyEditor:          'w-full text-[11px] border border-[#D4C9A0] rounded-lg px-3 py-2.5 bg-[#FAF6E8] text-[#2C2416] placeholder-[#A89878] focus:outline-none focus:ring-1 focus:ring-[#C4622D] focus:border-[#C4622D] font-mono resize-y transition-colors leading-relaxed',
    contentTypeSelector: 'text-[10px] font-mono text-[#8C7A5A] border border-[#D4C9A0] rounded px-2 py-0.5 bg-[#EDE6C8]',
    sendButton:          { base: 'shrink-0 px-4 rounded-lg text-xs font-semibold transition-all bg-[#C4622D] hover:bg-[#A84E22] active:scale-[0.98] text-[#FAF6E8] shadow-sm', loading: 'bg-[#EDE6C8] text-[#8C7A5A] cursor-not-allowed shadow-none', disabled: 'bg-[#EDE6C8] text-[#8C7A5A] cursor-not-allowed shadow-none' },
    responsePanel:       'h-full border-t border-[#D4C9A0] flex flex-col',
    responseStatus:      { base: 'text-[10px] rounded px-1.5 py-0.5 font-mono font-semibold border bg-[#EDE6C8] text-[#5C4A2A] border-[#D4C9A0]', success: 'bg-[#D5EDD0] text-[#3A6B30] border-[#A8C8A0]', redirect: 'bg-[#D5E4F0] text-[#2A5A8B] border-[#A0B8D0]', clientError: 'bg-[#F2E8C0] text-[#8B6914] border-[#D4B84A]', serverError: 'bg-[#F2D5D5] text-[#8B2020] border-[#C8A0A0]' },
    responseTime:        'text-[10px] text-[#8C7A5A] font-mono border border-[#D4C9A0] rounded px-1.5 py-0.5',
    responseSize:        'text-[10px] text-[#8C7A5A] font-mono',
    responseTabs:        'flex items-center gap-2 px-4 py-2 border-b border-[#D4C9A0] bg-[#EDE6C8]/60 shrink-0',
    responseTab:         { base: 'px-2.5 py-1 text-[10px] rounded font-medium transition-colors text-[#8C7A5A] hover:text-[#2C2416]', active: 'bg-[#FAF6E8] shadow-sm text-[#2C2416] border border-[#D4C9A0]' },
    responseBody:        'flex-1 overflow-auto bg-[#FAF6E8]',
    responseEmpty:       'shrink-0 border-t border-[#D4C9A0] h-10 flex items-center justify-center text-[10px] text-[#C4C0A8]',
    errorBanner:         'mx-5 mb-4 px-3 py-2 bg-[#F2D5D5] border border-[#C8A0A0] rounded-lg text-xs text-[#8B2020]',
  },

  authStatus: {
    sectionLabel:      'text-[10px] font-semibold uppercase tracking-wider text-[#8C7A5A] mb-3',
    emptyText:         'text-[10px] text-[#8C7A5A]',
    schemeRow:         'flex items-center justify-between py-2.5 px-3 rounded-lg border border-[#D4C9A0] bg-[#EDE6C8]/60',
    schemeName:        'text-[11px] font-mono text-[#2C2416]',
    schemeType:        'ml-1.5 text-[10px] text-[#8C7A5A]',
    authorizedBadge:   'text-[9px] text-[#3A6B30] bg-[#D5EDD0] border border-[#A8C8A0] rounded px-1.5 py-0.5 font-semibold uppercase tracking-wide',
    unauthorizedBadge: 'text-[9px] text-[#8C7A5A] bg-[#EDE6C8] border border-[#D4C9A0] rounded px-1.5 py-0.5 uppercase tracking-wide',
  },

  bodyEditor: {
    fileInput:    'block w-full text-xs text-[#5C4A2A] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-[#F5E4D5] file:text-[#C4622D] hover:file:bg-[#EECFBF]',
    formatButton: 'absolute top-1.5 right-1.5 z-10 text-[10px] text-[#8C7A5A] hover:text-[#C4622D] transition-colors px-1.5 py-0.5 rounded hover:bg-[#F5E4D5]',
    textarea:     'w-full text-[11px] border border-[#D4C9A0] rounded-lg px-3 py-2.5 bg-[#FAF6E8] text-[#2C2416] placeholder-[#A89878] focus:outline-none focus:ring-1 focus:ring-[#C4622D] focus:border-[#C4622D] font-mono resize-y transition-colors leading-relaxed',
  },

  paramLabel: {
    nameText:        'font-mono text-[11px] text-[#2C2416]',
    nameDeprecated:  'font-mono text-[11px] line-through text-[#A89878]',
    locPath:         'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#8B3A1A] bg-[#F2DDD0]',
    locQuery:        'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#2A7B78] bg-[#D5F0EE]',
    locHeader:       'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#2A5A8B] bg-[#D5E4F0]',
    locCookie:       'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#7B3A8B] bg-[#EDD5F0]',
    locForm:         'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#3A6B30] bg-[#D5EDD0]',
    locDefault:      'text-[9px] font-mono rounded px-1.5 py-0.5 leading-none text-[#5C4A2A] bg-[#EDE6C8]',
    typeBadge:       'text-[9px] font-mono text-[#7B3A8B] bg-[#EDD5F0] rounded px-1.5 py-0.5 leading-none',
    requiredBadge:   'text-[9px] font-semibold text-[#8B2020] bg-[#F2D5D5] rounded px-1.5 py-0.5 leading-none',
    deprecatedBadge: 'text-[9px] font-semibold text-[#8B6914] bg-[#F2E8C0] rounded px-1.5 py-0.5 leading-none',
    constraintBadge: 'text-[9px] font-mono text-[#5C4A2A] bg-[#EDE6C8] rounded px-1.5 py-0.5 leading-none',
    tooltipIcon:     'w-3.5 h-3.5 text-[#8C7A5A] cursor-help hover:text-[#5C4A2A] transition-colors',
    tooltipPopup:    'pointer-events-none absolute bottom-full right-0 mb-2 w-56 rounded-lg bg-[#2C2416] px-2.5 py-2 text-[10px] text-[#EDE6C8] leading-snug shadow-lg opacity-0 group-hover/tip:opacity-100 transition-opacity z-50',
  },

  responsePanel: {
    loadingState:  'shrink-0 border-t border-[#D4C9A0] h-16 flex items-center justify-center gap-2 text-xs text-[#8C7A5A] bg-[#EDE6C8]/50',
    emptyState:    'shrink-0 border-t border-[#D4C9A0] h-10 flex items-center justify-center',
    emptyText:     'text-[10px] text-[#C4C0A8]',
    container:     'h-full border-t border-[#D4C9A0] flex flex-col',
    tabBar:        'flex items-center gap-2 px-4 py-2 border-b border-[#D4C9A0] bg-[#EDE6C8]/60 shrink-0',
    tab:           { base: 'px-2.5 py-1 text-[10px] rounded font-medium transition-colors text-[#8C7A5A] hover:text-[#2C2416]', active: 'bg-[#FAF6E8] shadow-sm text-[#2C2416] border border-[#D4C9A0]' },
    tabDivider:    'w-px h-3 bg-[#D4C9A0] mx-1',
    headerCount:   'ml-0.5 text-[#C4C0A8]',
    copyButton:    { base: 'flex items-center gap-1 text-[10px] px-2 py-1 rounded hover:bg-[#EDE6C8] transition-colors text-[#8C7A5A] hover:text-[#2C2416]', copied: 'text-[#3A6B30]' },
    statusNeutral: 'text-[10px] border rounded px-1.5 py-0.5 font-mono font-semibold text-[#5C4A2A] bg-[#EDE6C8] border-[#D4C9A0]',
    statusSuccess: 'text-[10px] border rounded px-1.5 py-0.5 font-mono font-semibold text-[#3A6B30] bg-[#D5EDD0] border-[#A8C8A0]',
    statusError:   'text-[10px] border rounded px-1.5 py-0.5 font-mono font-semibold text-[#8B2020] bg-[#F2D5D5] border-[#C8A0A0]',
    bodyContainer: 'flex-1 overflow-auto bg-[#FAF6E8]',
    bodyPre:       'text-[11px] p-3 text-[#2C2416] font-mono leading-relaxed',
    headersPre:    'text-[11px] p-3 text-[#5C4A2A] font-mono leading-relaxed',
  },

  sendBar: {
    container:          'px-5 py-3 border-b border-[#D4C9A0] shrink-0 bg-[#EDE6C8]/50',
    urlBox:             'flex items-center gap-2 flex-1 min-w-0 bg-[#FAF6E8] rounded-lg px-2.5 py-2 border border-[#D4C9A0]',
    urlCode:            'text-[10px] text-[#5C4A2A] leading-tight flex-1 min-w-0 break-all',
    sendButtonActive:   'shrink-0 px-4 rounded-lg text-xs font-semibold transition-all bg-[#C4622D] hover:bg-[#A84E22] active:scale-[0.98] text-[#FAF6E8] shadow-sm',
    sendButtonDisabled: 'shrink-0 px-4 rounded-lg text-xs font-semibold transition-all bg-[#EDE6C8] text-[#A89878] cursor-not-allowed',
  },

  inputScalar: {
    input:        'w-full text-xs border border-[#D4C9A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] placeholder-[#A89878] focus:outline-none focus:ring-1 focus:ring-[#C4622D] focus:border-[#C4622D] transition-colors font-mono',
    inputInvalid: 'w-full text-xs border border-[#C8A0A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] placeholder-[#A89878] focus:outline-none focus:ring-1 focus:ring-[#8B2020] focus:border-[#8B2020] transition-colors font-mono',
  },

  inputBoolean: {
    select:        'w-full text-xs border border-[#D4C9A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] focus:outline-none focus:ring-1 focus:ring-[#C4622D] focus:border-[#C4622D] transition-colors font-mono',
    selectInvalid: 'w-full text-xs border border-[#C8A0A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] focus:outline-none focus:ring-1 focus:ring-[#8B2020] focus:border-[#8B2020] transition-colors font-mono',
  },

  inputEnum: {
    select:        'w-full text-xs border border-[#D4C9A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] focus:outline-none focus:ring-1 focus:ring-[#C4622D] focus:border-[#C4622D] transition-colors font-mono',
    selectInvalid: 'w-full text-xs border border-[#C8A0A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] focus:outline-none focus:ring-1 focus:ring-[#8B2020] focus:border-[#8B2020] transition-colors font-mono',
  },

  inputFile: {
    input: 'block w-full text-xs text-[#5C4A2A] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-medium file:bg-[#F5E4D5] file:text-[#C4622D] hover:file:bg-[#EECFBF]',
  },

  inputArray: {
    rowInput:        'flex-1 text-xs border border-[#D4C9A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] placeholder-[#A89878] focus:outline-none focus:ring-1 focus:ring-[#C4622D] focus:border-[#C4622D] transition-colors font-mono',
    rowInputInvalid: 'flex-1 text-xs border border-[#C8A0A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] placeholder-[#A89878] focus:outline-none focus:ring-1 focus:ring-[#8B2020] focus:border-[#8B2020] transition-colors font-mono',
    rowIndex:        'text-[9px] text-[#C4C0A8] font-mono w-4 text-right shrink-0',
    removeButton:    'shrink-0 w-5 h-5 flex items-center justify-center rounded text-[#C4C0A8] hover:text-[#8B2020] hover:bg-[#F2D5D5] disabled:opacity-0 transition-colors',
    addButton:       'flex items-center gap-1 text-[10px] text-[#C4622D] hover:text-[#A84E22] transition-colors',
    hint:            'text-[9px] text-[#C4C0A8] font-mono',
  },

  inputMultiSelect: {
    trigger:        'w-full text-xs border border-[#D4C9A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] focus:outline-none focus:ring-1 focus:ring-[#C4622D] focus:border-[#C4622D] transition-colors font-mono flex items-center justify-between text-left',
    triggerInvalid: 'w-full text-xs border border-[#C8A0A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] focus:outline-none focus:ring-1 focus:ring-[#8B2020] focus:border-[#8B2020] transition-colors font-mono flex items-center justify-between text-left',
    placeholder:    'text-[#A89878]',
    dropdown:       'absolute z-20 mt-1 w-full rounded-lg border border-[#D4C9A0] bg-[#FAF6E8] shadow-lg py-1',
    dropdownItem:   'flex items-center gap-2 px-3 py-1.5 hover:bg-[#EDE6C8] cursor-pointer',
    optionText:     'text-xs font-mono text-[#2C2416]',
  },

  inputObject: {
    textarea:        'w-full text-xs border border-[#D4C9A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] placeholder-[#A89878] focus:outline-none focus:ring-1 focus:ring-[#C4622D] focus:border-[#C4622D] transition-colors font-mono resize-y',
    textareaInvalid: 'w-full text-xs border border-[#C8A0A0] rounded-lg px-3 py-2 bg-[#FAF6E8] text-[#2C2416] placeholder-[#A89878] focus:outline-none focus:ring-1 focus:ring-[#8B2020] focus:border-[#8B2020] transition-colors font-mono resize-y',
  },

  detailPane: {
    spinner:      'w-5 h-5 animate-spin text-[#C4622D]',
    errorIcon:    'w-10 h-10 rounded-full bg-[#F2D5D5] flex items-center justify-center shrink-0 text-[#8B2020]',
    errorMessage: 'text-sm text-[#8B2020]',
    retryLink:    'text-xs text-[#8C7A5A] hover:text-[#2C2416] underline underline-offset-2',
    emptyIcon:    'w-10 h-10 rounded-full bg-[#EDE6C8] flex items-center justify-center text-[#8C7A5A]',
    emptyMessage: 'text-sm text-[#8C7A5A]',
  },

  verticalResizable: {
    handle: 'w-8 h-0.5 rounded-full bg-[#D4C9A0] group-hover:bg-[#C4622D] transition-colors',
  },

  syntax: {
    key:     '#2A5A8B',
    string:  '#3A6B30',
    boolean: '#7B3A8B',
    null:    '#8C7A5A',
    number:  '#8B6914',
  },

  paneHandle:  'bg-[#D4C9A0] group-hover:bg-[#C4622D] group-hover:w-0.5 group-[.dragging]:bg-[#A84E22] group-[.dragging]:w-0.5',
  fontFamily:  "'Georgia', 'Palatino Linotype', ui-serif, serif",
  focusRing:   'focus:ring-2 focus:ring-[#C4622D] focus:ring-offset-1',
  scrollbar:   { thumb: 'bg-[#D4C9A0]', thumbHover: 'bg-[#C4B888]' },
};