/**
 * Terminal theme preset — green phosphor on near-black.
 * Monospace everywhere, zero border radius, outlined method badges,
 * and a classic CRT color palette: #33cc33 text on #030a03 background
 * with #00ff41 as the interactive accent.
 */
import type { AppTheme } from '../contract';

// Bordered, square method badges — no rounding.
const methodBadgeBase = 'method-badge shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] rounded-none uppercase w-[36px] text-center border';

export const terminalTheme: AppTheme = {
  name: 'terminal',
  swatches: ['#030a03', '#00ff41', '#33cc33'],
  fontFamily: "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace",

  appRoot: {
    root:              'flex flex-col h-full overflow-hidden bg-[#030a03]',
    navPane:           'shrink-0 bg-[#000500] overflow-y-auto flex flex-col',
    detailPane:        'flex-1 min-w-0 bg-[#030a03] overflow-hidden',
    tryPane:           'shrink-0 bg-[#030a03] overflow-hidden',
    shortcutsBackdrop: 'fixed inset-0 bg-black/80 flex items-center justify-center z-50',
    shortcutsPanel:    'bg-[#0a140a] rounded-none border border-[#1e4a1e] shadow-xl shadow-black/50 w-72 mx-4 overflow-hidden',
    shortcutsHeader:   'flex items-center justify-between px-5 py-3.5 border-b border-[#1e4a1e]',
    shortcutsTitle:    'text-sm font-mono font-bold text-[#55ee55] uppercase tracking-wider',
    shortcutsClose:    'text-[#26932a] hover:text-[#33cc33] text-xl leading-none transition-colors font-mono',
    shortcutsRow:      'flex items-center justify-between py-1.5 border-b border-[#112a11] last:border-0',
    shortcutsDesc:     'text-xs font-mono text-[#33cc33]',
    shortcutsKbd:      'text-[10px] font-mono bg-[#0f200f] text-[#00ff41] px-2 py-0.5 rounded-none border border-[#1e4a1e] shrink-0',
  },

  nav: {
    container:         'shrink-0 bg-[#000500] overflow-y-auto flex flex-col h-full',
    divider:           'mt-1 border-t border-[#112a11]',
    searchWrapper:     'px-4 py-3 border-b border-[#1e4a1e] shrink-0',
    searchInput:       'w-full pl-7 pr-6 py-2 text-[11px] font-mono border border-[#1e4a1e] rounded-none bg-[#050e05] text-[#33cc33] placeholder-[#1a6b1a] focus:outline-none focus:border-[#33ff33] transition-colors',
    searchIcon:        'absolute left-2.5 top-1/2 -translate-y-1/2 w-3 h-3 text-[#1a6b1a] pointer-events-none',
    searchClearButton: 'absolute right-2 top-1/2 -translate-y-1/2 text-[#1a6b1a] hover:text-[#33cc33] leading-none text-sm font-mono',
    searchHint:        'absolute right-2 top-1/2 -translate-y-1/2 text-[9px] font-mono text-[#1a6b1a] border border-[#1e4a1e] rounded-none px-1 pointer-events-none leading-none',
    loadingSpinner:    'w-5 h-5 animate-spin text-[#33ff33]',
    tabBar:            'flex gap-1 px-4 py-2 border-b border-[#1e4a1e]',
    tab:               { base: 'px-2.5 py-1 text-[11px] font-mono rounded-none transition-colors text-[#1a6b1a] hover:text-[#33cc33] uppercase tracking-wider', active: 'bg-[#0f200f] text-[#55ee55] border border-[#1e4a1e]' },
    tagHeader:         'w-full flex items-center justify-between px-4 py-2.5 text-[10px] font-mono font-bold uppercase tracking-widest text-[#1a6b1a] hover:text-[#33ff33] transition-colors',
    tagChevron:        'w-3 h-3 transition-transform',
    tagCount:          'text-[10px] font-mono text-[#1a6b1a]',
    endpointItem:      { base: 'nav-endpoint w-full flex items-center gap-2.5 px-4 py-2 text-left transition-colors font-mono text-[#26932a] hover:text-[#33cc33] hover:bg-[#0a140a]', active: 'bg-[#0f200f] text-[#55ee55]' },
    endpointPath:      'truncate text-[11px] font-mono',
    methodBadge:       { base: methodBadgeBase, get: 'border-[#00ccff]/50 text-[#00ccff] bg-[#001e2a]', post: 'border-[#33ff33]/50 text-[#33ff33] bg-[#052a05]', put: 'border-[#ffb000]/50 text-[#ffb000] bg-[#1e1000]', delete: 'border-[#ff5555]/50 text-[#ff5555] bg-[#1e0000]', patch: 'border-[#cc88ff]/50 text-[#cc88ff] bg-[#1a0030]', options: 'border-[#1e4a1e] text-[#26932a] bg-transparent', head: 'border-[#1e4a1e] text-[#26932a] bg-transparent' },
    schemaItem:        { base: 'w-full text-left gap-2.5 px-4 py-2 transition-colors hover:bg-[#0a140a] font-mono', active: 'bg-[#0f200f]' },
    schemaName:        { base: 'truncate text-[11px] font-mono text-[#26932a]', active: 'text-[#55ee55]' },
    schemaTypeBadge:   'shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] rounded-none border border-[#cc88ff]/40 text-[#cc88ff] bg-[#1a0030] uppercase',
    schemaDescription: 'mt-0.5 text-[10px] font-mono text-[#1a6b1a] truncate pl-[38px]',
    emptyState:        'text-[11px] font-mono text-[#1a6b1a]',
  },

  endpoint: {
    container:           'h-full flex flex-col',
    header:              'flex items-center gap-3 px-6 py-5 border-b border-[#1e4a1e] shrink-0 h-[50px]',
    methodBadge:         { base: methodBadgeBase, get: 'border-[#00ccff]/50 text-[#00ccff] bg-[#001e2a]', post: 'border-[#33ff33]/50 text-[#33ff33] bg-[#052a05]', put: 'border-[#ffb000]/50 text-[#ffb000] bg-[#1e1000]', delete: 'border-[#ff5555]/50 text-[#ff5555] bg-[#1e0000]', patch: 'border-[#cc88ff]/50 text-[#cc88ff] bg-[#1a0030]', options: 'border-[#1e4a1e] text-[#26932a] bg-transparent', head: 'border-[#1e4a1e] text-[#26932a] bg-transparent' },
    path:                'font-mono text-sm text-[#55ee55] font-bold',
    summary:             'text-sm font-mono text-[#33cc33] mb-2 font-bold',
    description:         'text-xs font-mono text-[#26932a]',
    deprecated:          'ml-auto text-[10px] font-mono bg-[#1e1000] text-[#ffb000] border border-[#ffb000]/40 rounded-none px-2 py-0.5',
    paramSection:        'border border-[#1e4a1e] rounded-none overflow-hidden',
    paramSectionTitle:   'text-xs font-mono font-bold uppercase tracking-wider text-[#1a6b1a] mb-4',
    paramLocTitle:       'text-[10px] font-mono font-bold uppercase tracking-wider text-[#1a6b1a] mb-3',
    paramRow:            'border-b border-[#112a11] last:border-0 hover:bg-[#0a140a] transition-colors',
    paramName:           'font-mono text-[11px] text-[#55ee55] font-bold',
    paramType:           'text-[10px] font-mono bg-[#0f200f] text-[#33cc33] rounded-none px-1.5 py-0.5 border border-[#1e4a1e]',
    paramRequired:       'text-[#ff5555] text-[9px] font-mono font-bold ml-1',
    paramDescription:    'px-4 py-3 w-full text-xs font-mono text-[#26932a]',
    mutedText:           'font-mono text-[#1a6b1a]',
    responseAccordion:   'border border-[#1e4a1e] rounded-none overflow-hidden divide-y divide-[#1e4a1e]',
    responseHeader:      'w-full flex items-center gap-3 px-4 py-3.5 hover:bg-[#0a140a] transition-colors text-left',
    responseStatusCode:  { base: 'text-xs font-mono font-bold', success: 'text-[#33ff33]', redirect: 'text-[#00ccff]', clientError: 'text-[#ffb000]', serverError: 'text-[#ff5555]' },
    responseDescription: 'text-xs font-mono text-[#26932a] flex-1',
    bodySection:         'px-3 py-1.5 bg-[#050e05] border-b border-[#1e4a1e] flex items-center gap-2',
    bodyContentType:     'text-[10px] font-mono text-[#1a6b1a]',
  },

  topBar: {
    container:              'relative flex items-center gap-4 px-6 h-16 border-b border-[#1e4a1e] bg-[#000500] shrink-0 z-10',
    specTitle:              'text-sm font-mono font-bold text-[#55ee55] truncate uppercase tracking-wide',
    specVersion:            'text-[10px] font-mono text-[#1a6b1a] border border-[#1e4a1e] rounded-none px-1.5 py-px shrink-0 leading-tight',
    specDescription:        'text-[10px] font-mono text-[#1a6b1a] truncate leading-tight mt-px',
    noSpecIcon:             'w-7 h-7 rounded-none border border-[#1e4a1e] flex items-center justify-center shrink-0',
    noSpecIconSvg:          'w-4 h-4 text-[#1a6b1a]',
    noSpecTitle:            'text-sm font-mono font-bold text-[#1a6b1a] uppercase tracking-wide',
    divider:                'w-px h-5 bg-[#1e4a1e] mx-1 shrink-0',
    authButtonConfigured:   'flex items-center gap-1.5 text-xs font-mono rounded-none px-2.5 py-1.5 font-bold border transition-all shrink-0 text-[#33ff33] bg-[#052a05] border-[#33ff33]/50 hover:bg-[#0f200f] uppercase tracking-wide',
    authButtonUnconfigured: 'flex items-center gap-1.5 text-xs font-mono rounded-none px-2.5 py-1.5 font-medium border transition-all shrink-0 text-[#26932a] bg-transparent border-[#1e4a1e] hover:border-[#33ff33] hover:text-[#33cc33] uppercase tracking-wide',
    neutralButton:          'flex items-center gap-1.5 text-xs font-mono rounded-none px-2.5 py-1.5 font-medium border transition-all shrink-0 text-[#26932a] bg-transparent border-[#1e4a1e] hover:border-[#33ff33] hover:text-[#33cc33] uppercase tracking-wide',
    loadButton:             'flex items-center gap-1.5 text-xs font-mono text-[#000000] bg-[#00ff41] hover:bg-[#33ff33] active:bg-[#00cc33] rounded-none px-3 py-1.5 font-bold transition-colors shrink-0 uppercase tracking-wide',
  },

  themePicker: {
    dropdown: 'bg-[#0a140a] border border-[#1e4a1e] rounded-none shadow-xl shadow-black/60 py-1 overflow-hidden',
    item:     { base: 'w-full flex items-center gap-3 px-3 py-2 text-left hover:bg-[#0f200f] transition-colors font-mono', active: 'bg-[#0f200f] border-l-2 border-[#00ff41]' },
    name:     'text-sm font-mono text-[#33cc33] flex-1',
    check:    'w-3.5 h-3.5 text-[#00ff41] shrink-0',
  },

  modal: {
    backdrop:    'fixed inset-0 bg-black/80 flex items-center justify-center z-50',
    container:   'bg-[#0a140a] rounded-none border border-[#1e4a1e] shadow-xl shadow-black/50 w-full mx-4 overflow-hidden',
    header:      'flex items-center justify-between px-5 py-4 border-b border-[#1e4a1e]',
    closeButton: 'text-[#26932a] hover:text-[#33cc33] text-xl leading-none font-mono',
    footer:      'px-5 py-3 bg-[#050e05] border-t border-[#1e4a1e]',
  },

  loadModal: {
    title:        'text-sm font-mono font-bold text-[#55ee55] uppercase tracking-wide',
    footerText:   'text-[10px] font-mono text-[#1a6b1a]',
    petstoreLink: 'text-xs font-mono text-[#00ccff] hover:underline',
    urlLabel:     'block text-xs font-mono font-bold text-[#26932a] mb-1.5 uppercase tracking-wide',
    urlInput:     'flex-1 text-xs font-mono border border-[#1e4a1e] rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] placeholder-[#1a6b1a] focus:outline-none focus:border-[#33ff33] transition-colors',
    dividerLine:  'flex-1 border-t border-[#1e4a1e]',
    dividerText:  'text-[10px] font-mono text-[#1a6b1a] uppercase tracking-wider',
    fileLabel:    'block text-xs font-mono font-bold text-[#26932a] mb-1.5 uppercase tracking-wide',
    fileDropZone: 'flex items-center justify-center gap-2 border border-dashed border-[#1e4a1e] rounded-none px-4 py-5 cursor-pointer hover:border-[#33ff33] hover:bg-[#0a140a] transition-colors',
    fileDropIcon: 'w-4 h-4 text-[#1a6b1a]',
    fileDropText: 'text-xs font-mono text-[#26932a]',
    errorBanner:  'text-xs font-mono text-[#ff5555] bg-[#1e0000] border border-[#ff5555]/40 rounded-none px-3 py-2',
  },

  authModal: {
    tabBar:            'flex gap-1 px-4 py-2 bg-[#050e05] border-b border-[#1e4a1e] overflow-x-auto',
    tabActive:         'px-3 py-1.5 text-[11px] font-mono font-bold rounded-none bg-[#0f200f] text-[#55ee55] border border-[#1e4a1e] flex items-center gap-1.5 shrink-0 uppercase tracking-wide',
    tabInactive:       'px-3 py-1.5 text-[11px] font-mono rounded-none text-[#1a6b1a] hover:text-[#33cc33] transition-colors flex items-center gap-1.5 shrink-0 uppercase tracking-wide',
    titleIcon:         'w-4 h-4 text-[#26932a]',
    titleText:         'text-sm font-mono font-bold text-[#55ee55] uppercase tracking-wide',
    closeButton:       'text-xs font-mono bg-[#00ff41] hover:bg-[#33ff33] text-[#000000] px-4 py-2 rounded-none font-bold transition-colors uppercase tracking-wide',
    schemeType:        'text-[10px] font-mono text-[#1a6b1a] uppercase',
    authorizedBadge:   'text-[9px] font-mono text-[#33ff33] bg-[#052a05] border border-[#33ff33]/40 rounded-none px-1.5 py-0.5 font-bold uppercase tracking-wide',
    schemeDescription: 'text-[10px] font-mono text-[#1a6b1a]',
    fieldLabel:        'block text-[10px] font-mono text-[#26932a] mb-1 uppercase tracking-wide',
    fieldLabelHint:    'text-[#1a6b1a] font-mono',
    input:             'w-full text-xs font-mono border border-[#1e4a1e] rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] placeholder-[#1a6b1a] focus:outline-none focus:border-[#33ff33]',
    tokenWrapper:      'flex items-stretch border border-[#1e4a1e] rounded-none overflow-hidden bg-[#050e05] focus-within:border-[#33ff33] transition-all',
    tokenPrefix:       'px-2.5 flex items-center text-[10px] font-mono text-[#1a6b1a] bg-[#0a140a] border-r border-[#1e4a1e] shrink-0 select-none',
    tokenField:        'flex-1 text-xs px-2.5 py-2 bg-[#050e05] text-[#33cc33] placeholder-[#1a6b1a] focus:outline-none font-mono min-w-0',
    saveButton:        'text-xs font-mono bg-[#00ff41] hover:bg-[#33ff33] text-[#000000] px-3 py-1.5 rounded-none font-bold transition-colors uppercase tracking-wide',
    clearButton:       'text-xs font-mono border border-[#1e4a1e] text-[#26932a] hover:border-[#33ff33] hover:text-[#33cc33] px-3 py-1.5 rounded-none font-medium transition-colors uppercase tracking-wide',
  },

  serverConfig: {
    chip: {
      base: 'flex items-center gap-1.5 text-[11px] font-mono px-2.5 py-1.5 rounded-none border transition-colors shrink-0 text-[#26932a] border-[#1e4a1e] bg-transparent hover:border-[#33ff33] hover:text-[#33cc33] uppercase tracking-wide',
      open: 'bg-[#0f200f] text-[#33ff33] border-[#33ff33]/60 hover:bg-[#0f200f] hover:border-[#33ff33]/60',
    },
    chipIcon:            'w-3 h-3 shrink-0 text-[#1a6b1a]',
    backdrop:            'fixed inset-0 bg-black/80 flex items-center justify-center z-[60]',
    popover:             'bg-[#0a140a] rounded-none border border-[#1e4a1e] shadow-xl shadow-black/50 w-full max-w-sm mx-4 overflow-hidden',
    popoverHeader:       'flex items-center justify-between px-5 py-4 border-b border-[#1e4a1e]',
    headerIcon:          'w-4 h-4 text-[#26932a]',
    headerTitle:         'text-sm font-mono font-bold text-[#55ee55] uppercase tracking-wide',
    closeButton:         'text-[#26932a] hover:text-[#33cc33] text-xl leading-none font-mono',
    sectionDivider:      'px-5 py-4 border-b border-[#1e4a1e]',
    sectionLabel:        'block text-[10px] font-mono font-bold uppercase tracking-wider text-[#1a6b1a]',
    serverSelect:        'w-full text-[11px] font-mono border border-[#1e4a1e] rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] focus:outline-none focus:border-[#33ff33] cursor-pointer',
    variableName:        'text-[11px] font-mono font-bold text-[#33cc33]',
    variableDescription: 'text-[10px] font-mono text-[#1a6b1a] leading-tight mt-0.5',
    variableInput:       'text-[11px] font-mono border border-[#1e4a1e] rounded-none px-2.5 py-1.5 bg-[#050e05] text-[#33cc33] focus:outline-none focus:border-[#33ff33] w-full',
    resolvedSection:     'px-5 py-4 bg-[#050e05]',
    resolvedLabel:       'text-[10px] font-mono font-bold uppercase tracking-wider text-[#1a6b1a] mb-1.5',
    resolvedValue:       'text-[11px] font-mono text-[#00ff41] break-all',
  },

  commandBar: {
    backdrop:       'fixed inset-0 bg-black/85 z-[60] flex items-start justify-center pt-[12vh]',
    container:      'bg-[#030a03] rounded-none border border-[#1e4a1e] shadow-2xl shadow-black/80 w-full max-w-lg mx-4 flex flex-col overflow-hidden max-h-[70vh]',
    searchRow:      'flex items-center gap-3 px-4 py-3 border-b border-[#112a11] shrink-0',
    searchIcon:     'w-4 h-4 text-[#1a6b1a] shrink-0',
    input:          'flex-1 bg-transparent text-sm font-mono text-[#33cc33] placeholder-[#1a6b1a] outline-none',
    clearButton:    'text-[#1a6b1a] hover:text-[#33cc33] text-lg leading-none shrink-0 transition-colors font-mono',
    groupTitle:     'px-4 py-1.5 text-[10px] font-mono font-bold uppercase tracking-widest text-[#1a6b1a] select-none',
    resultItem:     { base: 'w-full flex items-center gap-3 px-4 py-2.5 text-left transition-colors font-mono hover:bg-[#0a140a]', active: 'bg-[#0f200f] hover:bg-[#0f200f] border-l-2 border-[#00ff41]' },
    actionIcon:     { base: 'w-7 h-7 rounded-none flex items-center justify-center shrink-0 bg-[#0a140a] text-[#1a6b1a] border border-[#112a11]', active: 'bg-[#0f200f] text-[#00ff41] border-[#1e4a1e]' },
    resultLabel:    'text-sm font-mono text-[#33cc33] truncate',
    resultSubtitle: 'text-xs font-mono text-[#1a6b1a] truncate mt-0.5',
    activeChevron:  'w-3.5 h-3.5 text-[#00ff41] shrink-0',
    emptyIcon:      'w-8 h-8 text-[#1a6b1a] mb-3',
    emptyText:      'text-sm font-mono text-[#1a6b1a]',
    footer:         'shrink-0 flex items-center gap-4 px-4 py-2 border-t border-[#112a11] bg-[#050e05]',
    shortcutText:   'flex items-center gap-1 text-[11px] font-mono text-[#1a6b1a]',
    shortcutBadge:  'font-mono text-[10px] bg-[#0a140a] border border-[#1e4a1e] rounded-none px-1 py-px',
    specTitle:      'ml-auto text-[11px] font-mono text-[#1a6b1a] truncate',
    highlightMark:  'bg-[#33ff33]/20 text-inherit not-italic',
  },

  schema: {
    tabBar:       'flex gap-1 px-3 py-2 bg-[#050e05] border-b border-[#1e4a1e]',
    tabActive:    'px-3 py-1 text-[11px] font-mono font-bold rounded-none bg-[#0f200f] text-[#55ee55] border border-[#1e4a1e] uppercase tracking-wide',
    tabInactive:  'px-3 py-1 text-[11px] font-mono rounded-none text-[#1a6b1a] hover:text-[#33cc33] transition-colors uppercase tracking-wide',
    description:  'px-4 pt-3 pb-0 text-[11px] font-mono text-[#26932a] leading-relaxed',
    exampleBlock: 'text-[11px] font-mono bg-[#000500] border border-[#112a11] rounded-none p-3 overflow-x-auto text-[#33cc33] leading-relaxed',
  },

  schemaNode: {
    name:          'font-mono text-[11px] text-[#55ee55] font-bold',
    typeBadge:     'text-[10px] rounded-none px-1.5 py-0.5 font-mono border',
    nullableBadge: 'text-[9px] font-mono bg-[#0f200f] text-[#26932a] rounded-none px-1 border border-[#1e4a1e]',
    constraint:    'text-[9px] font-mono text-[#1a6b1a]',
    enumValue:     'text-[9px] font-mono text-[#1a6b1a]',
    description:   'text-[11px] font-mono text-[#26932a] mt-0.5 leading-relaxed',
    enumKey:       'font-mono text-[#33cc33]',
    enumDesc:      'font-mono text-[#1a6b1a]',
    nestedBorder:  'border-l border-[#1e4a1e] ml-3 pl-3 mt-0.5',
    typeBadgeColors: {
      string:  'border-[#33ff33]/40 bg-[#052a05] text-[#33ff33]',
      integer: 'border-[#00ccff]/40 bg-[#001e2a] text-[#00ccff]',
      number:  'border-[#00ccff]/40 bg-[#001e2a] text-[#00ccff]',
      boolean: 'border-[#cc88ff]/40 bg-[#1a0030] text-[#cc88ff]',
      object:  'border-[#ffb000]/40 bg-[#1e1000] text-[#ffb000]',
      array:   'border-[#00ccff]/40 bg-[#001e2a] text-[#00ccff]',
      default: 'border-[#1e4a1e] bg-[#0a140a] text-[#26932a]',
    },
  },

  schemaDetail: {
    header:      'flex items-center gap-3 px-6 py-5 border-b border-[#1e4a1e] shrink-0',
    typeBadge:   'text-[9px] font-bold font-mono px-[5px] py-[2px] rounded-none uppercase border',
    schemaName:  'font-mono text-sm text-[#55ee55] font-bold',
    description: 'text-sm font-mono text-[#26932a] mb-6 leading-relaxed',
    sectionLabel:'text-xs font-mono font-bold uppercase tracking-wider text-[#1a6b1a] mb-4',
    schemaBox:   'border border-[#1e4a1e] rounded-none overflow-hidden',
    typeBadgeColors: {
      string:  'border-[#33ff33]/40 bg-[#052a05] text-[#33ff33]',
      integer: 'border-[#00ccff]/40 bg-[#001e2a] text-[#00ccff]',
      number:  'border-[#00ccff]/40 bg-[#001e2a] text-[#00ccff]',
      boolean: 'border-[#cc88ff]/40 bg-[#1a0030] text-[#cc88ff]',
      object:  'border-[#ffb000]/40 bg-[#1e1000] text-[#ffb000]',
      array:   'border-[#00ccff]/40 bg-[#001e2a] text-[#00ccff]',
      default: 'border-[#1e4a1e] bg-[#0a140a] text-[#26932a]',
    },
  },

  playground: {
    container:           'h-full flex flex-col bg-[#030a03]',
    header:              'flex items-center gap-2 px-5 border-b border-[#1e4a1e] shrink-0 h-[50px]',
    headerTitle:         'text-xs font-mono font-bold text-[#26932a] uppercase tracking-wider',
    emptyState:          'h-full flex flex-col items-center justify-center text-center px-6 gap-3 bg-[#030a03]',
    emptyIconWrapper:    'w-10 h-10 rounded-none border border-[#1e4a1e] flex items-center justify-center',
    emptyIcon:           'w-5 h-5 text-[#1a6b1a]',
    emptyText:           'text-sm font-mono text-[#1a6b1a]',
    inputLabel:          'text-[10px] font-mono font-bold uppercase tracking-wider text-[#1a6b1a] mb-3',
    textInput:           'w-full text-xs font-mono border border-[#1e4a1e] rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] placeholder-[#1a6b1a] focus:outline-none focus:border-[#33ff33] transition-colors',
    selectInput:         'w-full text-xs font-mono border border-[#1e4a1e] rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] focus:outline-none focus:border-[#33ff33] cursor-pointer transition-colors',
    fileInput:           'block w-full text-xs font-mono text-[#26932a] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-none file:border file:border-[#1e4a1e] file:text-xs file:font-mono file:font-medium file:bg-[#0f200f] file:text-[#33ff33] hover:file:bg-[#0a140a]',
    fileInputButton:     { base: 'file:py-1.5 file:px-3 file:rounded-none file:border file:border-[#1e4a1e] file:text-xs file:font-mono file:font-medium file:bg-[#0f200f] file:text-[#33ff33] hover:file:bg-[#0a140a]', hasFile: 'file:bg-[#0f200f]' },
    bodyEditor:          'w-full text-[11px] font-mono border border-[#1e4a1e] rounded-none px-3 py-2.5 bg-[#050e05] text-[#33cc33] placeholder-[#1a6b1a] focus:outline-none focus:border-[#33ff33] resize-y transition-colors leading-relaxed',
    contentTypeSelector: 'text-[10px] font-mono text-[#1a6b1a] border border-[#1e4a1e] rounded-none px-2 py-0.5 bg-[#050e05]',
    sendButton:          { base: 'shrink-0 px-4 rounded-none text-xs font-mono font-bold transition-all bg-[#00ff41] hover:bg-[#33ff33] active:scale-[0.98] text-[#000000] uppercase tracking-wide', loading: 'bg-[#0f200f] text-[#1a6b1a] border border-[#1e4a1e] cursor-not-allowed', disabled: 'bg-[#0f200f] text-[#1a6b1a] border border-[#1e4a1e] cursor-not-allowed' },
    responsePanel:       'h-full border-t border-[#1e4a1e] flex flex-col',
    responseStatus:      { base: 'text-[10px] font-mono font-bold rounded-none px-1.5 py-0.5 border bg-[#0a140a] text-[#26932a] border-[#1e4a1e]', success: 'bg-[#052a05] text-[#33ff33] border-[#33ff33]/40', redirect: 'bg-[#001e2a] text-[#00ccff] border-[#00ccff]/40', clientError: 'bg-[#1e1000] text-[#ffb000] border-[#ffb000]/40', serverError: 'bg-[#1e0000] text-[#ff5555] border-[#ff5555]/40' },
    responseTime:        'text-[10px] font-mono text-[#1a6b1a] border border-[#1e4a1e] rounded-none px-1.5 py-0.5',
    responseSize:        'text-[10px] font-mono text-[#1a6b1a]',
    responseTabs:        'flex items-center gap-2 px-4 py-2 border-b border-[#1e4a1e] bg-[#050e05] shrink-0',
    responseTab:         { base: 'px-2.5 py-1 text-[10px] font-mono rounded-none font-medium transition-colors text-[#1a6b1a] hover:text-[#33cc33] uppercase tracking-wide', active: 'bg-[#0f200f] text-[#55ee55] border border-[#1e4a1e]' },
    responseBody:        'flex-1 overflow-auto bg-[#000500]',
    responseEmpty:       'shrink-0 border-t border-[#1e4a1e] h-10 flex items-center justify-center text-[10px] font-mono text-[#1a6b1a]',
    errorBanner:         'mx-5 mb-4 px-3 py-2 bg-[#1e0000] border border-[#ff5555]/40 rounded-none text-xs font-mono text-[#ff5555]',
  },

  authStatus: {
    sectionLabel:      'text-[10px] font-mono font-bold uppercase tracking-wider text-[#1a6b1a] mb-3',
    emptyText:         'text-[10px] font-mono text-[#1a6b1a]',
    schemeRow:         'flex items-center justify-between py-2.5 px-3 border border-[#1e4a1e] bg-transparent',
    schemeName:        'text-[11px] font-mono text-[#33cc33]',
    schemeType:        'ml-1.5 text-[10px] font-mono text-[#1a6b1a]',
    authorizedBadge:   'text-[9px] font-mono text-[#33ff33] bg-[#052a05] border border-[#33ff33]/40 rounded-none px-1.5 py-0.5 font-bold uppercase tracking-wide',
    unauthorizedBadge: 'text-[9px] font-mono text-[#1a6b1a] bg-[#0a140a] border border-[#1e4a1e] rounded-none px-1.5 py-0.5 uppercase tracking-wide',
  },

  bodyEditor: {
    fileInput:    'block w-full text-xs font-mono text-[#26932a] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-none file:border file:border-[#1e4a1e] file:text-xs file:font-mono file:font-medium file:bg-[#0f200f] file:text-[#33ff33] hover:file:bg-[#0a140a]',
    formatButton: 'absolute top-1.5 right-1.5 z-10 text-[10px] font-mono text-[#1a6b1a] hover:text-[#33ff33] transition-colors px-1.5 py-0.5 rounded-none border border-transparent hover:border-[#1e4a1e] hover:bg-[#0a140a]',
    textarea:     'w-full text-[11px] font-mono border border-[#1e4a1e] rounded-none px-3 py-2.5 bg-[#050e05] text-[#33cc33] placeholder-[#1a6b1a] focus:outline-none focus:border-[#33ff33] resize-y transition-colors leading-relaxed',
  },

  paramLabel: {
    nameText:        'font-mono text-[11px] text-[#55ee55] font-bold',
    nameDeprecated:  'font-mono text-[11px] line-through text-[#1a6b1a]',
    locPath:         'text-[9px] font-mono rounded-none px-1.5 py-0.5 leading-none text-[#ffb000] bg-[#1e1000] border border-[#ffb000]/40',
    locQuery:        'text-[9px] font-mono rounded-none px-1.5 py-0.5 leading-none text-[#00ccff] bg-[#001e2a] border border-[#00ccff]/40',
    locHeader:       'text-[9px] font-mono rounded-none px-1.5 py-0.5 leading-none text-[#cc88ff] bg-[#1a0030] border border-[#cc88ff]/40',
    locCookie:       'text-[9px] font-mono rounded-none px-1.5 py-0.5 leading-none text-[#33ff33] bg-[#052a05] border border-[#33ff33]/40',
    locForm:         'text-[9px] font-mono rounded-none px-1.5 py-0.5 leading-none text-[#00ccff] bg-[#001e2a] border border-[#00ccff]/40',
    locDefault:      'text-[9px] font-mono rounded-none px-1.5 py-0.5 leading-none text-[#26932a] bg-[#0a140a] border border-[#1e4a1e]',
    typeBadge:       'text-[9px] font-mono text-[#cc88ff] bg-[#1a0030] border border-[#cc88ff]/40 rounded-none px-1.5 py-0.5 leading-none',
    requiredBadge:   'text-[9px] font-mono font-bold text-[#ff5555] bg-[#1e0000] border border-[#ff5555]/40 rounded-none px-1.5 py-0.5 leading-none',
    deprecatedBadge: 'text-[9px] font-mono font-bold text-[#ffb000] bg-[#1e1000] border border-[#ffb000]/40 rounded-none px-1.5 py-0.5 leading-none',
    constraintBadge: 'text-[9px] font-mono text-[#1a6b1a] bg-[#0a140a] border border-[#1e4a1e] rounded-none px-1.5 py-0.5 leading-none',
    tooltipIcon:     'w-3.5 h-3.5 text-[#1a6b1a] cursor-help hover:text-[#33cc33] transition-colors',
    tooltipPopup:    'pointer-events-none absolute bottom-full right-0 mb-2 w-56 rounded-none bg-[#000500] border border-[#1e4a1e] px-2.5 py-2 text-[10px] font-mono text-[#33cc33] leading-snug shadow-lg shadow-black/50 opacity-0 group-hover/tip:opacity-100 transition-opacity z-50',
  },

  responsePanel: {
    loadingState:  'shrink-0 border-t border-[#1e4a1e] h-16 flex items-center justify-center gap-2 text-xs font-mono text-[#1a6b1a] bg-[#050e05]',
    emptyState:    'shrink-0 border-t border-[#1e4a1e] h-10 flex items-center justify-center',
    emptyText:     'text-[10px] font-mono text-[#1a6b1a]',
    container:     'h-full border-t border-[#1e4a1e] flex flex-col',
    tabBar:        'flex items-center gap-2 px-4 py-2 border-b border-[#1e4a1e] bg-[#050e05] shrink-0',
    tab:           { base: 'px-2.5 py-1 text-[10px] font-mono rounded-none font-medium transition-colors text-[#1a6b1a] hover:text-[#33cc33] uppercase tracking-wide', active: 'bg-[#0f200f] text-[#55ee55] border border-[#1e4a1e]' },
    tabDivider:    'w-px h-3 bg-[#1e4a1e] mx-1',
    headerCount:   'ml-0.5 font-mono text-[#1a6b1a]',
    copyButton:    { base: 'flex items-center gap-1 text-[10px] font-mono px-2 py-1 rounded-none hover:bg-[#0a140a] transition-colors text-[#1a6b1a] hover:text-[#33cc33] border border-transparent hover:border-[#1e4a1e]', copied: 'text-[#33ff33]' },
    statusNeutral: 'text-[10px] font-mono border rounded-none px-1.5 py-0.5 font-bold text-[#26932a] bg-[#0a140a] border-[#1e4a1e]',
    statusSuccess: 'text-[10px] font-mono border rounded-none px-1.5 py-0.5 font-bold text-[#33ff33] bg-[#052a05] border-[#33ff33]/40',
    statusError:   'text-[10px] font-mono border rounded-none px-1.5 py-0.5 font-bold text-[#ff5555] bg-[#1e0000] border-[#ff5555]/40',
    bodyContainer: 'flex-1 overflow-auto bg-[#000500]',
    bodyPre:       'text-[11px] p-3 font-mono text-[#33cc33] leading-relaxed',
    headersPre:    'text-[11px] p-3 font-mono text-[#26932a] leading-relaxed',
  },

  sendBar: {
    container:          'px-5 py-3 border-b border-[#1e4a1e] shrink-0 bg-[#050e05]',
    urlBox:             'flex items-center gap-2 flex-1 min-w-0 bg-[#000500] rounded-none px-2.5 py-2 border border-[#1e4a1e]',
    urlCode:            'text-[10px] font-mono text-[#26932a] leading-tight flex-1 min-w-0 break-all',
    sendButtonActive:   'shrink-0 px-4 rounded-none text-xs font-mono font-bold transition-all bg-[#00ff41] hover:bg-[#33ff33] active:scale-[0.98] text-[#000000] uppercase tracking-wide',
    sendButtonDisabled: 'shrink-0 px-4 rounded-none text-xs font-mono font-bold transition-all bg-[#0f200f] text-[#1a6b1a] border border-[#1e4a1e] cursor-not-allowed uppercase tracking-wide',
  },

  inputScalar: {
    input:        'w-full text-xs font-mono border border-[#1e4a1e] rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] placeholder-[#1a6b1a] focus:outline-none focus:border-[#33ff33] transition-colors',
    inputInvalid: 'w-full text-xs font-mono border border-[#ff5555]/60 rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] placeholder-[#1a6b1a] focus:outline-none focus:border-[#ff5555] transition-colors',
  },

  inputBoolean: {
    select:        'w-full text-xs font-mono border border-[#1e4a1e] rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] focus:outline-none focus:border-[#33ff33] transition-colors',
    selectInvalid: 'w-full text-xs font-mono border border-[#ff5555]/60 rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] focus:outline-none focus:border-[#ff5555] transition-colors',
  },

  inputEnum: {
    select:        'w-full text-xs font-mono border border-[#1e4a1e] rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] focus:outline-none focus:border-[#33ff33] transition-colors',
    selectInvalid: 'w-full text-xs font-mono border border-[#ff5555]/60 rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] focus:outline-none focus:border-[#ff5555] transition-colors',
  },

  inputFile: {
    input: 'block w-full text-xs font-mono text-[#26932a] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:rounded-none file:border file:border-[#1e4a1e] file:text-xs file:font-mono file:font-medium file:bg-[#0f200f] file:text-[#33ff33] hover:file:bg-[#0a140a]',
  },

  inputArray: {
    rowInput:        'flex-1 text-xs font-mono border border-[#1e4a1e] rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] placeholder-[#1a6b1a] focus:outline-none focus:border-[#33ff33] transition-colors',
    rowInputInvalid: 'flex-1 text-xs font-mono border border-[#ff5555]/60 rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] placeholder-[#1a6b1a] focus:outline-none focus:border-[#ff5555] transition-colors',
    rowIndex:        'text-[9px] font-mono text-[#1a6b1a] w-4 text-right shrink-0',
    removeButton:    'shrink-0 w-5 h-5 flex items-center justify-center rounded-none text-[#1a6b1a] hover:text-[#ff5555] hover:bg-[#1e0000] disabled:opacity-0 transition-colors',
    addButton:       'flex items-center gap-1 text-[10px] font-mono text-[#33ff33] hover:text-[#55ee55] transition-colors',
    hint:            'text-[9px] font-mono text-[#1a6b1a]',
  },

  inputMultiSelect: {
    trigger:        'w-full text-xs font-mono border border-[#1e4a1e] rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] focus:outline-none focus:border-[#33ff33] transition-colors flex items-center justify-between text-left',
    triggerInvalid: 'w-full text-xs font-mono border border-[#ff5555]/60 rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] focus:outline-none focus:border-[#ff5555] transition-colors flex items-center justify-between text-left',
    placeholder:    'font-mono text-[#1a6b1a]',
    dropdown:       'absolute z-20 mt-1 w-full rounded-none border border-[#1e4a1e] bg-[#050e05] shadow-lg shadow-black/50 py-1',
    dropdownItem:   'flex items-center gap-2 px-3 py-1.5 hover:bg-[#0a140a] cursor-pointer',
    optionText:     'text-xs font-mono text-[#33cc33]',
  },

  inputObject: {
    textarea:        'w-full text-xs font-mono border border-[#1e4a1e] rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] placeholder-[#1a6b1a] focus:outline-none focus:border-[#33ff33] transition-colors resize-y',
    textareaInvalid: 'w-full text-xs font-mono border border-[#ff5555]/60 rounded-none px-3 py-2 bg-[#050e05] text-[#33cc33] placeholder-[#1a6b1a] focus:outline-none focus:border-[#ff5555] transition-colors resize-y',
  },

  detailPane: {
    spinner:      'w-5 h-5 animate-spin text-[#33ff33]',
    errorIcon:    'w-10 h-10 rounded-none border border-[#ff5555]/40 bg-[#1e0000] flex items-center justify-center shrink-0 text-[#ff5555]',
    errorMessage: 'text-sm font-mono text-[#ff5555]',
    retryLink:    'text-xs font-mono text-[#1a6b1a] hover:text-[#33cc33] underline underline-offset-2',
    emptyIcon:    'w-10 h-10 rounded-none border border-[#1e4a1e] flex items-center justify-center text-[#1a6b1a]',
    emptyMessage: 'text-sm font-mono text-[#1a6b1a]',
  },

  verticalResizable: {
    handle: 'w-8 h-0.5 rounded-none bg-[#1e4a1e] group-hover:bg-[#33ff33] transition-colors',
  },

  syntax: {
    key:     '#00ccff',
    string:  '#ffff66',
    boolean: '#cc88ff',
    null:    '#1a6b1a',
    number:  '#ffb000',
  },

  paneHandle:  'border-l border-[#1e4a1e] group-hover:border-[#39ff14] group-[.dragging]:border-[#00ff00] transition-colors duration-150',
  focusRing:   'focus:ring-1 focus:ring-[#33ff33] focus:ring-offset-0',
  scrollbar:   { thumb: 'bg-[#1e4a1e]', thumbHover: 'bg-[#2d6e2d]' },
};