/**
 * Wireframe theme preset — self-aware "still being designed" aesthetic.
 * Dashed borders, light blueprint-blue tint, annotation-style section labels.
 * Palette: blueprint (#F4F7FC), slate (#334155), blue (#2563EB), dash (#93A3B8).
 */
import type { AppTheme } from '../contract';

const badge = 'method-badge shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] border border-dashed uppercase w-[36px] text-center';

export const wireframeTheme: AppTheme = {
  name: 'wireframe',
  fontFamily: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', ui-monospace, monospace",

  appRoot: {
    root:              'flex flex-col h-full overflow-hidden bg-[#F4F7FC]',
    navPane:           'shrink-0 bg-[#EDF2FA] overflow-y-auto flex flex-col',
    detailPane:        'flex-1 min-w-0 bg-[#F4F7FC] overflow-hidden',
    tryPane:           'shrink-0 bg-[#F4F7FC] overflow-hidden',
    shortcutsBackdrop: 'fixed inset-0 bg-[#334155]/40 flex items-center justify-center z-50',
    shortcutsPanel:    'bg-[#F4F7FC] w-72 mx-4 overflow-hidden border border-dashed border-[#93A3B8] shadow-lg',
    shortcutsHeader:   'flex items-center justify-between px-5 py-3.5 border-b border-dashed border-[#93A3B8]',
    shortcutsTitle:    'text-sm font-medium text-[#334155]',
    shortcutsClose:    'text-[#7B93B0] hover:text-[#334155] text-xl leading-none transition-colors',
    shortcutsRow:      'flex items-center justify-between py-1.5 border-b border-dashed border-[#C8D8EC] last:border-0',
    shortcutsDesc:     'text-xs text-[#475569]',
    shortcutsKbd:      'text-[10px] font-mono bg-[#EDF2FA] text-[#475569] px-2 py-0.5 border border-dashed border-[#93A3B8] shrink-0',
  },

  nav: {
    container:         'shrink-0 bg-[#EDF2FA] overflow-y-auto flex flex-col h-full',
    divider:           'mt-1 border-t border-dashed border-[#93A3B8]',
    searchWrapper:     'px-4 py-3 border-b border-dashed border-[#93A3B8] shrink-0',
    searchInput:       'w-full pl-7 pr-6 py-2 text-[11px] border border-dashed border-[#93A3B8] bg-[#F4F7FC] text-[#334155] placeholder-[#7B93B0] focus:outline-none focus:ring-1 focus:ring-[#2563EB] focus:border-[#2563EB] transition-colors',
    searchIcon:        'absolute left-2.5 top-1/2 -translate-y-1/2 w-3 h-3 text-[#7B93B0] pointer-events-none',
    searchClearButton: 'absolute right-2 top-1/2 -translate-y-1/2 text-[#7B93B0] hover:text-[#334155] leading-none text-sm',
    searchHint:        'absolute right-2 top-1/2 -translate-y-1/2 text-[9px] text-[#93A3B8] border border-dashed border-[#93A3B8] px-1 font-mono pointer-events-none leading-none',
    loadingSpinner:    'w-5 h-5 animate-spin text-[#2563EB]',
    tabBar:            'flex gap-1 px-4 py-2 border-b border-dashed border-[#93A3B8]',
    tab:               { base: 'px-2.5 py-1 text-[11px] font-medium transition-colors text-[#7B93B0] hover:text-[#334155]', active: 'bg-[#DCE8F8] text-[#2563EB] border border-dashed border-[#7EB8F7]' },
    tagHeader:         'w-full flex items-center justify-between px-4 py-2.5 text-[10px] font-semibold uppercase tracking-widest text-[#7B93B0] hover:text-[#334155] transition-colors',
    tagChevron:        'w-3 h-3 transition-transform',
    tagCount:          'text-[10px] text-[#7B93B0] font-mono',
    endpointItem:      { base: 'nav-endpoint w-full flex items-center gap-2.5 px-4 py-2 text-left transition-colors text-[#475569] hover:bg-[#DCE8F8]/40 hover:text-[#334155]', active: 'bg-[#DCE8F8] text-[#334155] border-l-2 border-[#2563EB]' },
    endpointPath:      'truncate text-[11px] font-mono',
    methodBadge:       { base: badge, get: 'bg-[#EDF2FA] text-[#475569] border-[#93A3B8]', post: 'bg-[#DCE8F8] text-[#2563EB] border-[#7EB8F7]', put: 'bg-[#FFF7ED] text-[#92400E] border-[#D4A56A]', delete: 'bg-[#FEF2F2] text-[#991B1B] border-[#FCA5A5]', patch: 'bg-[#F0FDF4] text-[#14532D] border-[#86EFAC]', options: 'bg-[#EDF2FA] text-[#475569] border-[#93A3B8]', head: 'bg-[#EDF2FA] text-[#475569] border-[#93A3B8]' },
    schemaItem:        { base: 'w-full text-left gap-2.5 px-4 py-2 transition-colors hover:bg-[#DCE8F8]/40', active: 'bg-[#DCE8F8] border-l-2 border-[#2563EB]' },
    schemaName:        { base: 'truncate text-[11px] font-mono text-[#475569]', active: 'text-[#334155]' },
    schemaTypeBadge:   'shrink-0 text-[9px] font-bold font-mono px-[5px] py-[2px] border border-dashed border-[#93A3B8] bg-[#EDF2FA] text-[#7B93B0] uppercase',
    schemaDescription: 'mt-0.5 text-[10px] text-[#7B93B0] truncate pl-[38px]',
    emptyState:        'text-[11px] text-[#7B93B0]',
  },

  endpoint: {
    container:           'h-full flex flex-col',
    header:              'flex items-center gap-3 px-6 py-5 border-b border-dashed border-[#93A3B8] shrink-0 h-[50px]',
    methodBadge:         { base: badge, get: 'bg-[#EDF2FA] text-[#475569] border-[#93A3B8]', post: 'bg-[#DCE8F8] text-[#2563EB] border-[#7EB8F7]', put: 'bg-[#FFF7ED] text-[#92400E] border-[#D4A56A]', delete: 'bg-[#FEF2F2] text-[#991B1B] border-[#FCA5A5]', patch: 'bg-[#F0FDF4] text-[#14532D] border-[#86EFAC]', options: 'bg-[#EDF2FA] text-[#475569] border-[#93A3B8]', head: 'bg-[#EDF2FA] text-[#475569] border-[#93A3B8]' },
    path:                'font-mono text-sm text-[#334155]',
    summary:             'text-sm text-[#334155] mb-2 font-medium',
    description:         'text-xs text-[#475569]',
    deprecated:          'ml-auto text-[10px] bg-[#FFF7ED] text-[#92400E] border border-dashed border-[#D4A56A] px-2 py-0.5',
    paramSection:        'border border-dashed border-[#93A3B8] overflow-hidden',
    paramSectionTitle:   'text-xs font-semibold uppercase tracking-wider text-[#7B93B0] mb-4',
    paramLocTitle:       'text-[10px] font-semibold uppercase tracking-wider text-[#7B93B0] mb-3',
    paramRow:            'border-b border-dashed border-[#C8D8EC] last:border-0 bg-[#F4F7FC] hover:bg-[#EDF2FA] transition-colors',
    paramName:           'font-mono text-[11px] text-[#334155]',
    paramType:           'text-[10px] bg-[#EDF2FA] text-[#475569] border border-dashed border-[#93A3B8] px-1.5 py-0.5 font-mono',
    paramRequired:       'text-[#991B1B] text-[9px] font-semibold ml-1',
    paramDescription:    'px-4 py-3 w-full text-xs text-[#475569]',
    mutedText:           'text-[#7B93B0]',
    responseAccordion:   'border border-dashed border-[#93A3B8] overflow-hidden divide-y divide-dashed divide-[#C8D8EC]',
    responseHeader:      'w-full flex items-center gap-3 px-4 py-3.5 hover:bg-[#EDF2FA] transition-colors text-left',
    responseStatusCode:  { base: 'text-xs font-mono font-semibold', success: 'text-[#14532D]', redirect: 'text-[#1D4ED8]', clientError: 'text-[#92400E]', serverError: 'text-[#991B1B]' },
    responseDescription: 'text-xs text-[#475569] flex-1',
    bodySection:         'px-3 py-1.5 bg-[#EDF2FA] border-b border-dashed border-[#93A3B8] flex items-center gap-2',
    bodyContentType:     'text-[10px] text-[#7B93B0] font-mono',
  },

  topBar: {
    container:              'relative flex items-center gap-4 px-6 h-16 border-b border-dashed border-[#93A3B8] bg-[#EDF2FA] shrink-0 z-10',
    specTitle:              'text-sm font-medium text-[#334155] truncate',
    specVersion:            'text-[10px] text-[#7B93B0] border border-dashed border-[#93A3B8] px-1.5 py-px font-mono shrink-0 leading-tight',
    specDescription:        'text-[10px] text-[#7B93B0] truncate leading-tight mt-px',
    noSpecIcon:             'w-7 h-7 bg-[#DCE8F8] border border-dashed border-[#7EB8F7] flex items-center justify-center shrink-0',
    noSpecIconSvg:          'w-4 h-4 text-[#7B93B0]',
    noSpecTitle:            'text-sm font-medium text-[#7B93B0]',
    divider:                'w-px h-5 bg-[#C8D8EC] mx-1 shrink-0',
    authButtonConfigured:   'flex items-center gap-1.5 text-xs px-2.5 py-1.5 font-medium border border-dashed transition-all shrink-0 text-[#14532D] bg-[#F0FDF4] border-[#86EFAC] hover:bg-[#DCFCE7]',
    authButtonUnconfigured: 'flex items-center gap-1.5 text-xs px-2.5 py-1.5 font-medium border border-dashed transition-all shrink-0 text-[#475569] bg-[#F4F7FC] border-[#93A3B8] hover:bg-[#EDF2FA] hover:border-[#2563EB]',
    neutralButton:          'flex items-center gap-1.5 text-xs px-2.5 py-1.5 font-medium border border-dashed transition-all shrink-0 text-[#475569] bg-[#F4F7FC] border-[#93A3B8] hover:bg-[#EDF2FA] hover:border-[#2563EB]',
    loadButton:             'flex items-center gap-1.5 text-xs text-white bg-[#2563EB] hover:bg-[#1D4ED8] active:bg-[#1E40AF] px-3 py-1.5 font-semibold transition-colors shrink-0 border border-dashed border-[#7EB8F7]',
  },

  themePicker: {
    dropdown: 'bg-[#F4F7FC] border border-dashed border-[#93A3B8] shadow-lg py-1.5 overflow-hidden',
    item:     { base: 'w-full flex items-center gap-3 px-3 py-2 text-left hover:bg-[#EDF2FA] transition-colors', active: 'bg-[#DCE8F8]' },
    name:     'text-sm text-[#334155] font-medium flex-1',
    check:    'w-3.5 h-3.5 text-[#2563EB] shrink-0',
  },

  modal: {
    backdrop:    'fixed inset-0 bg-[#334155]/40 flex items-center justify-center z-50',
    container:   'bg-[#F4F7FC] w-full mx-4 overflow-hidden border border-dashed border-[#93A3B8] shadow-lg',
    header:      'flex items-center justify-between px-5 py-4 border-b border-dashed border-[#93A3B8]',
    closeButton: 'text-[#7B93B0] hover:text-[#334155] text-xl leading-none',
    footer:      'px-5 py-3 bg-[#EDF2FA] border-t border-dashed border-[#93A3B8]',
  },

  loadModal: {
    title:        'text-sm font-medium text-[#334155]',
    footerText:   'text-[10px] text-[#7B93B0]',
    petstoreLink: 'text-xs text-[#2563EB] hover:underline',
    urlLabel:     'block text-xs font-medium text-[#475569] mb-1.5',
    urlInput:     'flex-1 text-xs border border-dashed border-[#93A3B8] px-3 py-2 bg-[#F4F7FC] text-[#334155] placeholder-[#7B93B0] focus:outline-none focus:ring-1 focus:ring-[#2563EB] focus:border-[#2563EB] transition-colors',
    dividerLine:  'flex-1 border-t border-dashed border-[#93A3B8]',
    dividerText:  'text-[10px] text-[#7B93B0] uppercase tracking-wider',
    fileLabel:    'block text-xs font-medium text-[#475569] mb-1.5',
    fileDropZone: 'flex items-center justify-center gap-2 border-2 border-dashed border-[#93A3B8] px-4 py-5 cursor-pointer hover:border-[#2563EB] hover:bg-[#DCE8F8]/40 transition-colors',
    fileDropIcon: 'w-4 h-4 text-[#7B93B0]',
    fileDropText: 'text-xs text-[#475569]',
    errorBanner:  'text-xs text-[#991B1B] bg-[#FEF2F2] border border-dashed border-[#FCA5A5] px-3 py-2',
  },

  authModal: {
    tabBar:            'flex gap-1 px-4 py-2 bg-[#EDF2FA] border-b border-dashed border-[#93A3B8] overflow-x-auto',
    tabActive:         'px-3 py-1.5 text-[11px] font-medium bg-[#DCE8F8] text-[#2563EB] border border-dashed border-[#7EB8F7] flex items-center gap-1.5 shrink-0',
    tabInactive:       'px-3 py-1.5 text-[11px] font-medium text-[#7B93B0] hover:text-[#334155] transition-colors flex items-center gap-1.5 shrink-0',
    titleIcon:         'w-4 h-4 text-[#475569]',
    titleText:         'text-sm font-medium text-[#334155]',
    closeButton:       'text-xs bg-[#334155] hover:bg-[#475569] text-white px-4 py-2 font-medium transition-colors',
    schemeType:        'text-[10px] text-[#7B93B0]',
    authorizedBadge:   'text-[9px] text-[#14532D] bg-[#F0FDF4] border border-dashed border-[#86EFAC] px-1.5 py-0.5 font-semibold uppercase tracking-wide',
    schemeDescription: 'text-[10px] text-[#7B93B0]',
    fieldLabel:        'block text-[10px] text-[#475569] mb-1',
    fieldLabelHint:    'text-[#7B93B0] font-sans',
    input:             'w-full text-xs border border-dashed border-[#93A3B8] px-3 py-2 bg-[#F4F7FC] text-[#334155] placeholder-[#93A3B8] focus:outline-none focus:ring-1 focus:ring-[#2563EB] focus:border-[#2563EB] font-mono',
    tokenWrapper:      'flex items-stretch border border-dashed border-[#93A3B8] overflow-hidden bg-[#F4F7FC] focus-within:ring-1 focus-within:ring-[#2563EB] focus-within:border-[#2563EB] transition-all',
    tokenPrefix:       'px-2.5 flex items-center text-[10px] text-[#7B93B0] bg-[#EDF2FA] border-r border-dashed border-[#93A3B8] font-mono shrink-0 select-none',
    tokenField:        'flex-1 text-xs px-2.5 py-2 bg-[#F4F7FC] text-[#334155] placeholder-[#93A3B8] focus:outline-none font-mono min-w-0',
    saveButton:        'text-xs bg-[#2563EB] hover:bg-[#1D4ED8] text-white px-3 py-1.5 font-semibold transition-colors',
    clearButton:       'text-xs border border-dashed border-[#93A3B8] text-[#475569] hover:border-[#2563EB] hover:text-[#334155] px-3 py-1.5 font-medium transition-colors',
  },

  serverConfig: {
    chip: {
      base: 'flex items-center gap-1.5 text-[11px] font-mono px-2.5 py-1.5 border border-dashed transition-colors shrink-0 text-[#475569] border-[#93A3B8] bg-[#F4F7FC] hover:bg-[#EDF2FA] hover:border-[#2563EB]',
      open: 'bg-[#DCE8F8] text-[#2563EB] border-[#7EB8F7] hover:bg-[#DCE8F8] hover:border-[#7EB8F7]',
    },
    chipIcon:            'w-3 h-3 shrink-0 text-[#7B93B0]',
    backdrop:            'fixed inset-0 bg-[#334155]/40 flex items-center justify-center z-[60]',
    popover:             'bg-[#F4F7FC] w-full max-w-sm mx-4 overflow-hidden border border-dashed border-[#93A3B8] shadow-lg',
    popoverHeader:       'flex items-center justify-between px-5 py-4 border-b border-dashed border-[#93A3B8]',
    headerIcon:          'w-4 h-4 text-[#475569]',
    headerTitle:         'text-sm font-medium text-[#334155]',
    closeButton:         'text-[#7B93B0] hover:text-[#334155] text-xl leading-none',
    sectionDivider:      'px-5 py-4 border-b border-dashed border-[#93A3B8]',
    sectionLabel:        'block text-[10px] font-semibold uppercase tracking-wider text-[#7B93B0]',
    serverSelect:        'w-full text-[11px] font-mono border border-dashed border-[#93A3B8] px-3 py-2 bg-[#F4F7FC] text-[#334155] focus:outline-none focus:ring-1 focus:ring-[#2563EB] cursor-pointer',
    variableName:        'text-[11px] font-mono font-medium text-[#334155]',
    variableDescription: 'text-[10px] text-[#7B93B0] leading-tight mt-0.5',
    variableInput:       'text-[11px] font-mono border border-dashed border-[#93A3B8] px-2.5 py-1.5 bg-[#F4F7FC] text-[#334155] focus:outline-none focus:ring-1 focus:ring-[#2563EB] w-full',
    resolvedSection:     'px-5 py-4 bg-[#EDF2FA]',
    resolvedLabel:       'text-[10px] font-semibold uppercase tracking-wider text-[#7B93B0] mb-1.5',
    resolvedValue:       'text-[11px] font-mono text-[#334155] break-all',
  },

  commandBar: {
    backdrop:       'fixed inset-0 bg-[#334155]/50 z-[60] flex items-start justify-center pt-[12vh]',
    container:      'bg-[#F4F7FC] w-full max-w-lg mx-4 flex flex-col overflow-hidden border border-dashed border-[#93A3B8] shadow-lg max-h-[70vh]',
    searchRow:      'flex items-center gap-3 px-4 py-3 border-b border-dashed border-[#93A3B8] shrink-0',
    searchIcon:     'w-4 h-4 text-[#7B93B0] shrink-0',
    input:          'flex-1 bg-transparent text-sm text-[#334155] placeholder-[#7B93B0] outline-none',
    clearButton:    'text-[#7B93B0] hover:text-[#334155] text-lg leading-none shrink-0 transition-colors',
    groupTitle:     'px-4 py-1.5 text-[10px] font-semibold uppercase tracking-widest text-[#7B93B0] select-none',
    resultItem:     { base: 'w-full flex items-center gap-3 px-4 py-2.5 text-left transition-colors hover:bg-[#EDF2FA]', active: 'bg-[#DCE8F8] hover:bg-[#DCE8F8]' },
    actionIcon:     { base: 'w-7 h-7 flex items-center justify-center shrink-0 bg-[#EDF2FA] border border-dashed border-[#C8D8EC] text-[#475569]', active: 'bg-[#DCE8F8] border-[#7EB8F7] text-[#2563EB]' },
    resultLabel:    'text-sm font-medium text-[#334155] truncate',
    resultSubtitle: 'text-xs text-[#7B93B0] truncate mt-0.5',
    activeChevron:  'w-3.5 h-3.5 text-[#2563EB] shrink-0',
    emptyIcon:      'w-8 h-8 text-[#C8D8EC] mb-3',
    emptyText:      'text-sm text-[#7B93B0]',
    footer:         'shrink-0 flex items-center gap-4 px-4 py-2 border-t border-dashed border-[#93A3B8] bg-[#EDF2FA]',
    shortcutText:   'flex items-center gap-1 text-[11px] text-[#7B93B0]',
    shortcutBadge:  'font-mono text-[10px] bg-[#F4F7FC] border border-dashed border-[#93A3B8] px-1 py-px',
    specTitle:      'ml-auto text-[11px] text-[#C8D8EC] truncate',
    highlightMark:  'bg-[#DCE8F8] text-[#2563EB] not-italic',
  },

  schema: {
    tabBar:       'flex gap-1 px-3 py-2 bg-[#EDF2FA] border-b border-dashed border-[#93A3B8]',
    tabActive:    'px-3 py-1 text-[11px] font-medium bg-[#DCE8F8] text-[#2563EB] border border-dashed border-[#7EB8F7]',
    tabInactive:  'px-3 py-1 text-[11px] font-medium text-[#7B93B0] hover:text-[#334155] transition-colors',
    description:  'px-4 pt-3 pb-0 text-[11px] text-[#475569] leading-relaxed',
    exampleBlock: 'text-[11px] bg-[#EDF2FA] border border-dashed border-[#93A3B8] p-3 overflow-x-auto text-[#334155] font-mono leading-relaxed',
  },

  schemaNode: {
    name:          'font-mono text-[11px] text-[#334155]',
    typeBadge:     'text-[10px] border border-dashed px-1.5 py-0.5 font-mono',
    nullableBadge: 'text-[9px] bg-[#EDF2FA] text-[#7B93B0] border border-dashed border-[#C8D8EC] px-1 font-mono',
    constraint:    'text-[9px] font-mono text-[#7B93B0]',
    enumValue:     'text-[9px] text-[#7B93B0] font-mono',
    description:   'text-[11px] text-[#475569] mt-0.5 leading-relaxed',
    enumKey:       'font-mono text-[#334155]',
    enumDesc:      'text-[#7B93B0]',
    nestedBorder:  'border-l-2 border-dashed border-[#93A3B8] ml-3 pl-3 mt-0.5',
    typeBadgeColors: {
      string:  'bg-[#F0FDF4] text-[#14532D] border-[#86EFAC]',
      integer: 'bg-[#EFF6FF] text-[#1E40AF] border-[#93C5FD]',
      number:  'bg-[#EFF6FF] text-[#1E40AF] border-[#93C5FD]',
      boolean: 'bg-[#FAF5FF] text-[#6B21A8] border-[#D8B4FE]',
      object:  'bg-[#FFFBEB] text-[#92400E] border-[#FCD34D]',
      array:   'bg-[#ECFEFF] text-[#164E63] border-[#67E8F9]',
      default: 'bg-[#EDF2FA] text-[#475569] border-[#93A3B8]',
    },
  },

  schemaDetail: {
    header:      'flex items-center gap-3 px-6 py-5 border-b border-dashed border-[#93A3B8] shrink-0',
    typeBadge:   'text-[9px] font-bold font-mono px-[5px] py-[2px] border border-dashed uppercase',
    schemaName:  'font-mono text-sm text-[#334155]',
    description: 'text-sm text-[#475569] mb-6 leading-relaxed',
    sectionLabel:'text-xs font-semibold uppercase tracking-wider text-[#7B93B0] mb-4',
    schemaBox:   'border border-dashed border-[#93A3B8] overflow-hidden bg-[#F4F7FC]',
    typeBadgeColors: {
      string:  'bg-[#F0FDF4] text-[#14532D] border-[#86EFAC]',
      integer: 'bg-[#EFF6FF] text-[#1E40AF] border-[#93C5FD]',
      number:  'bg-[#EFF6FF] text-[#1E40AF] border-[#93C5FD]',
      boolean: 'bg-[#FAF5FF] text-[#6B21A8] border-[#D8B4FE]',
      object:  'bg-[#FFFBEB] text-[#92400E] border-[#FCD34D]',
      array:   'bg-[#ECFEFF] text-[#164E63] border-[#67E8F9]',
      default: 'bg-[#EDF2FA] text-[#475569] border-[#93A3B8]',
    },
  },

  playground: {
    container:           'h-full flex flex-col bg-[#F4F7FC]',
    header:              'flex items-center gap-2 px-5 border-b border-dashed border-[#93A3B8] shrink-0 h-[50px]',
    headerTitle:         'text-xs font-semibold text-[#334155]',
    emptyState:          'h-full flex flex-col items-center justify-center text-center px-6 gap-3 bg-[#F4F7FC]',
    emptyIconWrapper:    'w-10 h-10 bg-[#EDF2FA] border border-dashed border-[#93A3B8] flex items-center justify-center',
    emptyIcon:           'w-5 h-5 text-[#7B93B0]',
    emptyText:           'text-sm text-[#7B93B0]',
    inputLabel:          'text-[10px] font-semibold uppercase tracking-wider text-[#7B93B0] mb-3',
    textInput:           'w-full text-xs border border-dashed border-[#93A3B8] px-3 py-2 bg-[#F4F7FC] text-[#334155] placeholder-[#93A3B8] focus:outline-none focus:ring-1 focus:ring-[#2563EB] focus:border-[#2563EB] transition-colors font-mono',
    selectInput:         'w-full text-xs border border-dashed border-[#93A3B8] px-3 py-2 bg-[#F4F7FC] text-[#334155] focus:outline-none focus:ring-1 focus:ring-[#2563EB] cursor-pointer transition-colors',
    fileInput:           'block w-full text-xs text-[#475569] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:border file:border-dashed file:border-[#93A3B8] file:text-xs file:font-medium file:bg-[#EDF2FA] file:text-[#475569] hover:file:bg-[#DCE8F8]',
    fileInputButton:     { base: 'file:py-1.5 file:px-3 file:border file:border-dashed file:border-[#93A3B8] file:text-xs file:font-medium file:bg-[#EDF2FA] file:text-[#475569] hover:file:bg-[#DCE8F8]', hasFile: 'file:bg-[#DCE8F8]' },
    bodyEditor:          'w-full text-[11px] border border-dashed border-[#93A3B8] px-3 py-2.5 bg-[#F4F7FC] text-[#334155] placeholder-[#93A3B8] focus:outline-none focus:ring-1 focus:ring-[#2563EB] focus:border-[#2563EB] font-mono resize-y transition-colors leading-relaxed',
    contentTypeSelector: 'text-[10px] font-mono text-[#7B93B0] border border-dashed border-[#93A3B8] px-2 py-0.5 bg-[#EDF2FA]',
    sendButton:          { base: 'shrink-0 px-4 text-xs font-semibold transition-all bg-[#2563EB] hover:bg-[#1D4ED8] active:scale-[0.98] text-white border border-dashed border-[#7EB8F7]', loading: 'bg-[#EDF2FA] text-[#7B93B0] cursor-not-allowed border-[#C8D8EC]', disabled: 'bg-[#EDF2FA] text-[#7B93B0] cursor-not-allowed border-[#C8D8EC]' },
    responsePanel:       'h-full border-t border-dashed border-[#93A3B8] flex flex-col',
    responseStatus:      { base: 'text-[10px] px-1.5 py-0.5 font-mono font-semibold border border-dashed bg-[#EDF2FA] text-[#475569] border-[#93A3B8]', success: 'bg-[#F0FDF4] text-[#14532D] border-[#86EFAC]', redirect: 'bg-[#EFF6FF] text-[#1E40AF] border-[#93C5FD]', clientError: 'bg-[#FFFBEB] text-[#92400E] border-[#FCD34D]', serverError: 'bg-[#FEF2F2] text-[#991B1B] border-[#FCA5A5]' },
    responseTime:        'text-[10px] text-[#7B93B0] font-mono border border-dashed border-[#93A3B8] px-1.5 py-0.5',
    responseSize:        'text-[10px] text-[#7B93B0] font-mono',
    responseTabs:        'flex items-center gap-2 px-4 py-2 border-b border-dashed border-[#93A3B8] bg-[#EDF2FA]/60 shrink-0',
    responseTab:         { base: 'px-2.5 py-1 text-[10px] font-medium transition-colors text-[#7B93B0] hover:text-[#334155]', active: 'bg-[#F4F7FC] text-[#334155] border border-dashed border-[#93A3B8]' },
    responseBody:        'flex-1 overflow-auto bg-[#F4F7FC]',
    responseEmpty:       'shrink-0 border-t border-dashed border-[#93A3B8] h-10 flex items-center justify-center text-[10px] text-[#C8D8EC]',
    errorBanner:         'mx-5 mb-4 px-3 py-2 bg-[#FEF2F2] border border-dashed border-[#FCA5A5] text-xs text-[#991B1B]',
  },

  authStatus: {
    sectionLabel:      'text-[10px] font-semibold uppercase tracking-wider text-[#7B93B0] mb-3',
    emptyText:         'text-[10px] text-[#7B93B0]',
    schemeRow:         'flex items-center justify-between py-2.5 px-3 border border-dashed border-[#93A3B8] bg-[#EDF2FA]/60',
    schemeName:        'text-[11px] font-mono text-[#334155]',
    schemeType:        'ml-1.5 text-[10px] text-[#7B93B0]',
    authorizedBadge:   'text-[9px] text-[#14532D] bg-[#F0FDF4] border border-dashed border-[#86EFAC] px-1.5 py-0.5 font-semibold uppercase tracking-wide',
    unauthorizedBadge: 'text-[9px] text-[#7B93B0] bg-[#EDF2FA] border border-dashed border-[#93A3B8] px-1.5 py-0.5 uppercase tracking-wide',
  },

  bodyEditor: {
    fileInput:    'block w-full text-xs text-[#475569] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:border file:border-dashed file:border-[#93A3B8] file:text-xs file:font-medium file:bg-[#EDF2FA] file:text-[#475569] hover:file:bg-[#DCE8F8]',
    formatButton: 'absolute top-1.5 right-1.5 z-10 text-[10px] text-[#7B93B0] hover:text-[#2563EB] transition-colors px-1.5 py-0.5 hover:bg-[#DCE8F8]',
    textarea:     'w-full text-[11px] border border-dashed border-[#93A3B8] px-3 py-2.5 bg-[#F4F7FC] text-[#334155] placeholder-[#93A3B8] focus:outline-none focus:ring-1 focus:ring-[#2563EB] focus:border-[#2563EB] font-mono resize-y transition-colors leading-relaxed',
  },

  paramLabel: {
    nameText:        'font-mono text-[11px] text-[#334155]',
    nameDeprecated:  'font-mono text-[11px] line-through text-[#93A3B8]',
    locPath:         'text-[9px] font-mono border border-dashed border-[#D4A56A] px-1.5 py-0.5 leading-none text-[#92400E] bg-[#FFF7ED]',
    locQuery:        'text-[9px] font-mono border border-dashed border-[#67E8F9] px-1.5 py-0.5 leading-none text-[#164E63] bg-[#ECFEFF]',
    locHeader:       'text-[9px] font-mono border border-dashed border-[#93C5FD] px-1.5 py-0.5 leading-none text-[#1E40AF] bg-[#EFF6FF]',
    locCookie:       'text-[9px] font-mono border border-dashed border-[#D8B4FE] px-1.5 py-0.5 leading-none text-[#6B21A8] bg-[#FAF5FF]',
    locForm:         'text-[9px] font-mono border border-dashed border-[#86EFAC] px-1.5 py-0.5 leading-none text-[#14532D] bg-[#F0FDF4]',
    locDefault:      'text-[9px] font-mono border border-dashed border-[#93A3B8] px-1.5 py-0.5 leading-none text-[#475569] bg-[#EDF2FA]',
    typeBadge:       'text-[9px] font-mono border border-dashed border-[#D8B4FE] text-[#6B21A8] bg-[#FAF5FF] px-1.5 py-0.5 leading-none',
    requiredBadge:   'text-[9px] font-semibold border border-dashed border-[#FCA5A5] text-[#991B1B] bg-[#FEF2F2] px-1.5 py-0.5 leading-none',
    deprecatedBadge: 'text-[9px] font-semibold border border-dashed border-[#FCD34D] text-[#92400E] bg-[#FFFBEB] px-1.5 py-0.5 leading-none',
    constraintBadge: 'text-[9px] font-mono border border-dashed border-[#93A3B8] text-[#475569] bg-[#EDF2FA] px-1.5 py-0.5 leading-none',
    tooltipIcon:     'w-3.5 h-3.5 text-[#7B93B0] cursor-help hover:text-[#475569] transition-colors',
    tooltipPopup:    'pointer-events-none absolute bottom-full right-0 mb-2 w-56 bg-[#334155] border border-dashed border-[#475569] px-2.5 py-2 text-[10px] text-[#EDF2FA] leading-snug shadow-lg opacity-0 group-hover/tip:opacity-100 transition-opacity z-50',
  },

  responsePanel: {
    loadingState:  'shrink-0 border-t border-dashed border-[#93A3B8] h-16 flex items-center justify-center gap-2 text-xs text-[#7B93B0] bg-[#EDF2FA]/50',
    emptyState:    'shrink-0 border-t border-dashed border-[#93A3B8] h-10 flex items-center justify-center',
    emptyText:     'text-[10px] text-[#C8D8EC]',
    container:     'h-full border-t border-dashed border-[#93A3B8] flex flex-col',
    tabBar:        'flex items-center gap-2 px-4 py-2 border-b border-dashed border-[#93A3B8] bg-[#EDF2FA]/60 shrink-0',
    tab:           { base: 'px-2.5 py-1 text-[10px] font-medium transition-colors text-[#7B93B0] hover:text-[#334155]', active: 'bg-[#F4F7FC] text-[#334155] border border-dashed border-[#93A3B8]' },
    tabDivider:    'w-px h-3 bg-[#C8D8EC] mx-1',
    headerCount:   'ml-0.5 text-[#C8D8EC]',
    copyButton:    { base: 'flex items-center gap-1 text-[10px] px-2 py-1 hover:bg-[#EDF2FA] transition-colors text-[#7B93B0] hover:text-[#334155]', copied: 'text-[#14532D]' },
    statusNeutral: 'text-[10px] border border-dashed px-1.5 py-0.5 font-mono font-semibold text-[#475569] bg-[#EDF2FA] border-[#93A3B8]',
    statusSuccess: 'text-[10px] border border-dashed px-1.5 py-0.5 font-mono font-semibold text-[#14532D] bg-[#F0FDF4] border-[#86EFAC]',
    statusError:   'text-[10px] border border-dashed px-1.5 py-0.5 font-mono font-semibold text-[#991B1B] bg-[#FEF2F2] border-[#FCA5A5]',
    bodyContainer: 'flex-1 overflow-auto bg-[#F4F7FC]',
    bodyPre:       'text-[11px] p-3 text-[#334155] font-mono leading-relaxed',
    headersPre:    'text-[11px] p-3 text-[#475569] font-mono leading-relaxed',
  },

  sendBar: {
    container:          'px-5 py-3 border-b border-dashed border-[#93A3B8] shrink-0 bg-[#EDF2FA]/50',
    urlBox:             'flex items-center gap-2 flex-1 min-w-0 bg-[#F4F7FC] px-2.5 py-2 border border-dashed border-[#93A3B8]',
    urlCode:            'text-[10px] text-[#475569] leading-tight flex-1 min-w-0 break-all',
    sendButtonActive:   'shrink-0 px-4 text-xs font-semibold transition-all bg-[#2563EB] hover:bg-[#1D4ED8] active:scale-[0.98] text-white border border-dashed border-[#7EB8F7]',
    sendButtonDisabled: 'shrink-0 px-4 text-xs font-semibold transition-all bg-[#EDF2FA] text-[#93A3B8] border border-dashed border-[#C8D8EC] cursor-not-allowed',
  },

  inputScalar: {
    input:        'w-full text-xs border border-dashed border-[#93A3B8] px-3 py-2 bg-[#F4F7FC] text-[#334155] placeholder-[#93A3B8] focus:outline-none focus:ring-1 focus:ring-[#2563EB] focus:border-[#2563EB] transition-colors font-mono',
    inputInvalid: 'w-full text-xs border border-dashed border-[#FCA5A5] px-3 py-2 bg-[#F4F7FC] text-[#334155] placeholder-[#93A3B8] focus:outline-none focus:ring-1 focus:ring-[#991B1B] focus:border-[#991B1B] transition-colors font-mono',
  },

  inputBoolean: {
    select:        'w-full text-xs border border-dashed border-[#93A3B8] px-3 py-2 bg-[#F4F7FC] text-[#334155] focus:outline-none focus:ring-1 focus:ring-[#2563EB] focus:border-[#2563EB] transition-colors font-mono',
    selectInvalid: 'w-full text-xs border border-dashed border-[#FCA5A5] px-3 py-2 bg-[#F4F7FC] text-[#334155] focus:outline-none focus:ring-1 focus:ring-[#991B1B] transition-colors font-mono',
  },

  inputEnum: {
    select:        'w-full text-xs border border-dashed border-[#93A3B8] px-3 py-2 bg-[#F4F7FC] text-[#334155] focus:outline-none focus:ring-1 focus:ring-[#2563EB] focus:border-[#2563EB] transition-colors font-mono',
    selectInvalid: 'w-full text-xs border border-dashed border-[#FCA5A5] px-3 py-2 bg-[#F4F7FC] text-[#334155] focus:outline-none focus:ring-1 focus:ring-[#991B1B] transition-colors font-mono',
  },

  inputFile: {
    input: 'block w-full text-xs text-[#475569] cursor-pointer file:mr-3 file:py-1.5 file:px-3 file:border file:border-dashed file:border-[#93A3B8] file:text-xs file:font-medium file:bg-[#EDF2FA] file:text-[#475569] hover:file:bg-[#DCE8F8]',
  },

  inputArray: {
    rowInput:        'flex-1 text-xs border border-dashed border-[#93A3B8] px-3 py-2 bg-[#F4F7FC] text-[#334155] placeholder-[#93A3B8] focus:outline-none focus:ring-1 focus:ring-[#2563EB] focus:border-[#2563EB] transition-colors font-mono',
    rowInputInvalid: 'flex-1 text-xs border border-dashed border-[#FCA5A5] px-3 py-2 bg-[#F4F7FC] text-[#334155] placeholder-[#93A3B8] focus:outline-none focus:ring-1 focus:ring-[#991B1B] transition-colors font-mono',
    rowIndex:        'text-[9px] text-[#C8D8EC] font-mono w-4 text-right shrink-0',
    removeButton:    'shrink-0 w-5 h-5 flex items-center justify-center text-[#C8D8EC] hover:text-[#991B1B] hover:bg-[#FEF2F2] disabled:opacity-0 transition-colors',
    addButton:       'flex items-center gap-1 text-[10px] text-[#2563EB] hover:text-[#1D4ED8] transition-colors',
    hint:            'text-[9px] text-[#C8D8EC] font-mono',
  },

  inputMultiSelect: {
    trigger:        'w-full text-xs border border-dashed border-[#93A3B8] px-3 py-2 bg-[#F4F7FC] text-[#334155] focus:outline-none focus:ring-1 focus:ring-[#2563EB] focus:border-[#2563EB] transition-colors font-mono flex items-center justify-between text-left',
    triggerInvalid: 'w-full text-xs border border-dashed border-[#FCA5A5] px-3 py-2 bg-[#F4F7FC] text-[#334155] focus:outline-none focus:ring-1 focus:ring-[#991B1B] transition-colors font-mono flex items-center justify-between text-left',
    placeholder:    'text-[#93A3B8]',
    dropdown:       'absolute z-20 mt-1 w-full border border-dashed border-[#93A3B8] bg-[#F4F7FC] shadow-lg py-1',
    dropdownItem:   'flex items-center gap-2 px-3 py-1.5 hover:bg-[#EDF2FA] cursor-pointer',
    optionText:     'text-xs font-mono text-[#334155]',
  },

  inputObject: {
    textarea:        'w-full text-xs border border-dashed border-[#93A3B8] px-3 py-2 bg-[#F4F7FC] text-[#334155] placeholder-[#93A3B8] focus:outline-none focus:ring-1 focus:ring-[#2563EB] focus:border-[#2563EB] transition-colors font-mono resize-y',
    textareaInvalid: 'w-full text-xs border border-dashed border-[#FCA5A5] px-3 py-2 bg-[#F4F7FC] text-[#334155] placeholder-[#93A3B8] focus:outline-none focus:ring-1 focus:ring-[#991B1B] transition-colors font-mono resize-y',
  },

  detailPane: {
    spinner:      'w-5 h-5 animate-spin text-[#2563EB]',
    errorIcon:    'w-10 h-10 bg-[#FEF2F2] border border-dashed border-[#FCA5A5] flex items-center justify-center shrink-0 text-[#991B1B]',
    errorMessage: 'text-sm text-[#991B1B]',
    retryLink:    'text-xs text-[#7B93B0] hover:text-[#334155] underline underline-offset-2',
    emptyIcon:    'w-10 h-10 bg-[#EDF2FA] border border-dashed border-[#93A3B8] flex items-center justify-center text-[#7B93B0]',
    emptyMessage: 'text-sm text-[#7B93B0]',
  },

  verticalResizable: {
    handle: 'w-8 h-0.5 bg-[#C8D8EC] group-hover:bg-[#2563EB] transition-colors',
  },

  syntax: {
    key:     '#1E40AF',
    string:  '#14532D',
    boolean: '#6B21A8',
    null:    '#7B93B0',
    number:  '#92400E',
  },

  paneHandle:  'bg-[#C8D8EC] group-hover:bg-[#2563EB] group-hover:w-0.5 group-[.dragging]:bg-[#2563EB] group-[.dragging]:w-0.5',
  focusRing:   'focus:ring-2 focus:ring-[#2563EB] focus:ring-offset-1',
  scrollbar:   { thumb: 'bg-[#C8D8EC]', thumbHover: 'bg-[#93A3B8]' },
};